### ISSUE TITLE
Open Issues/PRs using repositories from another instance

### ISSUE THREAD

**Issue by randomdudette** [gogits/gogs#3635] opened 2016-09-10 08:46 UTC
- Gogs version (or commit ref):  try.gogs.io
- Git version:   try.gogs.io
- Operating system:  try.gogs.io
- Database (use `[x]`):  try.gogs.io
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes   https://try.gogs.io/wakawaka/repo
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I like Gogs because I can install my own instance, and other people can do the same (unlike github, that if it goes offline everybody stops working!). One of the major issues that I have is collaboration. If I run my own instance, and other people run their instance, it's hard to collaborate (write issues and open pull requests) because I have to create a new user account on every instance. I would **love** if Gogs could add a feature such that I can

- open a new PR on another person' instance using a Git repo hosted somewhere else (for example in another Gogs instance or maybe github too)
- open a new Issue on another person' instance without having to create a new account (maybe this would work if Gogs had openid/oauth?)

**Comment by randomdudette** [comment] 2016-09-10 14:01
@saboya thumbs down? Care to elaborate more? Otherwise your input is basically worthless

**Comment by saboya** [comment] 2016-09-10 16:54
@randomdudette I think this is completely outisde the scope of the project, and a really specific use case. I can't really see the benefits, or how it could be done cleanly,

**Comment by strk** [comment] 2016-10-05 09:23
#3131 is a more generic approach to this problem, would you consider closing this ticket in favor of that one ?

**Comment by bkcsoft** [comment] 2016-10-05 10:41
Duplicate of #3131. Closing

**Closed by bkcsoft** 2016-10-05 10:41 UTC
