### ISSUE TITLE
Disable password change if using external authentication, eg AD

### ISSUE THREAD

**Issue by bhchew** [gogits/gogs#2144] opened 2015-12-11 05:20 UTC
If change password settings page doesn't support changing external authentication accounts passwor d like AD, think it make sense to hide the page.

**Comment by angus-g** [comment] 2015-12-11 06:05
This is a duplicate of e.g. #1938 and should be fixed in the `develop` branch

**Comment by Unknwon** [comment] 2015-12-11 07:48
Thanks your feedback!

As @angus-g mentioned, this is a duplicated issue, and has been fixed in `master`.

**Closed by Unknwon** 2015-12-11 07:48 UTC
