### ISSUE TITLE
The owner has reached maximum creation limit of 0 repositories.

### ISSUE THREAD

**Issue by DropMotion** [gogits/gogs#2155] opened 2015-12-11 18:25 UTC
#### Hi
----
When i want to create a repositorie in my organizations i got this error : 
```
The owner has reached maximum creation limit of 0 repositories.
```

**Comment by Unknwon** [comment] 2015-12-11 18:30
Hi, please update Gogs with latest `master`.

**Comment by DropMotion** [comment] 2015-12-11 18:31
I install gogs 5 minutes ago

**Comment by Unknwon** [comment] 2015-12-11 18:33
Which way did you install?

**Comment by DropMotion** [comment] 2015-12-11 18:33
with packager.io.

**Comment by Unknwon** [comment] 2015-12-11 18:37
That is unexpected because the last commit message I click I can see is: https://github.com/pkgr/gogs/commit/98da7241a00a13d9fd46bc5d1cec1b2a3ac01534

Which is just the fix for this issue.

**Comment by Unknwon** [comment] 2015-12-11 18:37
what is the version you see after installation?

**Comment by DropMotion** [comment] 2015-12-11 18:42
How i know that ?

**Comment by Unknwon** [comment] 2015-12-11 18:45
It shows on bottom of every page.

**Comment by DropMotion** [comment] 2015-12-11 18:47
Version: 0.7.42.1211

**Comment by Unknwon** [comment] 2015-12-11 18:49
Thanks. 

I recommend try to install through other ways to avoid the possibility that not all mirrors of packager.io have been updated.

If problem still exists in other ways, I'll reopen this issue and find out way.

**Comment by DropMotion** [comment] 2015-12-11 19:15
I try to install via source but when i do 
```
go get -u github.com/gogits/gogs
```
i got
```

can't load package: package github.com/gogits/gogs: no buildable Go source files in /root/go/src/github.com/gogits/gogs


```

**Comment by KillTheIdols** [comment] 2015-12-11 19:15
This Max Creation Limit an issue for me as well and I've just built the latest version from go/git.

**Comment by Unknwon** [comment] 2015-12-11 19:52
@DropMotion that means download was failed...

Just to confirm, are you both using SQLite3?

**Comment by KillTheIdols** [comment] 2015-12-11 19:56
Yes, I'm using SQLite3

**Comment by Unknwon** [comment] 2015-12-11 20:01
@KillTheIdols Thanks, can you check the database table `user` see what are the values for column `max_repo_creation`?

**Comment by DropMotion** [comment] 2015-12-11 20:07
@Unknwon yes i have SQlite3

**Comment by Unknwon** [comment] 2015-12-11 20:11
Just pushed another fix to `master` branch, please help test out again!

**Comment by KillTheIdols** [comment] 2015-12-11 20:37
Gave it a go, still receiving an error. The max_repo_creation is 0.
```
id|lower_name|name|full_name|email|passwd|login_type|login_source|login_name|type|location|website|rands|salt|created|updated|last_repo_visibility|max_repo_creation|is_active|is_admin|allow_git_hook|allow_import_local|avatar|avatar_email|use_custom_avatar|num_followers|num_followings|num_stars|num_repos|description|num_teams|num_members
2|lynk|lynk|Lynk|||0|0||1|||||2015-12-11 19:00:38|2015-12-11 19:18:54|1|0|1|0|0|0|||1|0|0|0|2||1|1
```

**Comment by KillTheIdols** [comment] 2015-12-11 20:40
I tried settings it to -1 and it worked, but by default it's set to 0.

**Comment by Unknwon** [comment] 2015-12-11 20:41
@KillTheIdols the account already created can't be fixed, you need go to admin panel and edit user's limit back to -1... :sweat_smile: fix only works for newly created accounts.

**Comment by KillTheIdols** [comment] 2015-12-11 20:42
I cannot edit the max repo's for an organization without direct DB modification.

**Comment by Unknwon** [comment] 2015-12-11 20:43
> I cannot edit the max repo's for an organization without direct DB modification.

This is indeed a known problem (to me), you can file an issue for this specifically.

How about newly created accounts?

**Comment by KillTheIdols** [comment] 2015-12-11 20:46
A newly created organization has max_repo_creation set to 0, a new user account has it set to -1, so maybe something is missing when creating an organization user/account?

**Comment by Unknwon** [comment] 2015-12-11 20:46
> A newly created organization has max_repo_creation set to 0, a new user account has it set to -1, so maybe something is missing when creating an organization user/account?

Thanks! Let me check.

**Comment by Unknwon** [comment] 2015-12-11 20:48
Pushed to `master` branch.

**Comment by DropMotion** [comment] 2015-12-11 20:49
Still get the same issue. I don't really understand how do you fix it @KillTheIdols

**Comment by Unknwon** [comment] 2015-12-11 20:50
@DropMotion for account already created, you can go to admin panel `/admin/users` to edit its value to `-1`.

**Comment by DropMotion** [comment] 2015-12-11 20:50
I already do that. I still get the same issue.

**Comment by KillTheIdols** [comment] 2015-12-11 20:51
Tested and confirmed working, thank @Unknwon!

@DropMotion, just pull/update and it should all work now.

**Comment by DropMotion** [comment] 2015-12-11 20:51
i'm on the version 0.7.33

**Comment by Unknwon** [comment] 2015-12-11 20:52
The latest version should be `0.7.43.1211 Beta`, and `0.7.33` does not have this feature...

**Comment by DropMotion** [comment] 2015-12-11 20:53
@Unknwon Sorry version 0.7.42.1211

**Comment by Unknwon** [comment] 2015-12-11 20:54
@DropMotion hmm, yes, you need to re-pull from `master`.

**Comment by KillTheIdols** [comment] 2015-12-11 20:57
Drop motion, you will have to recreate the organization, if this is not possible you'll have to edit the DB manually.

This fix will not fix orgs created between the new max_repo function and the fix just applied.

**Comment by DropMotion** [comment] 2015-12-11 20:59
Thanks @Unknwon and @KillTheIdols I update my server to the lasted branch and recreate my organization and it works :D

**Comment by Unknwon** [comment] 2015-12-11 21:00
Awesome! 

@KillTheIdols would you mind file the issue about `admin can't edit organization settings`?

**Comment by KillTheIdols** [comment] 2015-12-11 21:11
Issue created! We can close this one off now. :smile:

Thanks :+1:

**Comment by Unknwon** [comment] 2015-12-11 21:13
Thank you both!

**Closed by Unknwon** 2015-12-11 21:13 UTC
Labels: bug
