### ISSUE TITLE
admin email validation should validate root@localhost

### ISSUE THREAD

**Issue by dalu** [gogits/gogs#470] opened 2014-09-15 20:12 UTC
error on /install
Admin E-mail is not a valid e-mail address.

Admin Account Settings
Email* root@localhost

It should be allowed to set root@localhost or any tld for that matter

Gogs: Go Git Service 0.5.1.0915 Beta

**Comment by pitchforks** [comment] 2015-08-12 10:12
Just bumped into this, except my use case was "user@localhost", not root. Apparently the problem is the validation of the domain name. Willing to send mail locally is a very fair expectation from first time gogs users who run a local instance for getting started.

My hack was to use "user@127.0.0.1" instead, it worked. This is gogs-v0.6.3

HTH

**Comment by Unknwon** [comment] 2015-08-12 10:15
@pitchforks thanks for the info :star:

**Comment by TheHowl** [comment] 2015-09-26 22:50
I've had a look at this. I thought about doing this:

Instance uses email confirmation:

* Just do [1]

Instance doesn't use email confirmation (which means, it's probably offline):

* Classic check to see if the host matches the correct format (like we're doing now)
* If it is not, attempt [1]

[1]: validate the host to check if it has illegal characters, and then attempt a connection with [net.DialTimeout](https://golang.org/pkg/net/#DialTimeout) on port 25 (default smtp). If connection is successful (`err == nil`), the email host is fine.

**Comment by Unknwon** [comment] 2015-09-26 22:52
@TheHowl it could be much more easier by just make `localhost` valid to regexp pattern. How do you think?

**Comment by TheHowl** [comment] 2015-09-26 23:11
The problem that arisens is, there is more. For instance, I sometimes set my hosts file to connect to 127.0.0.1 when I browse to, say, "fakedomain", so I can access "http://fakedomain/". simply adding `|localhost` to the regex isn't enough.

On 27 September 2015 00:52:45 CEST, "无闻" <notifications@github.com> wrote:
>@TheHowl it could be much more easier by just make `localhost` valid to
>regexp pattern. How do you think?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gogits/gogs/issues/470#issuecomment-143502778

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sapk** [comment] 2015-09-26 23:12
A possibility could be to check if the hostname is resolvable ?

**Comment by Unknwon** [comment] 2015-09-26 23:14
@TheHowl true...

**Comment by manfer** [comment] 2015-09-28 09:20
In my opinion the correct way to do things is to allow any valid email and all emails mentioned by @dalu are valid emails as documented on RFCs about email. There can NOT be any controversy on what is and what is not a valid email address as RFCs are authoritative for that subject. There are not such a thing like what I consider a valid email as I have seen in places. That makes no sense at all.

He has already provided some links. For reference on RFCs involved you can read the wikipedia article for example:
https://en.wikipedia.org/wiki/Email_address#Syntax

Thinking this is about allowing just localhost is a mistake in my opinion. As explained by @dalu there are other use cases for a intranet where other valid emails can contain a domain part which is not a TLD. For instance foo@baz is a valid email. Where baz will be the name of a machine on the network and foo a user on that machine. Email servers are clever enough to know were they have to deliver mail and they know exactly where to deliver that mail. If it can't deliver the mail for whatever reason (including the mail doesn't exists) it will be clever enough to handle that situation. The same that it is clever enough to try to deliver mail to FDDFDSFieiekd33r.ygygleksraydcafyarpñelrea@fdalkñfakfhnmeeaealfdagt.com. This is to make clear that email validation has nothing to do with email existance and doesn't solve any problem at all. It is more an usability thing than anything else.

If someone wants to be sure clients are using a valid email they can ask for email confirmation. There is no need to complicate things about email confirmation. It is a yes/no config option, period. There is no need to try to guess if a mail exists or not. Let that task to the email server. It will try to deliver mail and if you receive or you don't the confirmation that's your confirmation.

An admin can still add a user in admin panel to avoid email confirmation if confirmation is enabled.

If for some reason you want to be able to limit the valid emails to just emails which domain part is a TLD you can add a new config option ALLOW_ONLY_TLD_DOMAINS_ON_EMAIL or similar name. I don't think it worths it.

One we have it clear that email validation is just an usability thing, and nothing more than that, then you can just decide to use a full proof regex or an almost full proof regex to simplify the regex. But if you use an almost full proof regex be sure to use one that accepts more emails than the valid ones not one that rejects valid emails. That's my opinion. There are a lot of places that show 99.9% full proof email validation when what they should be trying to achieve is a 100.1% full proof validation.

And a nice question/answer about the subject in similar terms.
http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address

**Comment by dalu** [comment] 2015-10-01 15:28
I agree with @manfer , don't overcomplicate it.
Separation of concerns.
This concern is being RFC-compliant.
Anything outside this scope is a different concern.

The way I read 3.4.1 of RFC2822 is

- check if `@` is present
- if yes split by `@` else return error
- `left := ss[0]` and `right := ss[1]`
- if whitespace or control is present on `left` return error
- if whitespace or control is present on `right` return error
- if `right` starts with `[` and doesn't end with `]` return error
- if `left` starts or ends with `.` return error
- if `right` starts or ends with `.` return error

for starters
todo: quoted pair

**Comment by tboerger** [comment] 2015-10-01 15:34
What about https://github.com/asaskevich/govalidator/blob/master/patterns.go#L7? :)

**Comment by dalu** [comment] 2015-10-01 18:58
@tboerger http://play.golang.org/p/7KjPjotuEF

**Comment by kageurufu** [comment] 2015-10-13 19:24
The only safe way to validate an email address, if validation is required, is to actually send an email to that address, and verify it is received. 

I propose a series of changes, with relevant configuration options:

1. Add email verification through a sent email

**Comment by Unknwon** [comment] 2015-10-13 19:26
I think we're off topic here, this thread is about validate **admin** e-mail address.

**Comment by kageurufu** [comment] 2015-10-13 19:28
@Unknwon, the same rules could be used to validate admin and user emails. I host on a virtual machine, with the hostname ```git```. In my case, root@git is a valid email, and the only way to prove this is through domain resolution, or full email verification.

Or, let the user decide they don't need it verified, with a configuration option

**Comment by Unknwon** [comment] 2015-10-13 19:31
@kageurufu the problem is how to validate an admin's e-mail while the "admin" is filling the form of Gogs system e-mail account to send a verification e-mail?

**Comment by Unknwon** [comment] 2015-10-13 19:34
Could we just assume that in the install form, whatever the value of admin's e-mail is acceptable?

**Comment by dalu** [comment] 2015-10-18 21:23
As long as it has an `@` and is at least 3 bytes long

**Comment by Unknwon** [comment] 2015-10-18 21:24
@dalu :beers:

**Comment by dalu** [comment] 2015-10-22 12:42
Sure if you're ever near Stuttgart I'll invite you @Unknwon :)

**Comment by manfer** [comment] 2015-10-22 22:18
Though it will not solve the server side validation, probably is worth using html5 type email inputs when you need an email on a form.

http://www.w3.org/TR/html5/forms.html#e-mail-state-(type=email)
http://www.w3.org/TR/html5/forms.html#valid-e-mail-address

**Comment by Unknwon** [comment] 2015-10-30 01:11
@dalu @manfer `develop` branch now added both `email` type check for at least 3 bytes and must contain `@`. https://github.com/gogits/gogs/commit/7d72c8333e05b377d42fb773ef2d952c8ec87d32#diff-746f2e6ce527e335d63b08535b05106cR47

**Comment by dalu** [comment] 2015-11-02 00:45
I don't know if the error message was client side only or also server side.
`type="email1"` seems like a typo to me

**Comment by Unknwon** [comment] 2015-11-02 02:10
@dalu yes, was fixed in next commit :D

**Comment by Unknwon** [comment] 2015-11-03 19:07
Close as fixed.

**Closed by Unknwon** 2015-11-03 19:07 UTC
Labels: bug, feedback needed
