### ISSUE TITLE
Gogs not rendering escaped characters in organisation names correctly. 

### ISSUE THREAD

**Issue by alfiepates** [gogits/gogs#3173] opened 2016-06-07 00:24 UTC
- Gogs version (or commit ref): v0.9.13
- Operating system: Linux, AMD64
- Database: SQLite

## Description

Simple little bug today. I created an organisation, and then edited an apostrophe (`'`) into the organisation's full name. The name was stored and rendered with a `&#39;` in place of the apostrophe, which isn't exactly the prettiest. 

Prod example at https://git.alfiepates.me/alfies-dotfiles

**Comment by bkcsoft** [comment] 2016-06-07 02:46
Closing as duplicate of #1937

**Closed by bkcsoft** 2016-06-07 02:46 UTC

**Comment by alfiepates** [comment] 2016-06-07 18:35
Apologies, Search didn't turn anything up. Or maybe I didn't search hard enough, one of the two.
