### ISSUE TITLE
500 error while creating pull request

### ISSUE THREAD

**Issue by gshan88** [gogits/gogs#3699] opened 2016-09-26 04:32 UTC
- Gogs version (or commit ref): 0.9.99
- Git version:  2.6.6
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ X] Not relevant
- Log gist:
## Description

We are getting 500 error while creating pull request. Please find the gogs log.

[E] NewPullRequest: testPatch: UpdateLocalCopy: git checkout <branch_name>: exit status 1 - error: you need to resolve your current index first

...

**Comment by LefsFlarey** [comment] 2016-09-26 05:42
Hello,

It appears that this error is not caused by Gogs but rather the git repository. Can you double-check that both branches you are trying to create a pull request for, can be merged?

**Comment by drm** [comment] 2016-09-29 10:09
I have the same issue. Trouble is that gogs does not keep it's local checkout up-to-date with the remote.

Going into the docker into `/data/gogs/data/tmp/local-rpeo/[id]` and doing a `git fetch --prune` fixes the problem. Easiest way to find the correct id of the repo is to check the "fork" link in the HTML source. Otherwise either use `find` or open the MySQL database to find the correct id.

**Comment by gshan88** [comment] 2016-09-30 06:33
Thanks!

**Comment by drm** [comment] 2016-10-02 14:19
Removing the entire `local-rpeo`'s contents fixes the issue also, btw. But, gogs should keep it in check, nonetheless, of course

**Comment by LefsFlarey** [comment] 2016-10-03 02:29
Strange, I'm completely unable to reproduce this error, was any edition or tampering made to the repository folder on Gogs?

**Comment by GottemHams** [comment] 2016-10-07 13:07
Just chiming in to say I have a similar issue, but the fix/workaround posted here doesn't seem to apply to me. I don't have the `data/tmp` folder since that may be something Docker-exclusive?

The error I get:
`[...routers/repo/pull.go:524 ParseCompareInfo()] [E] GetPullRequestInfo: GetMergeBase: exit status 1`

I'm using Gogs `v0.9.85.0824` by the way, built from source.

**Comment by rainysia** [comment] 2016-10-28 07:24
Hi, I have the same problem, and the same latest version.

`...routers/repo/pull.go:710 CompareAndPullRequestPost()] [E] NewPullRequest: testPatch: UpdateLocalCopy: git checkout
develop: exit status 1 - error: Your local changes to the following files would be overwritten by checkout:
`

**Comment by Tectu** [comment] 2016-11-14 21:13
I was having the exact same problem with version 0.9.99.0915 today. Following @drm 's advice worked well.

**Comment by richbl** [comment] 2016-12-23 02:22
All, I'm able to confirm both the problem and solution (@drm, running `git fetch --prune`).

I'm running 0.9.97.0901 on a standalone server (not Docker).

Rich

**Comment by Unknwon** [comment] 2016-12-24 00:38
As @drm advised, I added `git fetch --prune` before `git checkout`. Please help test against `develop` branch!

**Comment by FarooqKhan** [comment] 2017-01-11 15:34
I have similar but slightly different problem. We get a Server Error 500 each time we create a pull request. The pull request creation operation takes a long time and eventually gives 500 but does succeed in the background.

The logs shows this: [...routers/repo/pull.go:700 CompareAndPullRequestPost()] [E] NewPullRequest: newIssue: Error 1062: Duplicate entry '12-90' for key 'UQE_issue_REPO_INDEX'
2017/01/11 15:21:02 [D] Template: status/500

My Gogs Version is: 0.9.115.0103

**Comment by Unknwon** [comment] 2017-01-22 11:14
@FarooqKhan I think the problem you met was caused in old version of Gogs which could possibly create same index number for issue and pull request, which is conflict under unique rule.

**Closed by Unknwon** 2017-01-22 11:14 UTC
Labels: kind/bug, status/needs feedback
