### ISSUE TITLE
Organiation members can't see teams

### ISSUE THREAD

**Issue by wolkenschieber** [gogits/gogs#3222] opened 2016-07-01 06:07 UTC
- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.7.4
- Operating system: Ubuntu 16.04
- Database: SQLite

## Description

I have created an organization and added people to it. These people are organized in teams.

If a normal user browses the organization site, he sees the members in the people panel, but the teams panel is empty. Only the site admin and the organization owner see the teams.

**Comment by mbugeia** [comment] 2016-07-04 10:11
Hi,
Same issue for me, I think it's a duplicate of #3031 (and maybe fixed by #3048 )

**Comment by Unknwon** [comment] 2016-07-07 23:50
Thanks @mbugeia !

**Closed by Unknwon** 2016-07-07 23:50 UTC
Labels: kind/bug
