### ISSUE TITLE
Add support to "approve" pull requests

### ISSUE THREAD

**Issue by nicolai86** [gogits/gogs#1663] opened 2015-09-19 20:11 UTC
This  would help with code reviews since one could configure a repository to enforce PR approval by certain users. Also in corporate environments PRs sometimes need to be checked and approved before being merged, which is a feature eg gitlab offers. 

We could implement a tiny version like this:
- opt in per repo
- also checkbox if new commits invalidate existing approvals
- every user /w write access can approve if enabled

However, we first should implement the line based commenting for this to be useful. See #1644 

What do you think?

**Comment by Unknwon** [comment] 2015-09-21 14:08
Sounds good!

But for 

>  sometimes need to be checked and approved before being merged,

I don't quite understand about this one.

**Comment by hhenkel** [comment] 2015-09-22 07:19
I agree with @nicolai86 that this would be a useful feature in a corporate environment. Currently we are using gitblit with its ticket functionality.  We have several repositories where people open up pull requrests (tickets) and someone else needs to review and approve the changes. Those review and voting could also be done via CI system like jenkins - if the test build is successfully the jenkins server votes on the pull request so that it could be merged. To be able to do something like that, we have dependencies to the api/webhooks.

For a first implementation that @nicolai86 described I would love to see a simple voting system, maybe something similar to [gitblit ticket reviews](http://www.gitblit.org/tickets_using.html#H19), but I'm also open to other systems.

**Comment by Unknwon** [comment] 2015-09-24 21:27
@hhenkel thanks your info!

From what I understand:

1. Collaborators(with write access) can vote up/down
2. In the future, CI or whatever service can be count as 1 vote up/down

Is this the mechanism you're talking about?

**Comment by nicolai86** [comment] 2015-09-25 06:18
@unknwon plus, you can configure a repo that a pull request can only be merged when +1/+2 has been reached.

**Comment by Unknwon** [comment] 2015-09-25 14:07
I got the idea, thanks1

**Comment by joubertredrat** [comment] 2015-10-16 20:12
+1 
I like this

**Comment by haliphax** [comment] 2015-12-11 20:39
I think even having Jenkins be able to comment on a pull request to say whether it was built successfully or not would be a **huge** feature to have. Then, I wouldn't have to manually build anything that's being sent as a PR to see if it breaks the build.

**Comment by doliver3** [comment] 2015-12-27 05:06
Yes, this an important feature. Please add it.

**Comment by mgracer48** [comment] 2015-12-31 12:54
+100000000

**Comment by renewsorensen** [comment] 2016-04-04 08:32
+1

**Comment by rudineirk** [comment] 2016-04-12 18:22
+1

**Comment by hrobertson** [comment] 2016-07-05 12:47
This appears to be a duplicate of https://github.com/gogits/gogs/issues/776 (Protected Branches)

**Comment by strk** [comment] 2016-07-18 07:41
Agreed about this being a duplicate of #776

**Closed** 2016-07-18 10:05 UTC
Labels: kind/feature

**Comment by niklaskorz** [comment] 2018-11-11 11:19
Am I missing something or has this actually not been implemented by #776 after all?

**Comment by tnatanael** [comment] 2019-08-08 19:31
#776 protected branches do not addressed PR Aprovals...
This is not a duplicate and should be reopened as this feature is very important on a collaborative team.
