### ISSUE TITLE
Protect branch: whitelist should bypass require pull request check

### ISSUE THREAD

**Issue by nbullock** [gogits/gogs#4207] opened 2017-02-28 15:32 UTC
- Gogs version (or commit ref): 0.10
- Git version: 2.11.1.windows.1
- Operating system: Windows Server 2012 R2
- Database
  - SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - No

I have encountered an issue affecting both webhooks and the dashboard page, possibly related.

The issue is that after a certain date, I stopped seeing push notifications on the dashboard of any of my Gogs organisations (or my own homepage).  At what appears to be the same time, webhooks for push requests stopped being triggered.  They do not appear in the webhook history.  I can go into repos and I can see commits which are not mentioned on the dashboard, and for which no webhook message was sent - the actual functioning of the repos is fine, I can push code without an issue.

For reference, the webhooks are configured at the organisation level, not repo level, and I have two - one for pushes (which doesn't fire at all) and one for pull notifications, which works fine.

Every repo appears to be affected.

Pull requests appear on the dashboard, and webhook messages are sent as normal - it's just pushes that don't appear (other things like repo creation also appear fine).

I did upgrade to the previous version - 0.10RC - on the same day this started happening, but it was 6 hours before anything started behaving oddly so I'm not sure if this could be the cause or not.  I am now on v0.10.

**Comment by Unknwon** [comment] 2017-02-28 15:41
I think this could be caused by recent changes to Git hooks. First to clarify:

Your Git hooks wasn't execute in the first place, right now Gogs "correctly" not giving you push updates on dashboard because the hidden bug is now revealed.

Are you running as Windows service?

**Comment by nbullock** [comment] 2017-02-28 17:33
Yes, running as Windows service.

**Comment by Unknwon** [comment] 2017-02-28 17:38
Thanks for the confirm, currently I have no idea why Git hooks are not being called on Windows run as service.

**Comment by Unknwon** [comment] 2017-03-01 03:59
Hi @nbullock , can you try latest `develop` branch? I just pushed a fix.

**Comment by nbullock** [comment] 2017-03-01 08:48
@Unknwon I now get the following error when trying to push...

The following errors were reported during push:
	refs/heads/develop, pre-receive hook declined

**Comment by nbullock** [comment] 2017-03-02 08:00
Turned out it was my fault anyway - I was trying to push to a protected branch (although I am whitelisted, so not sure if that's a separate issue, I need to try again).  Once I turned off branch protection, I can confirm that the original issue seems to be fixed - I now have the push on the dashboard, and the webhook executed.

**Comment by Unknwon** [comment] 2017-03-02 12:26
@nbullock Good to know... but you need to give me CLI push output.

**Comment by nbullock** [comment] 2017-03-02 13:29
First attempt where it didn't work

    Counting objects: 4, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (4/4), done.
    Writing objects: 100% (4/4), 478 bytes | 0 bytes/s, done.
    Total 4 (delta 3), reused 0 (delta 0)
    remote: Gogs: Branch 'develop' is protected and commits must be merged through pull request
    To http://git.emeadev.local:9000/UniversalSystem/Universal-Common.git
     ! [remote rejected] develop -> develop (pre-receive hook declined)
    error: failed to push some refs to 'http://git.emeadev.local:9000/UniversalSystem/Universal-Common.git'

Second attempt where it did work (after I turned off branch protection)

    Counting objects: 4, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (4/4), done.
    Writing objects: 100% (4/4), 478 bytes | 0 bytes/s, done.
    Total 4 (delta 3), reused 0 (delta 0)
    To http://git.emeadev.local:9000/UniversalSystem/Universal-Common.git
       ffa82d3..beb6f3f  develop -> develop

**Comment by Unknwon** [comment] 2017-03-02 13:31
>remote: Gogs: Branch 'develop' is protected and commits must be merged through pull request

OK... turns out Gogs is working, but raises questions, can whitelist person bypass the pull request check? Maybe yes?

**Comment by nbullock** [comment] 2017-03-02 13:45
I think there are times I would like to be able to bypass the pull request requirement while still having it enforced for others.

**Comment by Unknwon** [comment] 2017-03-02 13:53
@nbullock I think **require pull request** and **whitelist** can't be enabled at same time, because other people already couldn't push because they're not in the whitelist.

**Comment by Unknwon** [comment] 2017-03-02 13:55
For now, to make whitelist work, you can just uncheck require pull request.

**Comment by Unknwon** [comment] 2017-03-08 21:44
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Closed** 2017-03-10 22:57 UTC
Labels: kind/enhancement, status/needs feedback
