### ISSUE TITLE
View comparison for these 2 commits, returns 404

### ISSUE THREAD

**Issue by Infernuza** [gogits/gogs#864] opened 2015-01-17 21:35 UTC
I don't know what this is, but clicking on the link will lead to an invalid page.

Notice that hovering "View comparison for these 2 commits", returns wrong base url somehow. Changing it to the right one, will return a 404 page error. 

Is it a missconfiguration problem, or something else?

![untitled](https://cloud.githubusercontent.com/assets/4332609/5790449/e4095306-9e98-11e4-8fb7-d786093909ca.png)

**Comment by Infernuza** [comment] 2015-01-17 21:35
Oh and besides, gravatars doesn't seem to work.

**Comment by Infernuza** [comment] 2015-01-27 21:57
Still having problems with it. Any solution avaliable?

**Comment by C00Lzero** [comment] 2015-02-28 20:28
i can reproduce this in the current version on packager.io
the gravatar-problem: don't know - this works here fine. 

as for the 404: this will happen, if you use e.g. nginx as proxy-server. 
the comparison-link looks like hardcoded and don't use relative paths. 

if you change the path manually it should work.

**Comment by C00Lzero** [comment] 2015-02-28 20:45
if s.o. will read this: 
https://github.com/gogits/gogs/blob/master/models/action.go#L264
setting.AppUrl will contain the port - which won't work with nginx-proxy.

**Comment by Unknwon** [comment] 2015-03-01 05:47
@C00Lzero thanks for the tip!

**Comment by undersky** [comment] 2015-06-11 05:17
@C00Lzero Can you tell me how to  change the path manually to fix  comparison-link error?

**Comment by C00Lzero** [comment] 2015-06-11 06:27
@undersky the easiest way would be to just replace setting.AppUrl (now line 293) with the relative Path "/" - this could work 
or just replace it as follows: 
`repoLink := fmt.Sprintf("/%s/%s", repoUserName, repoName)`
- though i haven't tested it yet, since atm i don't have access to my server, and i don't find the creation of this variable within git sorry. 
i'm not so sure what exactly is depended on this action, so please test it, before you deploy this somewhere

**Comment by Unknwon** [comment] 2015-07-26 09:21
From what I know by testing so far, it is caused by user(you) didn't config `[server] ROOT_URL` right. But I'm going to change it to only sore relative path of repository, so no matter when your application changes, those links are still working.

**Comment by Unknwon** [comment] 2015-07-26 12:43
My bad, the URl is fixed in the database so change your ROOT_URL afterwards couldn't help.

But I'm going to change this behavior to add URL prefix after read action content from database.

**Comment by Unknwon** [comment] 2015-07-26 14:09
Fixed by `develop` branch.

**Closed** 2015-07-27 18:36 UTC
Labels: bug, feedback needed
