### ISSUE TITLE
Feature Request: Asciidoctor

### ISSUE THREAD

**Issue by toplac** [gogits/gogs#3994] opened 2016-12-28 13:05 UTC
Hey Guys, 

do you think it is possible to add asciidoctor support (https://github.com/asciidoctor/asciidoctor) for README files and Wiki Pages like GitHub does?

**Comment by sluedecke** [comment] 2016-12-28 20:40
Duplicate of https://github.com/gogits/gogs/issues/2097

**Closed** 2016-12-29 09:28 UTC
