### ISSUE TITLE
Out of Memory crash

### ISSUE THREAD

**Issue by gerroon** [gogits/gogs#3823] opened 2016-10-28 04:02 UTC
I was trying to push a big repo (about 11 gb) and this is what happened.

I am on Debian Wheezy 32 bit running with apache 2.2

https://paste.debian.net/hidden/10b05cd2/

I had to copy paste from the termianl so I might have double pasted here and there.

016/10/27 09:47:17 [T] Custom path: /opt/gogs/custom
2016/10/27 09:47:17 [T] Log path: /opt/gogs/log
2016/10/27 09:47:17 [I] Gogs: Go Git Service 0.9.97.0901
2016/10/27 09:47:17 [I] Build Time: 2016-09-01 06:10:22 UTC
2016/10/27 09:47:17 [I] Build Git Hash: 8ee14db
2016/10/27 09:47:17 [I] Log Mode: File(Info)
2016/10/27 09:47:17 [I] Cache Service Enabled
2016/10/27 09:47:17 [I] Session Service Enabled
2016/10/27 09:47:17 [I] Git Version: 1.7.10.4
2016/10/27 09:47:17 [T] Doing: CheckRepoStats
2016/10/27 09:47:17 [I] SQLite3 Supported
2016/10/27 09:47:17 [I] Run Mode: Production
2016/10/27 09:47:17 [I] Listen: http://0.0.0.0:3000

**Comment by stroucki** [comment] 2016-10-29 00:45
You apparently ran out of memory or on a 32 bit system you can't have more than 3 GB per process allocated anyway.

Last gogs line in the stack trace is
```
github.com/gogits/gogs/routers/repo.serviceRPC(0x1a3d2b18, 0xb5bd6ad8, 0x1a3d0f20, 0x1a41e200, 0x1a428570, 0x2c, 0x1a38b730, 0x10, 0x8a2841f, 0xc)
        /home/vagrant/gopath/src/github.com/gogits/gogs/routers/repo/http.go:367 +0x436 fp=0x1a0ac950 sp=0x1a0ac858
```

You could probably commit via ssh instead.

**Comment by bkcsoft** [comment] 2016-11-11 15:13
Duplicate of #636

**Closed by bkcsoft** 2016-11-11 15:13 UTC
