### ISSUE TITLE
Restore data from dump command

### ISSUE THREAD

**Issue by Flux159** [gogits/gogs#2925] opened 2016-04-04 14:07 UTC
Currently there is a ./gogs dump command that will generate a backup, but no way to automatically restore back.

As referenced here: https://discuss.gogs.io/t/suggestion-on-repository-load-balancing-and-replication-hot-backup-strategy/182/8

**Comment by zacheryph** [comment] 2016-05-11 03:04
#648

**Comment by bkcsoft** [comment] 2016-05-26 00:01
Closing as duplicate of #648 
Also see PR #3109

**Closed by bkcsoft** 2016-05-26 00:01 UTC
Labels: dont send pull request, kind/feature
