### ISSUE TITLE
Install page comes up nearly every day

### ISSUE THREAD

**Issue by Cedware** [gogits/gogs#1897] opened 2015-11-05 07:40 UTC
Nearly every day when I navigate to my gogs service, the install page comes up again, i think this happens after every update.
I installed gogs with the packager.io package.

**Comment by Unknwon** [comment] 2015-11-05 20:04
Thanks your feedback!

@crohr : can Packager.io check if the `INSTALL_LOCK = true` or need some other ways to help with on my side?

**Comment by Unknwon** [comment] 2015-11-07 23:32
Ping @crohr (I'm sorry that always @ you :sob:)

**Comment by crohr** [comment] 2015-11-10 10:42
@Unknwon where is this variable set? If it is set in the global conf, could you change it so that it is written in the custom conf if a custom conf file is present? Otherwise every time a new version is installed, the global (example) config that comes with the package gets overwritten, since the package configuration uses a custom conf file.

**Comment by Unknwon** [comment] 2015-11-10 17:53
@crohr after install, this value will be changed to `true` https://github.com/gogits/gogs/blob/master/conf/app.ini#L90

**Comment by crohr** [comment] 2015-11-10 18:49
@Unknwon ok, is there any way to also set it to true in the custom conf file if any?

**Comment by Unknwon** [comment] 2015-11-10 18:50
@crohr just set to `true` in custom file that's all...

**Comment by crohr** [comment] 2015-11-10 18:53
@Unknwon I meant, if you're supporting custom config files, you should probably expect that people will keep the "main" one unchanged (or, in the case of packages, it will get overwritten), so would it be feasible for you to set that flag both in the default app.ini and the custom app.ini if any?

**Comment by Unknwon** [comment] 2015-11-10 18:54
@crohr I'm confused... the default one has been built into Gogs as a Go source file.

**Comment by crohr** [comment] 2015-11-10 19:00
@Unknwon yes the custom config file will overwrite default, but do you make sure to write the `INSTALL_LOCK` flag in the `custom/conf/app.ini` (if that file exists), or do you always write in `conf/app.ini`? If you always write into `conf/app.ini`, then those changes will be overwritten next time the package is updated.

**Comment by Unknwon** [comment] 2015-11-10 19:05
Gogs does not change anything on `custom/conf/app.ini` after installation...

**Comment by crohr** [comment] 2015-11-10 19:12
@Unknwon then where do you write the `INSTALL_LOCK`?

**Comment by Unknwon** [comment] 2015-11-10 19:14
Right after the installation `/install`, it writes to custom config once, and only reads from custom config afterwards. If found it is `false`, then show the install page.

**Comment by crohr** [comment] 2015-11-10 19:23
OK that clears the confusion for me, I wasn't aware that you were always reading from the custom conf file (it wasn't the case before if I remember the early days correctly). So `INSTALL_LOCK` should indeed be set there, and there is no reason why updating the package would overwrite the value.

@Xamaxon can you have a look at your `/etc/gogs/conf/app.ini` file to see what's the value of `INSTALL_LOCK`?

**Comment by Xamaxon** [comment] 2015-11-10 20:12
@crohr in this file the INSTALL_LOCK is set to false,
in /opt/gogs/conf/app.ini and /opt/gogs/custom/conf/app.init its set to false

**Comment by stonerl** [comment] 2015-11-17 21:29
@Xamaxon 
Thel file ```/opt/gogs/custom/conf/app.ini``` should be a symlink to ```/etc/gogs/conf/app.ini```

```bash
root@local:/opt/gogs/custom/conf# ls -la
total 8
drwxr-xr-x 2 gogs gogs 4096 Nov 17 10:56 .
drwxr-xr-x 3 gogs gogs 4096 Oct 28 19:00 ..
lrwxrwxrwx 1 root root   22 Nov 17 10:56 app.ini -> /etc/gogs/conf/app.ini
```

**Comment by mbi** [comment] 2015-11-19 16:55
On my installation (Debian 8 from packager.io) `/opt/gogs/custom/conf/app.ini` is a regular file, not a link to `/etc/gogs/conf/app.ini`. (also, wouldn't the  symlink point `/etc/gogs/custom/conf/app.ini` and not `/etc/gogs/conf/app.ini`? I thought one shouldn't edit `conf/app.in` but `custom/conf/app.ini`, you're suggesting the latter being a symlink of the former)

**Comment by stonerl** [comment] 2015-11-19 17:11
@mbi You must not edit ```/opt/gogs/conf/app.ini```. ```/opt/gogs/custom/conf/app.ini``` is the file you should alter. As far as I understand gogs. It does not read anything from ```/etc/gogs/conf/```it only reads from ```/opt/gogs/conf/app.ini``` and ```/opt/gogs/custom/conf/app.ini```. So if you don't symlink the ```app.ini``` from or to ```/etc/gogs/conf/`` any changes you do in that file won't affect gogs.

**Comment by mbi** [comment] 2015-11-20 08:08
So here is what is going on:

* Before the upgrade: `/opt/gogs/custom/conf/app.ini` is a regular file with the custom configuration
* Right after `apt-get upgrade` the file is a symlink pointing `/etc/gogs/conf/app.ini`:
```    
    root@git2:/opt/gogs/custom/conf# ls -la
    total 8
    drwxr-xr-x 2 gogs gogs 4096 Nov 20 07:47 .
    drwxr-xr-x 4 gogs gogs 4096 Nov 20 07:44 ..
    lrwxrwxrwx 1 root root   22 Nov 20 07:47 app.ini -> /etc/gogs/conf/app.ini
```
```
grep INSTALL_LOCK /etc/gogs/conf/app.ini
INSTALL_LOCK = false
```
* Accessing the website redirects to `/install` because `INSTALL_LOCK = false`
* By submitting the installation form, `/opt/gogs/custom/conf/app.ini` gets written as a regular file again:

```
root@git2:/opt/gogs/custom/conf# ls -la
total 20
drwxr-xr-x 2 gogs gogs 4096 Nov 20 07:50 .
drwxr-xr-x 4 gogs gogs 4096 Nov 20 07:44 ..
-rw-r--r-- 1 gogs gogs 9676 Nov 20 07:50 app.ini
```
`SECRET_KEY` has been regenerated, the rest of the file is unchanged.

So a quickfix would be to `cp /opt/gogs/custom/conf/app.ini /etc/gogs/conf/app.ini` so that at step 2 `INSTALL_LOCK` remains `true`, is this correct?

**Comment by Unknwon** [comment] 2015-12-06 06:56
Any updates here?...

**Comment by mijndert** [comment] 2015-12-06 12:19
The updates to Gogs are very frequent but every time I update it breaks and I have to manually put app.ini back in its place.
A fix would be very, very welcome as this is getting annoying over time.

**Comment by mijndert** [comment] 2015-12-09 09:12
Any updates?

**Comment by Unknwon** [comment] 2015-12-09 09:14
@mijndert I think @crohr is very busy these days...

**Comment by stonerl** [comment] 2015-12-09 09:19
@mbi ```/etc/gogs/conf/app.ini```needs to be overwritten everytime. Thats why you have to store your custom configuration in ```/opt/gogs/custom/conf/app.ini```.

@mijndert what do you mean by putting the file in place? Where do you have the file stored?

**Comment by mijndert** [comment] 2015-12-09 09:23
@stonerl as someone else pointed out earlier, Gogs doesn't seem to use /etc/gogs/conf/app.ini and instead it just uses /opt/gogs/custom/conf/app.ini. During an update with the packager.io packages the file in /opt/gogs/custom/conf/app.ini gets overwritten with the one from /etc/gogs/conf/app.ini, or so it seems.

As a workaround I keep a copy of /opt/gogs/custom/conf/app.ini in my home directory and cp it to /opt/gogs/custom/conf/ after each time I do an apt-get upgrade.

I hope that clears up the issue a bit. :+1:

**Comment by stonerl** [comment] 2015-12-09 09:31
@mijndert I also use the packages from packager.io. And I don't have this problem. Try the following:

```
mv /opt/gogs/custom/conf/app.ini /etc/gogs/conf/

ln -s /etc/gogs/conf/app.ini /opt/gogs/custom/conf/app.ini 
```
And make sure that the owner of ```/etc/gogs/conf/app.ini``` is owned by the ```gogs``` user
```-rw-r----- 1 gogs gogs 9755 Dec  8 14:48 app.ini```

**Comment by mijndert** [comment] 2015-12-09 09:42
@stonerl that worked, but still, the packager.io default install shouldn't require this workaround imo.

**Comment by Unknwon** [comment] 2015-12-09 09:43
Maybe Gogs should also support check a file `INSTALL.LOCK`?

**Comment by stonerl** [comment] 2015-12-09 12:49
I think the problem is that every time the package gets updated it removes the ```/opt/gogs/custom/```-folder, because this folder is not part of the deb-package. When symlinked apt-does not remove the folder.

So maybe Gogs could also look in ```/etc/gogs/conf/``` for custom configurations and if it finds one there it should use this one. Also it should then prioritize ```/etc/gogs/conf/```over /opt/gogs/custom/conf/```?.

Or gogs should use ```/etc/gogs/conf/```in general for the custom config`

**Comment by Unknwon** [comment] 2015-12-09 13:06
Where to look for custom config is determined by env var or command line flag.

**Comment by stonerl** [comment] 2015-12-09 13:15
@Unknwon how is this env var called?

**Comment by Unknwon** [comment] 2015-12-09 13:16
GOGS_CUSTOM

**Comment by Unknwon** [comment] 2015-12-10 15:03
This issue is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2143

**Comment by stonerl** [comment] 2015-12-10 23:07
I can confirm that this is fixed.

**Comment by Unknwon** [comment] 2015-12-12 02:29
Close as fixed.

**Closed by Unknwon** 2015-12-12 02:29 UTC
Labels: deployment, feedback needed, third-party
