### ISSUE TITLE
Firefox 49.0.2 cann't open gogs.io

### ISSUE THREAD

**Issue by AndreWin** [gogits/gogs#3820] opened 2016-10-27 16:53 UTC
Firefox 49.0.2 cannot open site gogs.io on Windows 8.1. 

Error message:
Wrong sertificate sign in OCSP answer. Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT
(I translated this message from Russian).

I opened this site in Google Chrome.

**Comment by ChangePlaces** [comment] 2016-10-27 17:33
Can confirm in FF 49.0.2. Native English error message is: 

`Secure Connection Failed

An error occurred during a connection to gogs.io. Invalid OCSP signing certificate in OCSP response. Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the web site owners to inform them of this problem.`

**Comment by bkcsoft** [comment] 2016-10-27 18:57
Duplicate of #3793

**Closed by bkcsoft** 2016-10-27 18:57 UTC
