### ISSUE TITLE
Emoji in old commits

### ISSUE THREAD

**Issue by exmex** [gogits/gogs#2390] opened 2016-01-12 17:03 UTC
So we recently switched from gitbucket to gogs because gitbucket was using far too much resources.

After the "migration", (changed all origin urls to the new gogs system and pushing it). I noticed that emojis don't work for older commits. This commit is not the newest one (The newest is 3 commits newer)
![](http://i.imgur.com/KBI3vFH.png)

Same emoji in an issue comment:
![](http://i.imgur.com/6brphqZ.png)

**Comment by bkcsoft** [comment] 2016-01-14 04:44
does it work on any commit? or just not on older ones?

**Comment by Unknwon** [comment] 2016-01-14 08:25
What is your version of Gogs?

**Comment by exmex** [comment] 2016-01-14 10:30
Newest self-compiled source ;).
--------
We didn't tested it yet with newer commits. But the old ones are definitely not working.

**Comment by Unknwon** [comment] 2016-01-14 10:35
OK, reproduced here: https://try.gogs.io/unknwon/issue-2390

**Comment by Unknwon** [comment] 2016-01-14 10:36
I think it is caused by bug https://github.com/Ranks/emojify.js/issues/154

**Comment by exmex** [comment] 2016-01-14 10:38
=). That sucks. But at least we know now where it comes from..

**Comment by Unknwon** [comment] 2016-01-14 10:49
I'm thinking handle this directly in Go...

**Comment by exmex** [comment] 2016-01-14 10:50
The emoji conversion? I thought you'd already do this. But after I looked I noticed you're not. It would certainly be better to convert it directly and just send the emoji url to the page.

**Comment by Unknwon** [comment] 2016-01-14 10:52
> convert it directly and just send the emoji url to the page.

Yes, agree.

**Comment by exmex** [comment] 2016-01-14 10:58
So If a couple guys from us are implementing it, where do you think should we put it? As 3rd party library (I'm not a fan of this idea.), in the template.go file, or as a seperate module in the modules folder?

**Comment by Unknwon** [comment] 2016-01-14 11:07
Actually, I'm going to implement as 3rd party library because somewhere else is using empjify.js and met the same problem...

**Comment by bkcsoft** [comment] 2016-01-14 11:36
I'd have a look at this: https://github.com/shurcooL/github_flavored_markdown/issues/1 :smile:

**Comment by Unknwon** [comment] 2016-01-14 11:41
It's not just markdown, but everywhere... needs something more general. I've already got some idea.

**Comment by exmex** [comment] 2016-01-22 08:40
Sooo. I tinkered with it and the result was.... The emojify.js is either old or broken. The current from the website works!

http://hassankhan.me/emojify.js/javascripts/emojify.min.js

![](http://i.imgur.com/eSTqxpS.png)

**Comment by Unknwon** [comment] 2016-03-03 15:24
Somehow, https://github.com/gogits/gogs/pull/2738 solved this.

**Comment by Unknwon** [comment] 2016-03-04 04:39
Should be fixed by #2738 : https://try.gogs.io/unknwon/issue-2390

**Comment by Unknwon** [comment] 2016-03-06 18:32
Close as fixed.

**Closed by Unknwon** 2016-03-06 18:32 UTC
Labels: kind/bug, kind/third-party, kind/ui, status/needs feedback
