### ISSUE TITLE
16.04 binary install problem

### ISSUE THREAD

**Issue by Andrew415** [gogits/gogs#4621] opened 2017-07-12 14:18 UTC
- Gogs version (or commit ref): 0.11.19-1498611033.13cca8a.xenial
- Git version: latest
- Operating system: xenial
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

The package from the install guide at https://packager.io/gh/pkgr/gogs/install?bid=667#ubuntu-16-04-gogs produces the following error when installing on a latest version xenial. This is being run as root and with no unusual setups like nfs mounted home directories.

Setting up gogs (0.11.19-1498611033.13cca8a.xenial) ...
chown: invalid user: 'gogs.gogs'
dpkg: error processing package gogs (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 gogs
...

**Comment by Andrew415** [comment] 2017-07-12 14:47
I can verify the install from source works fine.

**Comment by Andrew415** [comment] 2017-07-12 16:10
I was able to fix this manually with:

addgroup gogs
usermod -a -G gogs gogs

**Comment by vivace-io** [comment] 2017-07-19 23:25
@Andrew415 if the problem is solved, could you close the issue? Looks to be an error in the guide, not Gogs itself.

**Closed** 2017-07-28 10:35 UTC
