### ISSUE TITLE
GOGS performance -- struggles to handle the Linux kernel repo (?)

### ISSUE THREAD

**Issue by IJeffray** [gogits/gogs#3818] opened 2016-10-27 09:41 UTC
- Gogs version (or commit ref): 0.9.99.0903
- Git version: 2.1.4
- Operating system: Debian 8.5 "Jessie" 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
  I have not tried to replicate this at try.gogs.io as I assume you would prefer me not to shove a whole kernel in there and place significant load on your test server.

But if I import a Linux kernel to my own private GOGS server, GOGS keeps producing these log messages:

> Fail to health check repository (/home/gogs/gogs-repositories/project/linux_kernel.git): execution is timeout [duration: 1m0s]

My server is an 8 core 3.6GHz Xeon E3-1270 with 32GB DDR4 RAM.... reasonably powerful.

**Comment by 0xbaadf00d** [comment] 2016-10-27 09:56
On a OVH virtual server (1 CPU 4 Go Ram) i succeed to clone Github Torval Kernel repos (700K commit) in 10 - 15 minutes, I can browse repos but each page take ~ 1-2 second except /commits who take 15 seconds (because gog run _git rev-list_ in background)

**Comment by strk** [comment] 2016-10-27 09:59
Duplicate of #3784 ?

**Comment by IJeffray** [comment] 2016-10-27 10:19
Not convinced it's a dup.  Browsing is pretty good for me, actually... 4-6 seconds per page -- it's just the log messages that I'm getting that are concerning.   I'm guessing this is when it's generating the dashboard summaries (which don't work at all for kernels).

**Comment by 0xbaadf00d** [comment] 2016-10-30 07:49
I have submitted a pull request on _git-module_ project (relative to issue opened by @tgulacsi). Fix reduce pages load time by 50% on my cheap OVH cloud virtual server.

@IJeffray: could you try to recompile GOGS with the patch on applied on _git-module_ to test is you have better performance too ?

**Comment by strk** [comment] 2016-10-30 09:50
Could you please drop here a link to your git-module PR ?

**Comment by 0xbaadf00d** [comment] 2016-10-30 09:53
Of course: https://github.com/gogits/git-module/pull/24

**Comment by 0xbaadf00d** [comment] 2016-10-30 11:28
_/commits_ page could be speed up by stopping to dump whole git repository commits and using `--max-count` and `--skip` argument to the command ` git rev-list`

**Comment by IJeffray** [comment] 2016-10-31 09:22
I installed GOGS using the Debian package, not from source, so I'll have to do some work to set up a secondary installation to test this (GOGS is already running as our company's primary Git service!)   I'm amazed to see the Sleep in there though.

**Comment by Unknwon** [comment] 2017-01-31 18:23
Merge this thread to https://github.com/gogits/gogs/issues/3830 as it indicates the problem better.

**Closed by Unknwon** 2017-01-31 18:23 UTC
