### ISSUE TITLE
Fail to initialize ORM engine

### ISSUE THREAD

**Issue by focmb** [gogits/gogs#2261] opened 2015-12-21 15:52 UTC
I did an update from gogs 8.10 to 8.13. After copying my custom and data folder in to the gogs folder I got an error message:

    [...s/routers/install.go:70 GlobalInit()] [E] Fail to initialize ORM engine: sync database struct error: Cannot add a NOT NULL column with default value NULL

I am using gogs with sqlite

**Comment by jbub** [comment] 2015-12-21 19:07
There is 8.13 version available ?

**Comment by focmb** [comment] 2015-12-21 23:26
0.8.13. Sorry, my fault

**Comment by acrade** [comment] 2015-12-22 02:53
@angus-g Thanks，the problem is solved:grinning:

**Comment by focmb** [comment] 2015-12-23 10:10
Fine. The solution of angus-g works. Thanks a lot

**Comment by Unknwon** [comment] 2015-12-24 15:14
This issue is claimed to be fixed by merging #2262

**Closed** 2016-01-01 03:16 UTC
Labels: bug, feedback needed
