### ISSUE TITLE
[Feature] Allow issue and comments creation via email

### ISSUE THREAD

**Issue by rogeriolino** [gogits/gogs#3736] opened 2016-10-05 21:06 UTC
Hi all,

Feature suggestion for issue email integration like in [Github](https://github.com/blog/811-reply-to-comments-from-email), [Redmine](http://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails) and [Mantis Email Reporting Plugins](https://www.mantisbt.org/wiki/doku.php/mantisbt:emailreporting).

Regards.

**Comment by bkcsoft** [comment] 2016-10-06 08:13
Duplicate of #1272

**Closed by bkcsoft** 2016-10-06 08:13 UTC

**Comment by rogeriolino** [comment] 2016-10-06 11:47
Sorry, I've searched about this feature and I've not found.
