### ISSUE TITLE
Creating repository with organization as owner does not set access to teams

### ISSUE THREAD

**Issue by chrberger** [gogits/gogs#1834] opened 2015-10-24 10:56 UTC
Gogs version: 0.6.16.1022 Beta
Git version: 1.9.1
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

When I create a repository with an organization as owner, the teams associated with this organization do not have access to the newly created repository. The same happens if I create the repository as user and transfer the ownership to the organization.

This feature was working when I set up our Gogs server beginning of August 2015 but not any longer with the aforementioned version (I don't have the old version at hand; I installed Gogs on my Ubuntu using the following package source "deb https://deb.packager.io/gh/pkgr/gogs trusty pkgr"; thereby, I also get the automated updates via apt).

After inspecting the MySQL table "access", I noticed that for the existing repositories the relation user-id <-> repository-id is set correctly but for new repositories, only the creating user is added to table "access" and not the other users.

Any suggestions and hints are appreciated as I cannot set up new repositories any longer.

**Comment by Unknwon** [comment] 2015-10-24 15:40
Thanks your feedback!

By design, only the `Owners` team get access when create a new repository, if need to add this repository to other teams manually. 

Similar issue maybe: https://github.com/gogits/gogs/issues/568

**Comment by chrberger** [comment] 2015-10-24 18:59
Thanks for the immediate feedback.

I tested your suggestions that of course worked - thanks.

This additional step was somewhat unintuitive as the teams are already part of the organization having the desired permissions set - why is this manual adding of newly created repositories that belong to an organization required?

**Comment by Unknwon** [comment] 2015-10-24 19:02
> why is this manual adding of newly created repositories that belong to an organization required?

By design, you can create a private repository that is only visible to certain teams (of course implementation may have bug).

An improvement is discussed in #568 that allows you to include/exclude teams at the same time you create a repository, so process can be a lot eaiser.

**Comment by Unknwon** [comment] 2015-10-24 19:10
All discussion goes to #568 to keep in one place. So I'm going to close this thread. :smiling_imp:

**Closed by Unknwon** 2015-10-24 19:10 UTC
Labels: feedback needed
