### ISSUE TITLE
gogs.io不能访问

### ISSUE THREAD

**Issue by limengwei** [gogits/gogs#3839] opened 2016-11-01 05:38 UTC

**Comment by GinoHereIam** [comment] 2016-11-01 13:05
What issue should this be?

**Comment by limianwang** [comment] 2016-11-01 15:48
@GinoHereIam I think you got the wrong person. I believe @limengwei implied that gogs.io can not be accessed.

**Comment by bkcsoft** [comment] 2016-11-01 18:35
Duplicate of #3793

**Closed by bkcsoft** 2016-11-01 18:35 UTC
