### ISSUE TITLE
https://gogs.io certificate issue

### ISSUE THREAD

**Issue by furai** [gogits/gogs#3836] opened 2016-10-31 20:20 UTC
Hey,

Does anyone else is experiencing issues with gogs.io website? It seems that there's something wrong with certificate.

Cheers,
Furai

**Comment by skrzepto** [comment] 2016-10-31 20:32
Duplicate of #3793

**Comment by bkcsoft** [comment] 2016-11-01 18:35
Duplicate

**Closed by bkcsoft** 2016-11-01 18:35 UTC

**Comment by furai** [comment] 2016-11-01 19:25
Sorry, haven't found other issue on github and I did search before posting this one. My bad.
