### ISSUE TITLE
View all issues assigned to me

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#1820] opened 2015-10-23 10:34 UTC
I have a repo created inside an organization (which I use as namespaces to group projects) and have assigned issues to my own personal user account.

When I go to the dashboard and view them they don't appear, instead showing I have 0 issues assigned to me.

This is different to #1580 I think as they're my own personal issues

**Comment by Unknwon** [comment] 2015-10-23 13:44
By design, I think it is same as #1580 because organization is equal to your personal account even though you're owner of it.

**Comment by stonerl** [comment] 2015-11-21 10:37
The same goes for PR in organization repos. IMHO it should not matter whether you're assigned or not. As soon as your part of an organization, issues and PR should show up on the Dashboard.

**Comment by tkschmidt** [comment] 2015-12-01 09:35
Yes, i think about using gogs more internally. But we need a possibility that people with assigned tasks see them at their issue tab and not by browsing to all repos in our organization and checking by hand :)

**Comment by TilmannBach** [comment] 2016-01-28 13:35
+1

**Comment by TilmannBach** [comment] 2016-03-21 11:06
do we have a chance for this view in v0.10.0?

**Comment by johnnylee** [comment] 2016-03-21 11:55
I'm including this log line from a duplicate issue: 

```
[xorm] [info]  2016/03/21 08:58:48.617567 [sql] SELECT COUNT(*) FROM "issue"  WHERE issue.is_closed=$1 AND issue.repo_id=0 AND issue.is_pull=0 AND assignee_id=$2 [args] [false 1]
```

It looks like the problem is `issue.repo_id=0`.

**Comment by ColtonProvias** [comment] 2016-04-13 03:04
Just checked the code and what @johnnylee pointed out is correct.

On [line 192 of routers/user/home.go](https://github.com/gogits/gogs/blob/master/routers/user/home.go#L192), the repository ID is selected from the query params and receives the value 0.  It is then referenced again on [line 262](https://github.com/gogits/gogs/blob/master/routers/user/home.go#L262) where the query is triggered.  Then looking at [line 511 of models/issue.go](https://github.com/gogits/gogs/blob/master/models/issue.go#L511), we see what has happened.  A `nil` value would give us the result we are looking for.  However, I'm still curious as to why repoID is being assigned 0 when it doesn't exist in the query string.  Chasing this back through macaron, then Unknwon/com, the issue is found to lie within a builtin of the Go Language itself.  On [line 40 of Unknwon/com/convert.go](https://github.com/Unknwon/com/blob/master/convert.go#L40), `ParseInt` is called.  `ParseInt`, when given an empty or invalid value, returns 0, which explains the base of the problem.

Thus to solve this, `repoID` should parse its value from the query string only if it exists within the query string.  Otherwise, if `repoID` was not in the query, it should be set to `nil`.

**Comment by ColtonProvias** [comment] 2016-04-13 03:36
I agree with @tkschmidt, it is a huge problem for us using Gogs internally.  I'd prefer to keep issues organized and together within Gogs, but having my designers check through 20+ repositories by hand causes them to revert to email and text messages which keeps everybody else out of the loop.

When viewing as an organization, it's great to see all of the issues immediately.  But when I view it as a user, I want to know within seconds what work I have to do.

**Comment by de-live-gdev** [comment] 2016-05-13 17:52
If possible it would be great if these informations could also be provided via the **gogs-api**. (The GitHub equivalent would be [**/issues**](https://developer.github.com/v3/issues/#list-issues) for the current logged in user / token holder then)

**Comment by lukeawyatt** [comment] 2016-06-02 17:27
**+1** on this, issue management over multiple organizations will make a huge difference in personal workflow.  In addition, a milestone filter accompanying this would also be beneficial.

**Comment by xp65** [comment] 2016-07-17 20:41
+1 really needed feature

**Comment by hgaiser** [comment] 2016-08-24 21:31
To be honest, I thought it was a bug when I didn't see the issues assigned to me. In my opinion this is really critical and should definitely be added.

**Comment by DblK** [comment] 2016-09-13 12:37
I have several questions/remarks about this one:
1) Is there anybody working on it? If not I will take a try
2) Would it be nice to have "In your organizations" bellow "In your repositories" to separate issues?
3) The "Assigned to you" should include all issue in all repo you are a part of. That what is wanted.
4) Same goes for "Created by you" I guess?

If everything is good I will develop it.
@Unknwon good for you?

**Comment by hgaiser** [comment] 2016-09-13 12:48
@DblK , it should be fixed by https://github.com/gogits/gogs/pull/3560 , waiting for a merge. It does not include the "In your organizations" though, which in my opinion would be a good addition.

**Comment by DblK** [comment] 2016-09-13 13:12
Okay. I will wait for your PR to be merged and create a new issue for the kind/enhancement for adding the "In your organizations" category.

**Comment by ChangePlaces** [comment] 2016-10-16 13:37
what's the current status of this?

**Comment by gsantner** [comment] 2016-11-02 10:28
Seems pretty much finished, but no response from team

**Comment by Unknwon** [comment] 2016-12-27 12:28
This is implemented by https://github.com/gogits/gogs/pull/3560.

**Closed by Unknwon** 2016-12-27 12:28 UTC
Labels: kind/enhancement
