### ISSUE TITLE
python notebook detection

### ISSUE THREAD

**Issue by ziozzang** [gogits/gogs#3788] opened 2016-10-20 08:13 UTC
I wish that gogs has support of python notebook.
detects and parse *.ipynb extension as Ipython notebook :)

* GitHub has this function. and can parse ipynb file.

**Comment by skrzepto** [comment] 2016-10-27 02:31
Potentially a duplicate of issue #3715 ?

**Comment by bkcsoft** [comment] 2016-10-28 01:18
Closed as duplicate

**Closed by bkcsoft** 2016-10-28 01:18 UTC
