### ISSUE TITLE
Access rights

### ISSUE THREAD

**Issue by Sauermann** [gogits/gogs#965] opened 2015-02-17 17:43 UTC
Currently the access control works in a way that everyone can access everything that is available, unless it is restricted.
I would like to see an option implemented to reverse this: Access should be denied by default and only allowed after being granted by the person responsible for the repository.
From a security point of view this is the more sensible way to handle access.

To make this request more precise I want to suggest three solutions:
1.
- During the creation of a new repository make the private-flag by default selected.

2.
- Add for each user a configuration option to select if during the creation of a new repository (owned by himself) the private-flag should be selected.
- Add for each organization a configuration option to select if during the creation of a new repository (owned by this organization) the private-flag should be selected.

3.
- Add for each user a configuration option to select if owned non-private repositories are hidden from others.
- Add for each organization a configuration option to select if owned non-private repositories are hidden from non-members.

Optionally this could be extended:
- Add site-administrator options to select if newly created users or organizations are "in private mode".
- Different access modes for http/https/ssh/Website

**Comment by phsmit** [comment] 2015-02-17 20:25
I do think it makes sense to make private repositories default (option 1.), but do you think this is such a big thing that it should be another configuration option? 

As for 3. why hide repositories that are not private? If they are private you should just add access for those people that you want. Also, do you have any real use case for different access modes for http/ssh/website?

**Comment by Sauermann** [comment] 2015-02-17 22:10
Just wanted to present different options to think about. I am perfectly happy with option 1.
My Idea behind 3 was to have some kind of bulk hiding functionality.

About the different access modes for http/ssh ... the scenario I can think of is to restrict access on a repository-owner-level when an unsecure http connection is used to transmit the repository (but this is not a real use case for me at the moment).

And thanks for the fast response.

**Comment by Unknwon** [comment] 2015-02-18 04:08
@Sauermann , thanks for your feedback!

I think option 1 would be the best, but just wonder what's the matter with one single click when the user create a new repository to make it private?

**Comment by Sauermann** [comment] 2015-02-18 12:16
According to [some](http://notes.gross.is/post/22958656041/the-144-146-165-button) [surveys](http://www.uie.com/brainsparks/2011/09/14/do-users-change-their-settings/) a large percentage of people don't change preselected settings.
Implementation of option 1 will reduce the chance that users of gogs accidentially grant public access to repositories that they wanted to keep private.

**Comment by Tomasen** [comment] 2015-02-28 12:12
+1

**Comment by de-live-gdev** [comment] 2015-08-17 09:52
Remembering if a new repo should be private could also be an option.
So if your last created repo was a private, private should be ticked

**Comment by Unknwon** [comment] 2015-08-17 09:54
> So if your last created repo was a private, private should be ticked

Thanks @de-live-gdev good suggestion!

**Comment by Unknwon** [comment] 2015-08-28 10:47
OK, hi all!

Right now on `develop` branch, Gogs remembers your visibility choice of your last created repository, and auto-check/uncheck private attribute for you when you create another repository.

You can test on: https://try.gogs.io/repo/create

**Comment by mhoram-kerbin** [comment] 2015-08-28 11:23
Sounds great. Tested it on try.gogs.io and remembering the status seems to work.
However accessing my newly created repositories results in a 500 error page.
https://try.gogs.io/mark/test1
https://try.gogs.io/mark/test4

I can however still access public repositories that were created by others - no matter if I am logged in or logged out.

**Comment by Unknwon** [comment] 2015-08-28 11:39
@mhoram-kerbin Oops, good catch!

It is caused by my mistake on handling bare repository, which has been fixed now!

**Comment by de-live-gdev** [comment] 2015-08-29 11:10
@Unknwon Thanks for your work, tried it on and found no problems. Maybe the switch could say "Public Repository" when its off? Don't know whats better by design/usability, but thats a personal opinion

**Comment by Unknwon** [comment] 2015-08-29 15:53
@de-live-gdev yes, that was kind of confusing, so I changed back to use checkbox again :) https://try.gogs.io/repo/create

**Closed by Unknwon** 2015-08-29 15:53 UTC
Labels: enhancement, feedback needed

**Comment by Sauermann** [comment] 2015-08-29 19:51
Thanks for implementing this. And the idea of using the status of the previous creation is very good, did not cross my mind.

**Comment by Unknwon** [comment] 2015-08-30 13:00
@Sauermann thanks your confirmation!
