### ISSUE TITLE
Use ctrl+c when clone through SSH makes Gogs docker exit unexpectedly

### ISSUE THREAD

**Issue by masiqi** [gogits/gogs#1499] opened 2015-08-18 04:41 UTC
client:
 git clone ssh://git@git.xxx.xxxx:10022/xxxx/abcd.git
Cloning into 'abcd'...
remote: Counting objects: 12138, done.
remote: Compressing objects: 100% (5245/5245), done.
^CKilled by signal 2.3% (365/12138)   
fatal: index-pack failed
fatal: The remote end hung up unexpectedly

docker gogs:
root@iZ23j3nxjzkZ:/data1/gogs/gogs# docker run  -p 192.168.42.1:3000:3000 -p 10022:22 -v /data1/gogs:/data gogs/gogs
Starting OpenBSD Secure Shell server: sshdCould not load host key: /data/ssh/ssh_host_ed25519_key
.
sending incremental file list

sent 2750 bytes  received 40 bytes  5580.00 bytes/sec
total size is 353972  speedup is 126.87
2015/08/18 04:38:16 [T] Custom path: /data/gogs
2015/08/18 04:38:16 [T] Log path: /gopath/src/github.com/gogits/gogs/log
2015/08/18 04:38:16 [I] Gogs: Go Git Service 0.6.5.0817 Beta
2015/08/18 04:38:16 [I] Log Mode: File(Info)
2015/08/18 04:38:16 [I] Redis Supported
2015/08/18 04:38:16 [I] Memcache Supported
2015/08/18 04:38:16 [I] Cache Service Enabled
2015/08/18 04:38:16 [I] Session Service Enabled
2015/08/18 04:38:16 [I] Mail Service Enabled

2015/08/18 04:38:17 [I] SQLite3 Supported
2015/08/18 04:38:17 [I] Run Mode: Production
2015/08/18 04:38:18 [I] Listen: http://0.0.0.0:3000

root@iZ23j3nxjzkZ:/data1/gogs/gogs# 

类似这样，自己就退出了。。我怎么才能知道是什么问题？怎样才能避免？谢谢

**Comment by masiqi** [comment] 2015-08-18 04:43
补充一下，直接docker pull gogs/gogs的

**Comment by Unknwon** [comment] 2015-08-18 05:32
Thanks your feedback!

Check `/gopath/src/github.com/gogits/gogs/log/gogs.log` see if any error presents there.

**Comment by masiqi** [comment] 2015-08-18 05:46
没有什么信息。。。
root@iZ23j3nxjzkZ:/tmp/ttt# tail -f gogs.log 
2015/08/18 05:43:21 [I] Log Mode: File(Info)
2015/08/18 05:43:21 [I] Redis Supported
2015/08/18 05:43:21 [I] Memcache Supported
2015/08/18 05:43:21 [I] Cache Service Enabled
2015/08/18 05:43:21 [I] Session Service Enabled
2015/08/18 05:43:21 [I] Mail Service Enabled
2015/08/18 05:43:22 [I] SQLite3 Supported
2015/08/18 05:43:22 [I] Run Mode: Production
2015/08/18 05:43:22 [I] Listen: http://0.0.0.0:3000




2015/08/18 05:44:50 [I] Log Mode: File(Info)
2015/08/18 05:44:50 [I] Redis Supported
2015/08/18 05:44:50 [I] Memcache Supported
2015/08/18 05:44:50 [I] Cache Service Enabled
2015/08/18 05:44:50 [I] Session Service Enabled
2015/08/18 05:44:50 [I] Mail Service Enabled
2015/08/18 05:44:51 [I] SQLite3 Supported
2015/08/18 05:44:51 [I] Run Mode: Production
2015/08/18 05:44:51 [I] Listen: http://0.0.0.0:3000

**Comment by masiqi** [comment] 2015-08-18 05:47
cat serv.log 
2015/08/18 05:44:39 [...ts/gogs/cmd/serve.go:199 runServ()] [F] Failed to execute git command: signal: broken pipe
2015/08/18 05:45:26 [...ts/gogs/cmd/serve.go:199 runServ()] [F] Failed to execute git command: signal: broken pipe

**Comment by Unknwon** [comment] 2015-08-18 06:06
Thanks for following up!

> cat serv.log 
2015/08/18 05:44:39 [...ts/gogs/cmd/serve.go:199 runServ()] [F] Failed to execute git command: signal: broken pipe
2015/08/18 05:45:26 [...ts/gogs/cmd/serve.go:199 runServ()] [F] Failed to execute git command: signal: broken pipe

This is expected. 

So, would you mind to perform the same operation(clone and ctrl+c), see if you can reproduces the same situation?

**Comment by masiqi** [comment] 2015-08-18 06:09
可重现，但是没有其他细节了，我用阿里云，docker，打算用gogs做版本控制服务

**Comment by masiqi** [comment] 2015-08-18 06:16
Gogs · 当前版本: 0.6.5.0817 Beta
gogs app.ini
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE = mysql
HOST = xxx:3306
NAME = xxxx
USER = xxx
PASSWD = xxx
SSL_MODE = disable
PATH = data/gogs.db

[repository]
ROOT = /home/git/gogs-repositories

[server]
DOMAIN = git.xxx
HTTP_PORT = 3000
ROOT_URL = http://git.xxxx/
SSH_PORT = 10022
ENABLE_GZIP = false

[session]
PROVIDER = file

[log]
MODE = file
LEVEL = Info

[security]
INSTALL_LOCK = true
SECRET_KEY = aaaaaaaa

[mailer]
ENABLED = true
HOST = smtp.xxxxx.xxxx
FROM = maillist@xxxxx.com
USER = maillist@xxxx.com
PASSWD = aaaaaa

[picture]
SERVICE = server
AVATAR_UPLOAD_PATH = data/avatars
GRAVATAR_SOURCE = duoshuo

**Comment by Unknwon** [comment] 2015-08-18 10:39
Thanks your info!

I cannot produce this without Docker, let me check it Docker again.

BTW, use Docker to run Gogs is just an option, but use binary to setup is a lot faster. http://gogs.io/docs/installation/install_from_binary.html

Just download zip and unzip to somewhere, you are basically all set.

**Comment by Unknwon** [comment] 2015-08-18 12:20
Hi there, I've successfully reproduce it on Docker. 

My first guess would be that command line somehow pass the `crtl+c` signal to Docker and shuts down the Gogs.

Doing more researching....

**Comment by Unknwon** [comment] 2015-08-18 13:13
OK... I found solution!

**Comment by Unknwon** [comment] 2015-08-18 13:14
Updating Docker README.

**Comment by Unknwon** [comment] 2015-08-18 13:28
Never mind... Still having trouble with ctrl+c signal... :joy:

**Comment by orzFly** [comment] 2015-08-27 06:31
https://jpetazzo.github.io/2014/06/23/docker-ssh-considered-evil/

Add a proper process manager can solve this problem. No time to propose a Pull Request but I can run Gogs successfully with the following code snippets. This may not be the best (minimal) way but I would just be satisfied because I really like supervisor :).

Append to `Dockerfile`:
```
apt-get install supervisor
```

Append to `docker/start.sh`:
```
>supervisord.conf cat <<EOF
[supervisord]
logfile=/var/log/app/supervisor.log
loglevel=info
nodaemon=true

[program:web]
command=$(pwd)/gogs web
process_name:%(program_name)s
numprocs=1
user=git
autostart=true
autorestart=true
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/data/gogs/log/s_%(program_name)s.%(process_num)02d.log
environment=HOME="/home/git",USER=git

[program:sshd]
command=/usr/sbin/sshd -D -e
process_name:%(program_name)s
numprocs=1
autostart=true
autorestart=true
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/data/gogs/log/s_%(program_name)s.%(process_num)02d.log
EOF

exec supervisord -c supervisord.conf --nodaemon
```

**Comment by Unknwon** [comment] 2015-08-27 11:59
@orzFly thanks your tip!

**Comment by Unknwon** [comment] 2015-10-02 19:44
Hi @masiqi , can you try `develop` tag of Docker image again? I just merged a PR which claims fixed this problem!

**Comment by masiqi** [comment] 2015-10-03 08:36
ok,thanks

**Comment by icewheel** [comment] 2015-10-04 10:18
just if this issue does not get resolved. This image works good for SSH, used it for few months never had problem with SSH. https://hub.docker.com/r/codeskyblue/docker-gogs/~/dockerfile/

FROM google/golang MAINTAINER codeskyblue@gmail.com RUN echo "deb http://ftp.debian.org/debian/ wheezy-backports main" >> /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y -t wheezy-backports openssh-server
# grab but do not build gogs RUN git clone https://github.com/gogits/gogs.git /gopath/src/github.com/gogits/gogs
# set the working directory and add current stuff WORKDIR /gopath/src/github.com/gogits/gogs
RUN git checkout master
RUN go get -v -tags "sqlite redis memecache"
RUN go build -tags "sqlite redis memecache"
RUN useradd --shell /bin/bash --system --comment gogits git
RUN mkdir /var/run/sshd
# SSH login fix. Otherwise user is kicked off after login RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
RUN sed 's@UsePrivilegeSeparation yes@UsePrivilegeSeparation no@' -i /etc/ssh/sshd_config
RUN echo "export VISIBLE=now" >> /etc/profile
RUN echo "PermitUserEnvironment yes" >> /etc/ssh/sshd_config
# create new server keys on startup RUN sed 's@^HostKey@\#HostKey@' -i /etc/ssh/sshd_config
RUN echo "HostKey /data/ssh/ssh_host_key" >> /etc/ssh/sshd_config
RUN echo "HostKey /data/ssh/ssh_host_rsa_key" >> /etc/ssh/sshd_config
RUN echo "HostKey /data/ssh/ssh_host_dsa_key" >> /etc/ssh/sshd_config
RUN echo "HostKey /data/ssh/ssh_host_ecdsa_key" >> /etc/ssh/sshd_config
RUN echo "HostKey /data/ssh/ssh_host_ed25519_key" >> /etc/ssh/sshd_config
# prepare data ENV GOGS_CUSTOM /data/gogs RUN echo "export GOGS_CUSTOM=/data/gogs" >> /etc/profile
RUN apt-get install -y rsync
ADD . /gopath/src/github.com/gogits/gogs
EXPOSE 22 3000 ENTRYPOINT [] CMD ["./start.sh"]

**Comment by Unknwon** [comment] 2015-10-04 18:08
@icewheel  FYI, the Dockerfile caused this issue was written by the same person @codeskyblue .

**Comment by icewheel** [comment] 2015-10-05 07:47
SSH is working good now. No container crash. Thanks

**Comment by icewheel** [comment] 2015-10-05 08:04
Feedback: 
SSH is working good now. No container crash. Thanks

But its a little slow. It waits at the last line for some seconds. Following is the output. The line "Checking connectivity... done." took more than 22 seconds to print from a local server while cloning or pushing. Cloning the same project from github takes 2-4 seconds.

ice-PC:~/tests$ date
Mon Oct  5 03:41:26 EDT 2015
ice-PC:~/tests$ git clone ssh://git@www.sulekha.rocks:10023/test/testproject.gitCloning into 'testproject'...
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 15 (delta 3), reused 0 (delta 0)
Receiving objects: 100% (15/15), 12.54 KiB | 0 bytes/s, done.
Resolving deltas: 100% (3/3), done.
Checking connectivity... done.           //[Takes more than 22 seconds to print this line, github takes only3 secinds to commit.]
ice-PC:~/tests$ date
Mon Oct  5 03:41:59 EDT 2015

**Comment by tboerger** [comment] 2015-10-05 08:49
@icewheel are you seriously comparing a tiny local pc with github? What do you think happens on the serverside?

**Comment by icewheel** [comment] 2015-10-05 08:50
@tboerger you can compare SSH and HTTPS. SSH is supposed to be faster. Push over HTTPS to local server is faster than github.

**Comment by tboerger** [comment] 2015-10-05 08:52
@icewheel than you should check your git or ssh server. The place where it hangs for ypu has nothing to do with gogs, it's pure SSH and Git, nothing else.

**Comment by icewheel** [comment] 2015-10-05 08:55
@tboerger Don't know its the complete Gogs Docker image, everything ssh and gogs is contained in docker image. I have not modified it.

**Comment by icewheel** [comment] 2015-10-05 11:11
@Unknwon  @codeskyblue gogs docker image with tag `latest` `(Gogs · Version: 0.6.1.0325 Beta)` does not show crash symptoms or wait 30 seconds before closing ssh session. 

The @codeskyblue image with `tag v0.5.5` makes the container crash after a ssh push.

Git Push over SSH took 1 second.
```
$ date ; git push origin master ; date
Mon Oct  5 06:57:40 EDT 2015
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 293 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
To ssh://git@www.xxxxx.rocks:10024/test/testproject.git
   fd21d5a..4cb22ca  master -> master
Mon Oct  5 06:57:41 EDT 2015
```

git clone over SSH took 1 second.
```
Mon Oct  5 07:00:26 EDT 2015
Cloning into 'testproject'...
remote: Counting objects: 38, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 38 (delta 11), reused 0 (delta 0)
Receiving objects: 100% (38/38), 14.27 KiB | 0 bytes/s, done.
Resolving deltas: 100% (11/11), done.
Checking connectivity... done.
Mon Oct  5 07:00:27 EDT 2015
```
Container settings: 
```
{
   "cap_add" : [],
   "cap_drop" : [],
   "cmd" : "",
   "cpu_priority" : 0,
   "enable_publish_all_ports" : false,
   "enabled" : true,
   "env_variables" : [],
   "exporting" : false,
   "id" : "95cb43fdd10456d2da7e5f8ebc2687a92bec2c75c7958d2b5d5ac8d5b0062748",
   "image" : "codeskyblue/docker-gogs:latest",
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "gogsCodeSky",
   "pin" : false,
   "port_bindings" : [
      {
         "container_port" : 10445,
         "host_port" : 10445,
         "type" : "tcp"
      },
      {
         "container_port" : 22,
         "host_port" : 10024,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false
   },
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/gogs/develop/codeSkyBlue",
         "mount_point" : "/data/",
         "type" : "rw"
      }
   ]
}
```

**Comment by Unknwon** [comment] 2015-10-05 13:32
@icewheel thanks for the detail!

The `30 seconds` thing looks like https://github.com/gogits/gogs/issues/1698

**Comment by icewheel** [comment] 2015-10-05 13:50
@Unknwon The delay might be happening because of Ciphers or Encryption use by SSH. Otherwise, its not a bug. SSH is working fine.

**Comment by Unknwon** [comment] 2015-10-05 13:53
> The delay might be happening because of Ciphers or Encryption use by SSH

It could be and I'm really not sure about it...

**Comment by codeskyblue** [comment] 2015-10-07 22:43
The Dockerfile has changed a lot since I last pr. This might be the ssh config or the sshd version, I guess.

**Comment by Unknwon** [comment] 2015-10-24 20:20
Close for now but open for continuing discussion.

**Closed by Unknwon** 2015-10-24 20:20 UTC
Labels: bug, deployment, feedback needed
