### ISSUE TITLE
raw link 'broken' when filename contains spaces

### ISSUE THREAD

**Issue by sluedecke** [gogits/gogs#2842] opened 2016-03-16 15:55 UTC
- Gogs version (or commit ref): 0.9.0.0306
- Git version: any
- Operating system: Server -> Archlinux, Debian // Client -> Archlinux, Windows
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [X] Yes  -> https://try.gogs.io/scnet/linkTest
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When adding a binary file with a name containing spaces, the RAW link generates a wrong filename, e.g. EMPTY.zip for "EMPTY with spaces.pptx"

Also the mimetype appears to be zip for office files.

https://try.gogs.io/scnet/linkTest

**Comment by Unknwon** [comment] 2016-03-16 20:05
Hi, I can't reproduce on Chrome.

**Comment by sluedecke** [comment] 2016-03-16 20:55
I'm using Firefox, maybe it's a problem of this browser. 

On March 16, 2016 9:06:20 PM GMT+01:00, "无闻" <notifications@github.com> wrote:
>Hi, I can't reproduce on Chrome.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gogits/gogs/issues/2842#issuecomment-197523026

-- 
Sascha Lüdecke
+49 179 9210765

**Comment by Unknwon** [comment] 2016-03-16 20:57
Thanks, I'll take a look.

**Comment by sluedecke** [comment] 2016-03-17 08:20
I tested with other browsers, all are working: MSIE 11, Safari, rekonq and the Android Marshmellow built-in browser.  Only firefox fails on the filename

**Comment by neolit123** [comment] 2016-03-17 11:08
firefox exhibits semi-broken behavior in my option.
if you copy-paste a URL with spaces from the address bar it is escaped with %20, but if you click a link with spaces it's not escaped. what chrome and other browsers do is that when a link is clicked it becomes escaped. chrome also always escapes a URL once you navigate to it.

it's probably a safe bet to pre-escape **all** generated URLs just in case, with something like this:
http://stackoverflow.com/a/28407928
2c

**Comment by Unknwon** [comment] 2016-03-25 21:11
This is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2883, you can test on demo site.

**Comment by neolit123** [comment] 2016-03-26 00:33
the issue in original user report is not fixed:
> When adding a binary file with a name containing spaces, the RAW link generates a wrong filename, e.g. EMPTY.zip for "EMPTY with spaces.pptx"
Also the mimetype appears to be zip for office files.

because it looks to be a Firefox issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=221028
the bugreport talks about "Content disposition" and "quoting" the filename, no idea what that's all about.

a Bitbucket developer says that they have a fix:
https://jira.atlassian.com/browse/BSERV-4985

so not a Gogs bug, but possibly Gogs can be adapted to work around this Firefox issue.

**Comment by Unknwon** [comment] 2016-03-26 00:35
I tested with Firefox developer edition and works, which version are you in?

**Comment by neolit123** [comment] 2016-03-26 00:36
Windows 7, with a slightly older Firefox - 43.0.

More info about the "Content disposition" part:
http://kb.mozillazine.org/Filenames_with_spaces_are_truncated_upon_download

**Comment by Unknwon** [comment] 2016-03-26 00:37
So sad...

**Comment by neolit123** [comment] 2016-03-26 00:41
> I tested with Firefox developer edition and works, which version are you in?

just updated to 45.0 and the issue is still present, at least on Windows.

**Comment by Unknwon** [comment] 2016-03-26 01:18
So what to do next then?

**Comment by neolit123** [comment] 2016-03-26 01:54
the "quotes" solution proposed here supposedly works:
http://kb.mozillazine.org/Filenames_with_spaces_are_truncated_upon_download

**Comment by Unknwon** [comment] 2016-03-26 02:12
@neolit123 please test the demo link again.

**Comment by moltam** [comment] 2016-03-26 06:41
File name is now correct with demo link (Ubuntu 15.10, Firefox 45.0).

**Comment by neolit123** [comment] 2016-03-26 18:08
works properly for Firefox 45.0 (Windows 7); nicely done.

**Comment by sluedecke** [comment] 2016-04-01 11:22
Works with firefox 45.0.1 on Linux (arch) -> no longer an issue

**Closed** 2016-04-04 07:22 UTC
Labels: kind/bug, kind/third-party, kind/ui
