### ISSUE TITLE
Issues comment wrong link to non existent "commit"

### ISSUE THREAD

**Issue by yjrerffefr** [gogits/gogs#3538] opened 2016-08-30 06:57 UTC
- Gogs version (or commit ref): try.gogs.io
- Git version: try.gogs.io
- Operating system: try.gogs.io
- Database (use `[x]`): try.gogs.io
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes   https://try.gogs.io/mmmmm/retfdsdf/issues/1
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Comments text is erroneously linked to a non existent commit.

**Comment by Unknwon** [comment] 2016-08-30 06:59
Note: we should modify regexp to check not match the case that all chars are same.

**Comment by DblK** [comment] 2016-08-31 11:25
After dig in the issue, the problem is more severe than I thought.
Inside "modules/markdown/markdown.go", it transform any string in link based on regexp without checking if the computed link is a valid one or not that lend to error 500.

For example, if you type any string with at least 7 characters and with only letter from a to f and/or number it will be transformed in commit link as if it was SHA number.

I would suggest to add a validator to check every link, including issue, commit, etc.. so every link candidate should be checked (according to the current repository).
That way, the FIXME (on line#94) about the regexep of SHA that convert the number only don't have to be fixed because even if the number will be transformed as link it will fail the validation and not be transformed at the end.

I'm new to Golang but I can try to fix this if @Unknwon still think it's a kind/bug.

**Comment by Unknwon** [comment] 2016-08-31 11:27
>I would suggest to add a validator to check every link, including issue, commit, etc.. so every link candidate should be checked (according to the current repository).
That way, the FIXME (on line#94) about the regexep of SHA that convert the number only don't have to be fixed because even if the number will be transformed as link it will fail the validation and not be transformed at the end.

It sounds good but not worth costing in my opinion. I have basically given the idea how we should fix this issue in my above comment... I'm just bad at regexp..

**Comment by Unknwon** [comment] 2016-08-31 21:23
This is claimed to be fixed by merging #3563, please help test on `develop` branch or https://try.gogs.io.

**Closed** 2016-08-31 21:22 UTC
Labels: kind/bug, status/needs feedback
