### ISSUE TITLE
500 error: GetCommitOfRelPath: Length must be 40

### ISSUE THREAD

**Issue by vantt** [gogits/gogs#1199] opened 2015-04-09 02:53 UTC
I did upgrade from gogs 0.4.3 to 0.5.0 and got the following error when access to a repo. After that, I did upgrade step by step from 0.5.2 to 0.6.1 but still had the same error. Please be noticed that, all of the other repos seem to be ok except this one got the error.

```
[Macaron] Started GET /thanhnp/Sync_email_anphabe_miomail for 192.168.68.171
2015/04/09 09:47:02 [view.go:134 Home()] [E] GetCommitOfRelPath: Length must be 40
[Macaron] Completed /thanhnp/Sync_email_anphabe_miomail 500 Internal Server Error in 24.580161ms
[Macaron] Started GET /img/500.png for 192.168.68.171
[Macaron] Completed /img/500.png 200 OK in 3.144532ms
```

**Comment by wbg** [comment] 2015-05-10 13:15
same error here: 2015/05/10 15:10:25 [view.go:134 Home()] [E] GetCommitOfRelPath: Length must be 40
version:  Length must be 40

also tried to reinitalize the repo (losing the commit history), but that didnt solve the problem

**Comment by wbg** [comment] 2015-05-10 14:19
little update:
* my repo contained this file: ```-rw-r--r-- 1 root root    0 May 10 09:39 Icon?``` - Apple custom Icon, seems to be missing in my default .gitignore
* the ? is actually a cariage return and removing the file from the repo fixes the problem 
* removing the file fixes the problem
* still having a hard time reading go, but i suspect the error can be fixed by correctly escaping filenames here: https://github.com/gogits/gogs/blob/f03b6be8f997efbcfea45326629e532e834b998b/modules/git/repo_commit.go#L288

**Comment by cowai** [comment] 2015-10-10 11:24
Just wanted to say that I have the same exact bug.

**Comment by Unknwon** [comment] 2015-10-10 15:12
@cowai thanks your info!

**Comment by Unknwon** [comment] 2015-11-20 05:35
@cowai Can you retest on latest version?

**Comment by Unknwon** [comment] 2015-11-20 05:48
Close for now but open for continuing discussion.

**Closed by Unknwon** 2015-11-20 05:48 UTC
Labels: bug

**Comment by matteo107** [comment] 2015-12-15 15:42
in version 0.8.0.1212 problem is still present. 
`2015/12/15 17:01:33 [...routers/repo/view.go:142 Home()] [E] GetCommitByPath: Length must be 40:`

but git log command in project folder returns 40 chars commit hash
`$ git log -1 --pretty=format:%H -- folder1/folder2/`
`a3b98fdbcc7a5fd2b9298a8179e13cc3e06c415a`

**Comment by Unknwon** [comment] 2015-12-15 21:19
Hi @matteo107 , can you reproduce this on https://try.gogs.io ?

**Comment by matteo107** [comment] 2015-12-16 08:33
Hi @Unknwon , I've tried to reproduce it at https://try.gogs.io/matteo107/test2 but unfortunately without success. Everything works fine on https://try.gogs.io 
In my local environment on Windows I cannot access any of folders in the repo [cmd,conf,...,templates], only files at first level directory.

**Comment by Unknwon** [comment] 2015-12-17 00:12
@matteo107 no problem.... what is the shell/cmd you're using?

**Comment by matteo107** [comment] 2015-12-17 07:34
Cmder from http://cmder.net

**Comment by Unknwon** [comment] 2015-12-17 07:37
@matteo107 cool tool! I'll install one on my Windows and see if I can reproduce.

**Comment by Unknwon** [comment] 2015-12-18 02:41
@matteo107 Hi, I've install the cmder but I have very strange problem that I can't cd into any directory, I recommend you start with system cmd or git-bash.

**Comment by matteo107** [comment] 2015-12-18 07:54
Hi @Unknwon , the problem is caused by git version delivered within cygwin package. When I fix my environment to use git for windows by default (https://git-for-windows.github.io) , everything works fine.

**Comment by Unknwon** [comment] 2015-12-18 08:58
@matteo107 good to know! Thanks.
