### ISSUE TITLE
Rendering the wrong Path spec for go get

### ISSUE THREAD

**Issue by Toasterson** [gogits/gogs#4801] opened 2017-09-27 07:32 UTC
- Gogs version (or commit ref): 
b1100b5e345a8a6f5e3f3dfd19e18c9cc8b499e8
- Git version: 
git version 2.13.5
- Operating system: 
- Database (use `[x]`):
  - [x ] PostgreSQL
- Can you reproduce the bug at https://try.gogs.io:
  - [ x] Yes (provide example URL)
https://try.gogs.io/MaxBosse/TestRepo/Test%20Folder?go-get=1
- Log gist (usually found in `log/gogs.log`):
There is no gogs.log on my machine.

## Description
As found out with the devlopers of dep gogs is reporting the wrong path when calling the url from 'go get'. For example if you call https://try.gogs.io/MaxBosse/TestRepo/Test%20Folder?go-get=1 you get this:
```
<html>
	<head>
		<meta name="go-import" content="try.gogs.io/MaxBosse/TestRepo/Test Folder git https://try.gogs.io/MaxBosse/TestRepo.git">
		<meta name="go-source" content="try.gogs.io/MaxBosse/TestRepo/Test Folder _ https://try.gogs.io/MaxBosse/TestRepo/src/master{/dir} https://try.gogs.io/MaxBosse/TestRepo/src/master{/dir}/{file}#L{line}">
	</head>
	<body>
		go get try.gogs.io/MaxBosse/TestRepo/Test Folder
	</body>
</html>
```

However go get and dep expect the first meta tag in head to be like this:
```
<meta name="go-import" content="try.gogs.io/MaxBosse/TestRepo git https://try.gogs.io/MaxBosse/TestRepo.git">
```

So basicly "Test Folder" should not be there in the path otherwise go get and dep fail to download the package from gogs. See the Issue from the dep github in refference:
https://github.com/golang/dep/issues/1213

**Comment by dolmen** [comment] 2017-09-27 08:47
Have you read the line in bold in what you posted?

**Comment by Toasterson** [comment] 2017-09-27 08:48
Nope Sorry missed it. Fixed.

**Comment by dolmen** [comment] 2017-09-27 08:53
This is a duplicate of #4725 which has a proposed fix in #4726.

**Comment by Toasterson** [comment] 2017-09-27 08:59
Are you guys still needing tester for this?

**Comment by Unknwon** [comment] 2017-11-18 05:51
Already fixed in `develop` branch, thanks everyone!

**Closed by Unknwon** 2017-11-18 05:51 UTC
