### ISSUE TITLE
New wiki button is shown for user who cannot create

### ISSUE THREAD

**Issue by ponzipoh** [gogits/gogs#2102] opened 2015-12-04 10:30 UTC
When I try to create a new wiki page, for example [here](https://try.gogs.io/SimonSun/gogs/wiki), all I get is a 404 error.

**Comment by Unknwon** [comment] 2015-12-04 22:33
Sorry I can't reproduce it.

Can you provide more details?

**Comment by ponzipoh** [comment] 2015-12-05 13:54
Go [here](https://try.gogs.io/SimonSun/passport_local_login_demo/wiki), and click the button "Create the first page". I'm redirected to https://try.gogs.io/SimonSun/passport_local_login_demo/wiki/_new which displays 404

**Comment by Unknwon** [comment] 2015-12-05 16:41
Thanks. Are you user `SimonSun`？

**Comment by Unknwon** [comment] 2015-12-05 16:44
OK, I think I found the problem, the `create` should just never show. :sweat_smile:

**Comment by Unknwon** [comment] 2015-12-05 16:48
OK, pushed fix to `develop` branch.

**Closed** 2015-12-06 00:21 UTC
Labels: bug, feedback needed
