### ISSUE TITLE
Allow http(s) git actions using application token

### ISSUE THREAD

**Issue by compressed** [gogits/gogs#842] opened 2015-01-07 14:05 UTC
I was wondering if we can use the application token that a user has created to also permit git actions to repos the user has access to.

This is useful when it's needed to programmatically push commits to a repo.

GitHub allows this via the following:

```
git push https://${GITHUB_TOKEN}@github.com/user/repo.git
```

Edit: It would be best if the token works for the gamut of git actions: e.g. pull, push, clone, etc.

**Comment by Unknwon** [comment] 2015-01-07 14:53
Will Git converts `${GITHUB_TOKEN}` to request header automatically?

**Comment by compressed** [comment] 2015-01-07 16:37
I don't think so. We probably need to add some logic in gogs that if we don't find the username, check if the username is actually a token.

Some more info here: https://github.com/blog/1270-easier-builds-and-deployments-using-git-over-https-and-oauth

**Comment by Unknwon** [comment] 2015-01-07 16:46
I want to say that Go looks like cannot get content before `@`, and it doesn't even say user is using HTTP or HTTPS in `*http.Request`.

But, 

> check if the username is actually a token.

I think it would work. :+1:

**Comment by Unknwon** [comment] 2015-02-07 20:49
Hi @compressed , thanks for waiting. I've pushed some fixes based on changes you made on https://github.com/gogits/gogs/pull/845 . You are also free to try on https://try.gogs.io/

**Comment by Unknwon** [comment] 2015-02-13 20:32
As new mirror release `v0.5.13` is going to release, and this issue is labeled as **feedback needed**, so close it for **assumed resolved**, feel free to reopen this if you want to continue discussing. :beer:

**Closed by Unknwon** 2015-02-13 20:32 UTC
Labels: feature request, feedback needed

**Comment by lavvy** [comment] 2015-09-01 15:13
Please has this feature being added ?  Please how do I learn more how to use it to pull  .tar from my private repository

**Comment by Unknwon** [comment] 2015-09-01 16:02
@lavvy this was implemented a while ago, based on the code, yes, it has added.

**Comment by lavvy** [comment] 2015-09-01 18:06
Oh cool. So I am cloning into Jenkins with this url  when it's public repo
https://try.gogs.io/lavvy/newproj

And I download tar file with this url
https://try.gogs.io/lavvy/newproj/archive/master.tar.gz

So if it now private repo, how will the urls be ?

**Comment by Unknwon** [comment] 2015-09-01 18:13
You use `curl` with basic auth through HTTP.

**Comment by lavvy** [comment] 2015-09-01 18:17
Yeah I mean assessing it from a url for instance Jenkins will access it as
an application. Then if I want to do wget command from Linux , how will the
url be

**Comment by lavvy** [comment] 2015-09-01 18:20
And then how to generate the token for a repo. I couldn't just see how

**Comment by Unknwon** [comment] 2015-09-01 18:27
> Yeah I mean assessing it from a url for instance Jenkins will access it as
an application. Then if I want to do wget command from Linux , how will the
url be

wget https://try.gogs.io/lavvy/newproj/archive/master.tar.gz

> And then how to generate the token for a repo. I couldn't just see how

There is no such that token for a repo, only token for a user

**Comment by lavvy** [comment] 2015-09-01 18:48
sorry for my english may be we are missing something here.

please reproduce this please here
 if you click this
https://try.gogs.io/lavvy/newproj/archive/master.tar.gz
you will download the tar file because that is a PUBLIC repo

BUT :

if you click this
https://try.gogs.io/lavvy/bogons/archive/master.tar.gz

you CANNOT download the tar file because it is a PRIVATE repo

NOW:
my question is
HOW do i insert my token in the second url so that i can download the tar file ?
(REMEMBER I AM ASSESSING WITHOUT A BROWSER THEREFORE I CANNOT LOG IN)

I TRIED THIS
https://try.gogs.io/<USER-TOKEN>/bogons/archive/master.tar.gz
BUT IT DIDNT WORK

**Comment by lavvy** [comment] 2015-09-01 19:39
Please any docs on how to do this please

**Comment by Unknwon** [comment] 2015-09-01 20:23
@lavvy well.. I've said you can use basic auth through HTTP...

**Comment by lavvy** [comment] 2015-09-01 20:36
you mean like this ?

 https://try.gogs.io/lavvy/bogons/archive/master.tar.gz?token=usertoken

**Comment by Unknwon** [comment] 2015-09-01 20:46
I just don't understand why a Google search is so hard... https://docs.oracle.com/cd/E24191_01/common/tutorials/authn_http_basic.html

**Comment by lavvy** [comment] 2015-09-01 23:53
@unknown, am sorry for stressing you out , but please pardon me , i
just discovered this software. And it looks like its relatively new
and quite promising.
Pardon that i couldnt have seen so much of its docs. we are looking to
start using it especially for the private repo feature.
what i am asking for is relatively very simple, i dont know why its
taking this long.
Look at how we get zips or tarballs from private repos from other scm
apps in ubuntu linux command line, for instance;

IN GITHUB :
wget --output-document=<version>.tar.gz \
    https://api.github.com/repos/<owner>/<repo>/tarball/<version>?access_token=<OAUTH-TOKEN>

IN GITLAB:
wget https://gitlab.com/api/v3/projects/<project_id>/repository/raw_blobs/<file_id>?private_token=<your_private_token>

IN BITBUCKET :
wget https://bytebucket.org/$username/$repo/raw/$sha/$filename.jpg?token=$sometoken

IN GOGS ;
(please just give me an example url here:
wget________________________________________________________ please )

once again thank you guys for the beautiful job you guys are doing right there

**Comment by vijairaj** [comment] 2015-09-02 06:23
I took some time to test this functionality. I see that it works for git commands, eg:
```
git clone https://e6503db88f1db7018747fedffd8f3296ce3a01b1@try.gogs.io/u99/pr1
```

But not for all URLs, for example the below _doesn't_ work:
```
wget https://e6503db88f1db7018747fedffd8f3296ce3a01b1@try.gogs.io/u99/pr1/archive/master.tar.gz
```

**Comment by Unknwon** [comment] 2015-09-02 06:51
@lavvy  OK. Sorry for poor docs...

I just added allow URL query to pass token value like all of your 3 examples in `develop` branch, and have updated https://try.gogs.io .

So in your example you need to download a raw blob, here is the example from my local server:

```
wget http://localhost:3000/api/v1/repos/unknwon/macaron/raw/master/README.md\?token\=7ba8bcfb08c9ca128e475d098b42a815e8ddd5d9
```

The basic format it:

```
wget {HOST}/api/v1/repos/{username}/{reponame}/raw/{ref}/{blob path}?token={token}
```

**Comment by lavvy** [comment] 2015-09-02 13:15
yeah, thats what i meant . @unknown it now works like charm but i
tried adjusting the string to download a full release like
v0.0.1.tar.gz or master.tar.gz , it didnt work. please could you
support that too, i think it will use the same pattern

meanwhile thanks @vijairaj,

**Comment by Unknwon** [comment] 2015-09-02 13:41
@lavvy yeah, OK, let me see.

**Comment by Unknwon** [comment] 2015-09-02 13:56
OK, on `develop` and try.gogs.io, you can use following format to download archive:

```
wget {HOST}/api/v1/repos/{username}/{reponame}/archive/{ref}.{format}?token={token}
```

example

```
wget https://try.gogs.io/api/v1/repos/unknwon/macaron/archive/4d7e15f9cb3e636ae685efdee690b6f0b0f2e17a.tar.gz?token=xxx
```

**Comment by lavvy** [comment] 2015-09-02 14:46
Pure. So Pure. thumbs up man. this is good so far and keep up the good
work. Maybe i will have to close back the issue and let the sleeping
dog lie.

**Comment by lavvy** [comment] 2015-09-02 14:47
Pure. So Pure. thumbs up man. this is good so far and keep up the good
work. Maybe i will have to close back the issue and let the sleeping
dog lie  :)

**Comment by Unknwon** [comment] 2015-09-02 14:49
@lavvy :wink:

**Comment by lavvy** [comment] 2015-09-02 14:59
yeah, real good feature right there @Unknwon , but it wasnt easy . you remember u almost gave up yesterday, but u didn't and thats how great guys are born. :+1:

**Comment by lavvy** [comment] 2016-05-04 16:37
Please,  looks like this feature is broken or removed or changed .  It doesn't work again. 
Please is there a different format to download a versioned release from a private repo.

**Comment by klappy** [comment] 2017-05-18 16:02
We are attempting to use token based git pushes so that we don't have to send passwords. Does anybody have any tips on using this with git actions such as pushing to gogs?

**Comment by Unknwon** [comment] 2017-05-19 02:44
@klappy I think use access token as username with empty password should work already.

**Comment by erguotou520** [comment] 2017-07-06 10:42
So how do I push throw token? 
```shell
git push -u https://gogs.erguotou.me/erguotou/gift-pwa.git?token=token master --force
```
like this?

**Comment by Unknwon** [comment] 2017-07-14 22:26
@erguotou520 no, use token ad username when Git prompts you.
