### ISSUE TITLE
怎么组织的其他人对组织里面的仓库有读写权限？

### ISSUE THREAD

**Issue by zhouyixing** [gogits/gogs#2998] opened 2016-04-20 06:41 UTC
如题，本人在gogs上建立了组织，然后把其他同事也拉进了组织。但是其他同事只有读权限，没有写权限。这样不方便协调工作。请问如何设置呢？

**Comment by bkcsoft** [comment] 2016-04-20 08:52
When you create a team to place colleagues in, you tell it that that team should have "Write Access" (寫入權限). Or you can place your colleagues in the Owner-group.

**Comment by zhouyixing** [comment] 2016-04-21 04:43
谢谢(thanks)！ @bkcsoft

**Comment by l2dy** [comment] 2016-04-22 13:21
Please close this issue if the problem is solved.

**Comment by bkcsoft** [comment] 2016-04-22 16:44
Closed as resolved

**Closed by bkcsoft** 2016-04-22 16:44 UTC
