### ISSUE TITLE
Issuses Date Error

### ISSUE THREAD

**Issue by Arylo** [gogits/gogs#2302] opened 2015-12-29 08:42 UTC
I create a new issus, and it display `Created before 8 H`

Gogs 0.8.0.122, Go 1.5.1

**Comment by BurakDev** [comment] 2015-12-29 17:17
Related to #2084 ?

What is your server timezone ? and database engine ?

**Comment by Unknwon** [comment] 2015-12-29 17:43
Sorry, I don't understand your description?

**Comment by Arylo** [comment] 2015-12-30 01:32
Timezone is UTC-8 and use SQLite3

![qq 20151230093050](https://cloud.githubusercontent.com/assets/4516541/12045118/15344d78-aed8-11e5-8a2d-42d92870cbef.png)

**Comment by Unknwon** [comment] 2015-12-30 01:43
Thanks. What is your system and how did you install Gogs?

**Comment by Arylo** [comment] 2015-12-30 01:51
It run on Ubuntu 14.04 x64. And I install it by download the `.tar.gz` file

**Comment by Arylo** [comment] 2015-12-30 01:53
But on project main page/commits page, the date is accurate

**Comment by Unknwon** [comment] 2015-12-30 02:47
OK... can you check what the data time on table `issue` in database?

**Comment by Arylo** [comment] 2015-12-30 02:49
How to check?

**Comment by Unknwon** [comment] 2015-12-30 02:49
Dump the table

**Comment by Unknwon** [comment] 2016-01-11 08:29
Any updates?

**Comment by Arylo** [comment] 2016-01-11 08:34
Recently busy for working, not yet tried

**Comment by Unknwon** [comment] 2016-01-11 08:36
Understandable, but lack of feedback will make this issue be closed.

**Comment by Arylo** [comment] 2016-01-11 08:41
I will reply before Wednesday.

**Comment by Unknwon** [comment] 2016-01-11 08:45
OK, no problem!

**Comment by Unknwon** [comment] 2016-02-17 03:08
ping @Arylo

**Comment by loxK** [comment] 2016-02-18 02:09
I also face this issue since a while now.

In the dashboard any commit submitted right now says 9 hours from now. But if I click the commit, the date is accurate, as it is when listing a repository's commits.

`# date
jeudi 18 février 2016, 13:06:33 (UTC+1100)
# dpkg -l | grep gogs
ii  gogs                            0.8.25-1454711359.e797a22.trusty amd64        Gogs(Go Git Service) is a painless self-hosted Git Service written in Go.
# LANG=C date
Thu Feb 18 13:06:47 NCT 2016`

**Comment by Unknwon** [comment] 2016-02-18 02:13
@loxK are you using MySQL?

**Comment by Unknwon** [comment] 2016-03-10 00:56
Starting from 0.9.2, all time are saved in Unix Timestamp format with UTC, the timezone problem caused by database time parse should be fixed with **new** operations, existing ones are not fixed.

**Comment by Unknwon** [comment] 2016-03-13 21:01
Any updates?

**Comment by Unknwon** [comment] 2016-03-14 06:34
Close as fixed.

**Closed by Unknwon** 2016-03-14 06:34 UTC
Labels: kind/bug, status/needs feedback
