### ISSUE TITLE
Gogs webhooks don't seem to work.

### ISSUE THREAD

**Issue by timshannon** [gogits/gogs#3003] opened 2016-04-20 16:37 UTC
- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.5.0
- Operating system: Ubuntu 15.10
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist:
```
2016/04/19 19:33:59 [I] New random avatar created: 3
2016/04/19 19:48:08 [...routers/user/home.go:364 Profile()] [E] GetUserByName: user does not exist [uid: 0, name: config]
2016/04/19 19:33:59 [I] New random avatar created: 3
2016/04/19 19:48:08 [...routers/user/home.go:364 Profile()] [E] GetUserByName: user does not exist [uid: 0, name: config]
2016/04/19 19:48:08 [...s/middleware/repo.go:84 func1()] [E] GetUserByName: user does not exist [uid: 0, name: ironsmith]
2016/04/19 23:59:05 [.../gogs/models/repo.go:1692 CheckRepoStats()] [E] Update repository count 'num_watches'[48]: database table is locked: repository
2016/04/19 23:59:05 [.../gogs/models/repo.go:1692 CheckRepoStats()] [E] Update repository count 'num_watches'[50]: database table is locked: repository
2016/04/19 23:59:05 [.../gogs/models/repo.go:1692 CheckRepoStats()] [E] Update repository count 'num_watches'[51]: database table is locked: repository
2016/04/19 23:59:05 [.../gogs/models/repo.go:1692 CheckRepoStats()] [E] Update repository count 'num_watches'[52]: database table is locked: repository
2016/04/19 23:59:05 [.../gogs/models/repo.go:1692 CheckRepoStats()] [E] Update repository count 'num_watches'[54]: database table is locked: repository
2016/04/19 23:59:05 [.../gogs/models/repo.go:1692 CheckRepoStats()] [E] Update repository count 'num_watches'[55]: database table is locked: repository
2016/04/19 23:59:05 [.../gogs/models/repo.go:1692 CheckRepoStats()] [E] Update repository count 'num_watches'[56]: database table is locked: repository
2016/04/19 23:59:05 [.../gogs/models/repo.go:1692 CheckRepoStats()] [E] Update repository count 'num_watches'[57]: database table is locked: repository
2016/04/19 23:59:05 [.../gogs/models/repo.go:1692 CheckRepoStats()] [E] Update repository count 'num_watches'[59]: database table is locked: repository
```
## Description
I have a simple gogs (not slack) webhook setup, and I'm trying to tie it into a custom continuous integration application that's listening for the webhook trigger to kick off the next CI run.  I can test the webhook fine, and it works successfully, but it fails when it's triggered via a git push.

![gogs](https://cloud.githubusercontent.com/assets/1330485/14682580/dbcca35c-06eb-11e6-8994-6943811fc934.png)

If I can get you any additional info, let me know.

**Comment by timshannon** [comment] 2016-04-20 16:42
Also, since the listener is a server I wrote, I've also been able to confirm that the webhook post call never makes it to my listener.

**Comment by timshannon** [comment] 2016-04-25 15:49
For other's wanting to accomplish this the work-around I am currently using is a curl call in the git post-receive hook:

**Comment by nmaas87** [comment] 2016-05-12 22:53
I have the same problem. I git-push to activate an drone.io build. If I git-push my code, the "Recent Deliveries" also becomes N/A with 1970... as date.
![fail1](https://cloud.githubusercontent.com/assets/1331457/15232907/a1e41b50-18a4-11e6-9797-1c7a1454627a.png)


If I click "Test Delivery", however, from that moment on the Webhook is fired TWICE: The stuck / N/A one - as well as a new (probably the one created by Test Delivery): Both also are received by drone.io and it starts up TWO build sessions.



![fail3](https://cloud.githubusercontent.com/assets/1331457/15232949/f55e7140-18a4-11e6-8714-764d7863f914.png)

**Comment by bkleef** [comment] 2016-05-28 10:22
Same here on Gogs 0.9.25.0506 and Go 1.6.2. Strange is that only one user has this issue.

**Comment by nmaas87** [comment] 2016-06-01 21:49
@bkleef I can confirm this, seems to be SSH only.

**Comment by jbub** [comment] 2016-06-28 16:39
Also the same behaviour here. Im using SSH.

**Comment by Unknwon** [comment] 2016-06-29 19:58
1. How did you add SSH key to Gogs?
2. What is the SSH URL for you to do `git push`?

All you push bypasses Gogs SSH delegation.

**Comment by timshannon** [comment] 2016-06-29 20:07
For me I'm just doing a git push in the repo folder, which was cloned from the URL copied from gogs which looks similar to this:

```
root@domainofgogsinstance.com:organization/repositoryname.git
```

**Comment by Unknwon** [comment] 2016-06-29 20:49
@timshannon are you able to see push activities on your dashboard if you push through SSH?

**Comment by timshannon** [comment] 2016-06-29 20:58
@Unknwon Yep, all of them.

**Comment by Unknwon** [comment] 2016-06-30 07:23
@timshannon time to check your `path/to/gogs/log/serv.log`, I think there should be quite a lot errors by now...

**Comment by jbub** [comment] 2016-06-30 12:51
All my errors were due to incorrect db pooler configuration - i had pgbouncer in front of postgres running in `transaction` pool_mode. Gogs uses prepared statements which pgbouncer supports only in `session` pool_mode. So be aware :) 

More here: https://pgbouncer.github.io/faq.html#how-to-use-prepared-statements-with-session-pooling

**Comment by timshannon** [comment] 2016-06-30 14:41
@Unknwon well, I'm not actually using the webhooks now, because they don't work.  I'm using a curl call in the git post-receive hook instead and it's been working fine.

I can try the webhooks again if you like, but I assume I'd be getting the same errors as I submitted above.

**Comment by Unknwon** [comment] 2016-07-01 06:46
@timshannon yes, try again and check errors in `path/to/gogs/log/serv.log`.

**Comment by Unknwon** [comment] 2016-07-04 13:19
ping

**Comment by timshannon** [comment] 2016-07-05 17:27
@Unknwon Sorry I was out on vacation for a bit.  Here's my serv.log

```
2016/07/05 17:20:25 [T] Trigger task: http://localhost:443/townsourced/ironsmith/tasks/trigger?branch=master&secret=d852b9a8d177962594c6d688c4b9728f
2016/07/05 17:20:25 [...ts/gogs/cmd/serve.go:128 handleUpdateTask()] [E] Fail to trigger task: Head http://localhost:443/townsourced/ironsmith/tasks/trigger?branch=master&secret=d852b9a8d177962594c6d688c4b9728f: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

```

So it looks like it's expecting a specific response?  I'm not finding any specifics in the documentation as to what kind of return value it's expecting.

**Comment by Unknwon** [comment] 2016-07-08 03:08
The request is simply failed, how did you config Gogs?

**Comment by timshannon** [comment] 2016-07-08 15:29
Other than what I put up above, what are you looking for?  How I configured the webhook?

**Comment by Unknwon** [comment] 2016-07-08 17:37
Your server is not able to request (HTTP HEAD)  itself with URL http://localhost:443/townsourced/ironsmith/tasks/trigger

**Comment by bkleef** [comment] 2016-07-12 17:03
@Unknwon some additional info as we have same issue:

```
```

**Comment by bkleef** [comment] 2016-07-12 17:08
@Unknwon some additional info as we have same issue:

```
2016/07/09 08:51:03 [T] Trigger task: http://localhost:3000/agro4all/srv-product/tasks/trigger?branch=master&secret=1473a8c2dbdcfed82a00d667969a3379
2016/07/09 08:51:03 [...ts/gogs/cmd/serve.go:128 handleUpdateTask()] [E] Fail to trigger task: Head http://localhost:3000/agro4all/srv-product/tasks/trigger?branch=master&secret=1473a8c2dbdcfed82a00d667969a3379: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

Gogs version: 0.9.30.0601
Git version: 2.9.0
OS: Alpine Linux Edge
Database: PostgreSQL

As said before, this only happens while pushing over SSH. HTTPS works great.

**Comment by Unknwon** [comment] 2016-07-15 02:58
Duplicated to https://github.com/gogits/gogs/issues/3077?

**Comment by nmaas87** [comment] 2016-07-15 08:56
@Unknwon Very likely. It seems to work on my end now, as soon as the default setting from #3078 / https://github.com/gogits/gogs/commit/6f6b37f148428eb83cbefdf84253ab7f412e2537 was merged. Everyone should check in their app.ini, wheter they set LOCAL_ROOT_URL there statically to some value and change that and update their gogs container :).

**Comment by bkleef** [comment] 2016-07-15 10:16
@Unknwon I can confirm that `LOCAL_ROOT_URL = %(PROTOCOL)s://localhost:%(HTTP_PORT)s/` works for us.

**Closed** 2016-07-15 16:46 UTC
Labels: status/needs feedback

**Comment by misuzu** [comment] 2017-03-03 20:06
Webhook is still broken when using unix sockets.

**Comment by Unknwon** [comment] 2017-03-03 20:49
@misuzu thanks your feedback! Never thought about that case, can you post logs from `log/hooks/post-receive.log` (assuming you're using 0.10.1)?

**Comment by misuzu** [comment] 2017-03-05 10:54
@Unknwon ```log/hooks/post-receive.log``` is empty for some reason.
log level is set to Trace.
Webhook is working when using plain http.

**Comment by Unknwon** [comment] 2017-03-05 15:13
@misuzu What is your system? exact version?

**Comment by misuzu** [comment] 2017-03-05 21:18
@Unknwon 
Go Git Service 0.10.1.0228
Git Version: 2.11.0
Linux 4.6.4
Debian Stretch

**Comment by Unknwon** [comment] 2017-03-05 21:56
@misuzu Thanks, can you turn on `dev` mode and push again to see if any tracing logs in `post-receive.log`?

**Comment by misuzu** [comment] 2017-03-05 23:15
@Unknwon Yes, thanks!
```
2017/03/06 01:14:25 [TRACE] Trigger task: unix:///tmp/gogs.sock:3000/misuzu/apulse/tasks/trigger?branch=master&secret=f273f7ed949c03497a65c42895e557f9&pusher=1
2017/03/06 01:14:25 [ERROR] [...its/gogs/cmd/hook.go:224 runHookPostReceive()] Fail to trigger task: Head unix:///tmp/gogs.sock:3000/misuzu/apulse/tasks/trigger?branch=master&secret=f273f7ed949c03497a65c42895e557f9&pusher=1: unsupported protocol scheme "unix"
```

**Comment by Unknwon** [comment] 2017-03-05 23:18
@misuzu Now we have very helpful error message! :tada:

Would you mind file a new issue?
