### ISSUE TITLE
Replace "Code" tab with "Files"

### ISSUE THREAD

**Issue by randomdudette** [gogits/gogs#3633] opened 2016-09-10 08:32 UTC
- Gogs version (or commit ref):  try.gogs.io
- Git version: try.gogs.io
- Operating system: try.gogs.io
- Database (use `[x]`): try.gogs.io
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes    https://try.gogs.io/wakawaka/repo
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I believe Gogs should replace the tab "Code" with "Files", or eventually "Tree". The reason is that "Code" is too restrictive and specific, but Git is not intended to track source code only. For example if I'm using Gogs to write a book, I'm not using it for code, but just for text files.

**Comment by randomdudette** [comment] 2016-09-10 08:49
@0xbaadf00d Care to explain the downvote? By the way I don't think all this "social thumbs up/down" introduced by GitHub is useful at all. People just "thumb" stuff without giving any reason...

**Comment by 0xbaadf00d** [comment] 2016-09-10 09:58
I vote down, cause Git is mainly used for developer and technical users.  "Code" (or "Repository") is used on all others plateform like Gogs I use (Github, Gitlab and XP-Dev).

I think "Tree" is a non sens and not follow the Git spirit and "Files" is too like Dropbox or Google Drive.

**Comment by bkcsoft** [comment] 2016-09-10 10:51
@0xbaadf00d actually, on gitlab it's under `Repository->Files`

**Comment by 0xbaadf00d** [comment] 2016-09-10 11:16
@bkcsoft  ah ? yeah you right, I never see they are a submenu in this page on Gitlab. My bad.

**Comment by randomdudette** [comment] 2016-09-10 13:57
@saboya you as well, care to explain? A thumb with no explanation is pretty much pointless and useless...

**Comment by randomdudette** [comment] 2016-09-10 14:00
> you right, I never see they are a submenu in this page on Gitlab

I don't understand GitLab UI at all

**Comment by saboya** [comment] 2016-09-10 16:53
@randomdudette There's not much to it really. Even though I agree that you can use Git to but whatever you want in a repository, the purpose of the tool is to put code in it. So I think code is appropriate.

**Comment by LefsFlarey** [comment] 2016-09-15 07:58
@randomdudette The purpose of Git is for source/version control management, not hosting files. There is a reason why large repositories > 100MB are usually frowned upon. The incredulous ratio of people who use Git for what git is for, _storing code_ is also probably the reason why I down-voted the idea of changing it from `Code` to `Files`.

**Comment by bkcsoft** [comment] 2016-09-29 15:59
At a closer look this is an exact duplicate of #2455 so I'm closing this. Please merge into the other one and continue the discussion there :)

**Closed by bkcsoft** 2016-09-29 15:59 UTC
