### ISSUE TITLE
Error when accessing admin/config

### ISSUE THREAD

**Issue by emil-nasso** [gogits/gogs#2421] opened 2016-01-16 09:36 UTC
I get this error when accessing `admin/config`.

> template: admin/config:82:38: executing "admin/config" at <.Service.DisableMini...>: DisableMinimumKeySizeCheck is not a field of struct type interface {}

I installed using the officiall docker image ( https://github.com/gogits/gogs/tree/master/docker )

**Comment by l2dy** [comment] 2016-01-16 09:49
Duplicate of #2416

**Comment by emil-nasso** [comment] 2016-01-16 10:07
I restarted the container and now the webserver seems to be down. I can't access port 10080/3000 anymore. If i try starting the container without mounting my shared volume with the configuration, everything starts up as it should. So my guess would be that there is some corruption in the configuration.

Is there any part of the configuration i should share here?

**Comment by emil-nasso** [comment] 2016-01-16 10:17
I "fixed" this by doing this:

* Moved to `/var/gogs` contents to `/var/gogs-backup`
* changed the docker container to use the 0.8.10 image: `docker run -d --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs:0.8.10`
* went through the installation process
* copied back the sqlite-database and the git-repositories from the backup into `/var/gogs`.

Might not be a solution for everyone but i got everything back and running again, including the webserver.

**Comment by alimy** [comment] 2016-01-19 10:58
fixed #2440 - a simple resoved solution

**Comment by alimy** [comment] 2016-01-19 11:04
Fixes #2440 - simple resoved solution

**Comment by Unknwon** [comment] 2016-01-26 18:44
It should be fixed already, thanks all!

**Closed by Unknwon** 2016-01-26 18:44 UTC
