### ISSUE TITLE
[Suggestion] Supporting PGP signed commit

### ISSUE THREAD

**Issue by lifehome** [gogits/gogs#3147] opened 2016-05-29 13:00 UTC
- Gogs version (or commit ref): 0.9.28.0527
- Git version: e9ae926e040c94ce66666ae6c330c93918fa321c
- Operating system: ArchLinux
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [X] Yes, URL: https://try.gogs.io/lifehome/viu-proxy/commits/master
  - [ ] No
  - [ ] Not relevant
- Log gist: N/A

## Description

I am creating a mirror repo to Saren-Arterius/viu-proxy, as you can see https://github.com/Saren-Arterius/viu-proxy/commit/2fefb827261de496799048a761935bf7cf3ec118 is PGP signed, and once copied to Gogs, the "Verified" commit become trash-ish since Gogs is currently not supporting PGP signed commit.

## Suggestions

- Supporting PGP signed commit.

**Comment by ekozan** [comment] 2016-05-29 13:55
Dupe of https://github.com/gogits/gogs/issues/2321 and https://github.com/gogits/gogs/issues/2981

Work in progress here : https://github.com/gogits/gogs/pull/3127

**Closed** 2016-05-29 13:57 UTC
