### ISSUE TITLE
Add pagination for user dashboard feeds

### ISSUE THREAD

**Issue by frt678ikjhgffrgtf** [gogits/gogs#3529] opened 2016-08-29 09:40 UTC
- Gogs version (or commit ref): try.gogs.io
- Git version: try.gogs.io
- Operating system: try.gogs.io
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes   https://try.gogs.io (after login, the user dashboard)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

In the user dashboard where all recent updates are displayed, there is no pagination to see the older updates. Only the first 20 are shown.

**Comment by henkjan** [comment] 2016-08-31 19:50
duplicate of #2511

**Comment by Unknwon** [comment] 2016-08-31 21:12
Thanks @henkjan !

**Closed by Unknwon** 2016-08-31 21:12 UTC
Labels: kind/enhancement
