### ISSUE TITLE
time zone trouble

### ISSUE THREAD

**Issue by rapidhere** [gogits/gogs#1500] opened 2015-08-18 06:43 UTC
using 0.6.5 Beta, mysql 5.5.43, git 1.7.9.5, Ubuntu 12.04

the time in the log is right, and both the client, the server have the time zone at Asia/Shanghai, and mysql db use the system time zone

but the display time on the web page(timelines, issues and comments, etc) is 8 hours late than the Asia/Shanghai's time

I've checked the issues, doesn't found a familiar one,so where's problem probably by?

**Comment by Unknwon** [comment] 2015-08-18 11:22
It happens to me as well. 

Just to make sure that are you(browser) and server is in the same time zone, or different?

Somewhat related to https://github.com/gogits/gogs/issues/1360

**Comment by aclindsa** [comment] 2015-08-19 01:34
I am seeing this same issue. For example, in xorm.log, the timestamps match my local time (both server and the machine running browser are in the same time zone). However, when I push a commit and check the dashboard immediately, it says I pushed the commit "4 hours ago" (which is exactly how many hours off I am from UTC).

**Comment by aclindsa** [comment] 2015-08-19 01:58
I just noticed that this issue with time zones is not present everywhere. For instance, the timestamps beside commits on http://git.example.com/username/repository/commits/master appear to be correct (i.e. it says "6 minutes ago") even when the Dashboard (i.e. http://git.example.com) reports the same commits as having been pushed "4 hours ago".

**Comment by rapidhere** [comment] 2015-08-19 04:47
### datetime on my server

![image](https://cloud.githubusercontent.com/assets/3130526/9348866/72a3857c-466f-11e5-865d-2269af8517e1.png)

### and mysql data on my server (a comment commit after serveral minutes)

![image](https://cloud.githubusercontent.com/assets/3130526/9348889/d7c77206-466f-11e5-808d-07d8d411d135.png)

### on my web browser(the same comment)
![image](https://cloud.githubusercontent.com/assets/3130526/9348898/16a91498-4670-11e5-9086-ea8a2f7f2403.png)

### the client's date

![image](https://cloud.githubusercontent.com/assets/3130526/9348903/3660470c-4670-11e5-9239-19d57e04ea29.png)

**Comment by Unknwon** [comment] 2015-08-19 09:30
@rapidhere thanks your info!

I actually know how to quick fix this, as far as I know, time rendered by Go template all has this problem, but render by Go code(compiled code) will remind the correct time(at least same as server time).

**Comment by Unknwon** [comment] 2015-08-19 16:56
OK！Yes! Finally!!!!! 

https://try.gogs.io/unknwon/gogs/issues/19

**Comment by rapidhere** [comment] 2015-08-20 13:57
@Unknwon really fast!

**Comment by Unknwon** [comment] 2015-08-20 14:03
@rapidhere so... is it fixed on your machine? :blush:

**Comment by rapidhere** [comment] 2015-08-21 05:09
@Unknwon I think it will, but i chose to fix it after your next release :-)

**Comment by Unknwon** [comment] 2015-08-21 05:22
Ok, cool :grinning:

**Comment by Unknwon** [comment] 2015-09-02 18:15
Close as implemented. :tada:

**Comment by vijairaj** [comment] 2015-09-07 15:20
I still have this issue with Version: 0.6.9.0903 Beta.
Is this issue fixed in 0.6.9 or 0.7.0?

**Comment by Unknwon** [comment] 2015-09-07 15:21
@vijairaj that is the exact page you're seeing?

It was fixed within 0.6.9 release.

**Comment by vijairaj** [comment] 2015-09-07 15:31
I see the issue in:
* Dashboard (gogs-url)
* User page (gogs-url/user)
* Explore page (gogs-url/explore)
* issues summary (gogs-url/issues)
* project specific issues (gogs-url/user/project/issues)

Commit history (gogs-url/user/project/commits/master) doesn't have this issue though.

I double checked and I am on master (commit#1c2dbd7183f12eff0be33c7a8d1cf0753dd42324) from the Saturday release.

**Comment by vijairaj** [comment] 2015-09-07 15:37
testing it on https://try.gogs.io

https://try.gogs.io/explore says:
![a](https://cloud.githubusercontent.com/assets/953389/9719674/4884fe3a-55a4-11e5-8af1-414a97da0373.png)

https://try.gogs.io/u99/rep1 says:
![a](https://cloud.githubusercontent.com/assets/953389/9719687/6caa09fe-55a4-11e5-8dc3-1c79af2e3505.png)

**Comment by vijairaj** [comment] 2015-09-07 15:38
I am in UTC+0530

**Comment by Unknwon** [comment] 2015-09-07 15:41
Hmm, `updated` time is obvious not the same as the time you `commit` your change.

> I am in UTC+0530

Didn't know that timezone can have 30min shift... so do your time are having 30mins shift from everywhere?

**Comment by jprjr** [comment] 2015-09-09 18:26
@Unknwon timezones can have nearly anything as a shift - there's a large number of 30-minute offsets, and even a few 15-minute offsets.

Wikipedia has a list of current timezones and their offsets: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Timezones are mostly driven by politics, hence there's a lot of weird timezones out there.

**Comment by Unknwon** [comment] 2015-09-09 21:00
@jprjr thanks your detailed explanation! But I'm sorry I didn't say it clear for @vijairaj . I was trying to say what shift between his/her actual time and the time shows on Gogs web UI.

Because currently Gogs only handles the **hour** part, and I did not know that the **minute** part can be different as well.

**Comment by Unknwon** [comment] 2015-09-11 16:34
@vijairaj hi! I've pushed some code to `develop` branch which should fix your problem, but I need your test results see if it really fixed the problem.

**Comment by vijairaj** [comment] 2015-09-12 01:48
I will test it and report back.

**Comment by vijairaj** [comment] 2015-09-12 18:40
I am still testing this fix, at first check I see that in regulateTimeZone() the hour and minutes calculation is off by a byte, I have corrected that below:
```go
hour := com.StrTo(zone[1:3]).MustInt()
minutes := com.StrTo(zone[3:5]).MustInt()
```

I am still unsure if the problem is resolved as I see for an issue created just now to be reported as created 5 hours ago. I will do some more checks and report back.

I added some debug messages to check this, thought it would be useful for your analysis: In
```go
func (i *Issue) AfterSet(colName string, _ xorm.Cell) {
...
fmt.Println("created: ", i.Created);
i.Created = regulateTimeZone(i.Created)
fmt.Println("regulated: ", i.Created);
```
and the output is:
```
created: 2015-09-12 23:20:04 +0530 IST
regulated: 2015-09-12 17:50:04 +0530 IST
```

I actually created the issue @23:20:04 IST so the time reported as created is the right value but after regulating, it has went __back__ 5 hours and displays in the UI as created 5 hours ago. I am not sure how this works correctly for others and in try.gogs.io, so I am still checking whether I am doing it right.

**Comment by Unknwon** [comment] 2015-09-12 18:43
@vijairaj thanks your feedback!

What database you're testing with?

**Comment by vijairaj** [comment] 2015-09-13 04:15
@Unknwon, I am using Postgres.

**Comment by vijairaj** [comment] 2015-09-13 05:14
Ok, now this time I tested again but with Sqlite3 and it works perfectly. The time is reported correctly in every page I tested. I haven't looked at the code quite extensively yet, but in `regulateTimeZone()`:
```go
if setting.UseSQLite3 {
	return t
}
```

Why is this special handling for Sqlite3? I saw the comment `Time from database Go sees it at UTC where they are really Local.` but that doesn't seem to be true at least for postrgres as the time reported is local time with correct timezone info, at least that's what I could see when I print it.

**Comment by Unknwon** [comment] 2015-09-13 11:31
> https://github.com/gogits/gogs/tree/master/docker

@vijairaj yes, thanks your feedback! It turns out MySQL is the only one needs to regulateTimeZone.

**Comment by Unknwon** [comment] 2015-09-13 11:32
I have pushed another fix for it.

**Comment by vijairaj** [comment] 2015-09-13 13:45
Thanks, now it works great with Postgres. I can confirm that _time since_ is reported correctly from every page I tested - including the dashboard, explore, issues, commit history, repo home.

I have couple of suggestions though:
  1. The _absolute time stamp_ that's displayed when clicking on the _relative time stamp_ shows the time in the servers timezone, however it would be more useful to display it in the browsers timezone.
  2. The behaviour when clicking/hovering on the relative time zone is not consistent. In the repo home for example, clicking replaces the relative with absolute time stamp. On issue page for example clicking doesn't do anything hovering displays the absolute time stamp in a different kind of popup.

I can create a new issues for the above if required - thanks for your efforts so far!

**Comment by Unknwon** [comment] 2015-09-13 13:47
Hi @vijairaj !

For 1:

It's another user timezone feature has been requested in another issue.

For 2:

Yes, there are still some pages are using old theme, will be changed to new one(pop up) eventually.

**Comment by vijairaj** [comment] 2015-09-13 13:53
That's great, I guess this issue can then be closed.

**Comment by Unknwon** [comment] 2015-09-13 13:57
@vijairaj thanks again!

**Closed** 2015-09-13 13:56 UTC
Labels: bug, feedback needed

**Comment by dabaer** [comment] 2015-09-24 18:39
Hi there, i still have this issue on Gogs 0.6.13.0918 Beta - Git related timestamps are all correct, but the `updated` timestamps shown in the repository listings for an organization are not:

![iaeo0ly](https://cloud.githubusercontent.com/assets/5544713/10082902/40f22ad6-62b9-11e5-858b-c876a6ffbace.png)

**Comment by Unknwon** [comment] 2015-09-24 18:40
@dabaer hi, what database are you using? And which page?

**Comment by dabaer** [comment] 2015-09-24 19:06
@Unknwon sqlite, and its the organizations repository listing page (example.com/org/OrgName)

**Comment by Unknwon** [comment] 2015-09-24 19:21
@dabaer that's weird, MySQL is the only one should have time zone trouble...

**Comment by dabaer** [comment] 2015-09-24 20:49
indeed - i checked server time settings and everything, the timestamps on git commits are all correct in the web interface, just in that page i keep getting times into the future.

**Comment by Unknwon** [comment] 2015-09-24 20:51
@dabaer what about other pages? issues?

**Comment by dabaer** [comment] 2015-09-24 20:55
anywhere there is a listing of repositories:
![x46wpsc](https://cloud.githubusercontent.com/assets/5544713/10086553/363648d0-62cc-11e5-83dc-9a9c63c6b7c6.png)

**Comment by Unknwon** [comment] 2015-09-24 20:55
@dabaer thanks! Only repository list? How about issues?

**Comment by dabaer** [comment] 2015-09-24 20:56
Ah yes, i didn't notice the issue timestamps before:
![ylxh94c](https://cloud.githubusercontent.com/assets/5544713/10086605/7e12a82e-62cc-11e5-9d38-65db82995b6f.png)

**Comment by Unknwon** [comment] 2015-09-24 20:58
@dabaer is this version ` 0.6.13.0918` you see at the bottom of every page?

**Comment by dabaer** [comment] 2015-09-24 20:59
@Unknwon yeah

**Comment by Unknwon** [comment] 2015-09-24 21:07
@dabaer OK. What is your system? I have to dig more information because simply convert time for SQLite3 will be a bug for most of other users.

**Comment by dabaer** [comment] 2015-09-24 21:22
@Unknwon Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux

**Comment by dabaer** [comment] 2015-09-24 21:50
Might i suggest storing timestamps in UTC, and just using a client time library such as moment.js? That would be ultimately portable

**Comment by Unknwon** [comment] 2015-09-24 22:07
@dabaer SQLite3 did store all time as UTC...

**Comment by dabaer** [comment] 2015-09-24 22:13
@Unknwon so it's an issue with gogs then? moment.js can take raw unix timestamps, format them and display them localized based on the users browser. It would save a bunch of back-end logic!

**Comment by Unknwon** [comment] 2015-09-24 22:15
@dabaer The problem is I can't reproduce it right now, so I'm not sure which part is going wrong. 

And what you're suggestion is based on we have fixes this problem, but not the way to solve the current problem you met because Gogs currently saves time as Date type.

**Comment by dabaer** [comment] 2015-09-24 22:20
More info:
`<span class="time-since" title="Thu, 24 Sep 2015 19:08:02 PDT">3 hours from now</span>`

however,
```
jadenn@STRATO-IN85SD74RL7:~$ date
Thu Sep 24 15:17:53 PDT 2015
```

I'll take a peek into the template to try and get a better understanding of how gogs parses time.

**Comment by Unknwon** [comment] 2015-09-24 22:30
@dabaer actually, if you don't mind get dirty with code, you can do exactly same thing as : https://github.com/gogits/gogs/issues/1500#issuecomment-139808948

**Comment by dabaer** [comment] 2015-09-24 22:40
@Unknwon ok, i have a slight niggle into the issue here, with the timestamp being stored as UTC in the database, but gogs interprets that timestamp as if it were PDT.

**Comment by dabaer** [comment] 2015-09-24 22:43
Also possibly related to that comment, the seconds are slightly off:

![3d1xvih](https://cloud.githubusercontent.com/assets/5544713/10088880/54d0c658-62db-11e5-944b-799f8ec2c429.png)

The applicable database row, and the associated pull request displayed in the browser.

**Comment by Fastidious** [comment] 2015-09-24 22:47
For what is worth, I am not seeing this problem @dabaer has on my test install. Date and time check all fine.

**Comment by Unknwon** [comment] 2015-09-24 22:49
@dabaer Does the time you see from database is exactly same as your system?

**Comment by dabaer** [comment] 2015-09-24 22:52
@Unknwon No the timestamp in the database is UTC, and I am in MST. To me it looks like the system is parsing the UTC timestamp as if it were PDT.

**Comment by dabaer** [comment] 2015-09-24 22:53
I'll try setting up a test instance on a different system and see if i get the same result

**Comment by dabaer** [comment] 2015-09-24 23:27
Okay, test results are in:
![fye1nhv](https://cloud.githubusercontent.com/assets/5544713/10089451/46bc03ec-62e1-11e5-8f7f-2266518cab08.png)

Fresh install of Debian 8, in a VM on my local computer, whereas the other system is in a datacenter in the USA.

I can still somehow reproduce this issue on a fresh system, following the build from source instructions to the letter.

**Comment by Unknwon** [comment] 2015-09-24 23:30
@dabaer thanks your detail!

What type of system you're using? 32 or 64bit?

If it's 64, can you test a installation by download one of zip from https://github.com/gogits/gogs/releases/tag/v0.6.9 ?

**Comment by dabaer** [comment] 2015-09-24 23:32
Yeah, 64. The binary or the source?

**Comment by Unknwon** [comment] 2015-09-24 23:34
@dabaer binary, so basically I'm trying to avoid compile on your machine to rule out some possibilities.

**Comment by dabaer** [comment] 2015-09-24 23:36
@Unknwon ok, the relative times are now correct with the binary installation

**Comment by dabaer** [comment] 2015-09-24 23:37
@Unknwon i'll try building 0.6.9 from source and see if there wasn't a regression to the fix in the newest source.

**Comment by dabaer** [comment] 2015-09-24 23:54
Same issue with the 0.6.9 source. So it's something in my build process - i'm out of ideas on that one :P

**Comment by Unknwon** [comment] 2015-09-24 23:58
@dabaer I don't have any idea either :joy:. What is your Go version?

**Comment by dabaer** [comment] 2015-09-25 00:05
go1.5.1 linux/amd64

**Comment by Unknwon** [comment] 2015-09-25 00:06
OK... I'm developing with exactly the same version.

**Comment by dabaer** [comment] 2015-09-25 00:07
You are able to build from source and have correct timestamps?

**Comment by Unknwon** [comment] 2015-09-25 00:08
:sweat_smile: I can't develop with binary...

**Comment by dabaer** [comment] 2015-09-25 00:13
I could be doing something wrong in the build steps however. My build method is as follow:
  1. Install `git` and `build-essential` via apt
  2. Create user account with login disabled (i call it `gogs` instead of `git` actually, thats my only deviation)
  3. Download the go binary version, and add it to gogs's path as specified in the gogs docs
  4. `go get -u -tags "sqlite" github.com/gogits/gogs`
  5. `cd ~/go/src/github.com/gogits/gogs`
  6. `go build -tags "sqlite"`
  7. `./gogs web`
  8. ...?
  9. Profit.

**Comment by Unknwon** [comment] 2015-09-25 00:15
Indeed, all looks good to me...

**Comment by BurakDev** [comment] 2015-10-01 11:59
Isn't fixed on mine

https://i.gyazo.com/6bdfb0120111e40c9d2764a3d4334710.png
https://i.gyazo.com/cdb180c0e548f3f662dfb74e3d4991bb.png

**Comment by Unknwon** [comment] 2015-10-01 19:21
Hi @BurakDev ,

1. What is your Gogs version?
2. What database you use?
3. What system you have?
4. What way you installed Gogs?

**Comment by utking** [comment] 2015-10-10 02:22
Doesn't work for me too.

What is your Gogs version? 0.6.15-1444420152.bc2f546.wheezy
What database you use? - percona-5.6.26
What system you have? - Debian Wheezy x64
What way you installed Gogs? - Using apt and rpm.packager.io repo.

I always have my commits 9 hours in the future. Tried to change the timezone in /etc/environment; works for the system, but doesn't work for gogs

**Comment by Unknwon** [comment] 2015-10-10 02:24
@utking 

> percona-5.6.26

What is this?

**Comment by utking** [comment] 2015-10-10 02:28
Percona is an open source software company specializing in MySQL Support, Consulting, Managed Services, and Training

That is, Percona is MySQL fork.

**Comment by Unknwon** [comment] 2015-10-10 02:32
@utking 

Since it's not exactly MySQL... I can't promise anything on that...

> What is your Gogs version? 0.6.15

Is this the same version you see at the bottom of every page in web UI?

**Comment by utking** [comment] 2015-10-10 02:39
I can see 2015 Gogs · Version: 0.6.16.1008 Beta · Page: 16ms · Template: 4ms

It doesn't really matter. I have the same trouble on my another server with MySQL.

**Comment by Unknwon** [comment] 2015-10-10 02:46
@utking What is the value of field `created` if you open database table `action`, and how's this value compare to the real time of your system?

**Comment by utking** [comment] 2015-10-10 02:56
The dates in the action table are all correct

**Comment by Unknwon** [comment] 2015-10-10 02:57
@utking what is your time zone? +0900?

**Comment by utking** [comment] 2015-10-10 02:59
+1000

**Comment by Unknwon** [comment] 2015-10-10 03:02
@utking can you post any value of `created`?

**Comment by utking** [comment] 2015-10-10 03:03
Sure. My last commit 2015-10-10 12:10:26

**Comment by Unknwon** [comment] 2015-10-10 03:06
@utking Thanks, I've pushed some code to add a log print to `develop`, can you update Gogs?

**Comment by utking** [comment] 2015-10-10 03:07
upgrade from repo? I used repo to install gogs

**Comment by Unknwon** [comment] 2015-10-10 03:08
> upgrade from repo? I used repo to install gogs

Sorry, I don't understand...

**Comment by utking** [comment] 2015-10-10 03:08
I used rpm.packager.io repositories to install gogs from. I did not installed it from the source.

**Comment by Unknwon** [comment] 2015-10-10 03:10
Ok... but I suppose you can upgrade thought it as well.

I can't produce on all systems I have, so I can't test or detect exceptions. :flushed:

**Comment by utking** [comment] 2015-10-10 03:11
I understand that.
I think I should wait a day or so until rpm.packager.io update the package. Then I will upgrade and check. I check a minute age, and there was no upgrade for gogs on rpm.packager.io.
Thank a lot! You do really great job!

**Comment by Unknwon** [comment] 2015-10-10 03:14
@utking no problem.

Based on https://github.com/gogits/gogs/issues/1500#issuecomment-143080243 , I think there is something quite different from my develop environment, because the binary installation(without compiling on your system) does not have any problem with timezone.

**Comment by utking** [comment] 2015-10-10 03:37
I applied you fix to my system. I reload the page and checked /var/log/gogs.log. I found nothing but lines  about service restart

**Comment by Unknwon** [comment] 2015-10-10 03:39
@utking Good! You also need to change your custom app.ini:

```ini
[log]
LEVEL = Trace
```

PS: night here, will reply you tomorrow. :)

**Comment by utking** [comment] 2015-10-10 04:48
OK, I changed log level and log path.
Next, I tried to put log statements even at the beginning of regulateTimeZone function. The log was empty, except a dozen of lines about service restart.
Also, I tried to execute SQL 'SELECT * FROM repository'. It gave me right dates. 
When I tried to print the field '.Updated' without transformations in the User/Dashboard template, I saw the time was 10 hours in the future.

**Comment by Unknwon** [comment] 2015-10-10 15:13
> Next, I tried to put log statements even at the beginning of regulateTimeZone function. 

I think you modified code but did not recompile Gogs.

**Comment by utking** [comment] 2015-10-10 22:40
I believe so.
Now I've deleted old directory structure and built using "Build from develop branch" manual. It was new clean installation. I'm starting gogs with './gogs web -c conf/app.ini':
2015/10/11 08:39:07 [T] Custom path: /opt/gogs/custom
2015/10/11 08:39:07 [T] Log path: /opt/gogs/log
2015/10/11 08:39:07 [I] Gogs: Go Git Service 0.6.16.1008 Beta
2015/10/11 08:39:07 [I] Log Mode: Console(Trace)
2015/10/11 08:39:07 [I] Cache Service Enabled
2015/10/11 08:39:07 [I] Session Service Enabled
2015/10/11 08:39:07 [I] Mail Service Enabled
2015/10/11 08:39:07 [I] Register Mail Service Enabled
2015/10/11 08:39:07 [I] Notify Mail Service Enabled
2015/10/11 08:39:07 [T] Doing: CheckRepoStats
2015/10/11 08:39:07 [I] Run Mode: Production
2015/10/11 08:39:07 [I] Listen: http://0.0.0.0:3000
...and only [Macaron] lines as before.

**Comment by Unknwon** [comment] 2015-10-10 22:43
@utking  you need to open a page with time in the guture

**Comment by utking** [comment] 2015-10-10 22:50
:) I always open it to check

**Comment by Unknwon** [comment] 2015-10-10 22:54
> ...and only [Macaron] lines as before.

What are those?

**Comment by utking** [comment] 2015-10-10 22:58
[Macaron] Started GET /utking for my_ip
[Macaron] Completed /utking 200 OK in 285.195472ms
[Macaron] Started GET /ng/css/font-awesome.min.css for my_ip
[Macaron] [Static] Serving /ng/css/font-awesome.min.css
[Macaron] Completed /ng/css/font-awesome.min.css 304 Not Modified in 71.189µs
[Macaron] Started GET /ng/js/lib/jquery-1.11.1.min.js for my_ip
[Macaron] [Static] Serving /ng/js/lib/jquery-1.11.1.min.js
[Macaron] Completed /ng/js/lib/jquery-1.11.1.min.js 304 Not Modified in 69.955µs

and so on

**Comment by Unknwon** [comment] 2015-10-10 22:59
@utking and you still see time in the future in this page?

**Comment by utking** [comment] 2015-10-10 23:00
Yes, 13 minutes from now; and I was committing about 11 hours ago

**Comment by Unknwon** [comment] 2015-10-10 23:01
@utking your `DB_TYPE=mysql` right?

**Comment by utking** [comment] 2015-10-10 23:01
That is right

**Comment by Unknwon** [comment] 2015-10-10 23:05
@utking I have no idea now... 

I pushed something to `develop` again, need your help to rebuild again.

**Comment by utking** [comment] 2015-10-10 23:12
I did:
git pull (one commit - print log every time regulater timezone)
go build (no errors)
./gogs web -c conf/app.ini

all the same. There is no a line about time in log. Nothing new.
By the way, it shows me install page every time I rebuild. Is that normal?

**Comment by Unknwon** [comment] 2015-10-10 23:13
> all the same. There is no a line about time in log. Nothing new.

If that's the case, your `DB_TYPE` is not `mysql`.

**Comment by Unknwon** [comment] 2015-10-10 23:14
PS: I think you did not read this page: http://gogs.io/docs/advanced/configuration_cheat_sheet

**Comment by utking** [comment] 2015-10-10 23:14
[database]
; Either "mysql", "postgres" or "sqlite3", it's your choice
DB_TYPE = mysql
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD = ...
; For "postgres" only, either "disable", "require" or "verify-full"
SSL_MODE = disable
; For "sqlite3" and "tidb"
PATH = data/gogs.db

**Comment by utking** [comment] 2015-10-10 23:17
I think I will create new virtual machine and test all again.

**Comment by Unknwon** [comment] 2015-10-10 23:18
Make sure you did:

```ini
[log]
LEVEL = Trace
```

It prints a log for each time if you're using MySQL.

**Comment by utking** [comment] 2015-10-10 23:19
It prints xorm.log, yes

**Comment by Unknwon** [comment] 2015-10-10 23:20
No xorm.log, console, based on your configuration.

**Comment by utking** [comment] 2015-10-10 23:26
My mistake, I did not mean file xorm.log. I get xorm log messages when install, but there is nothing xorm-like on the console. I think I do something wrong. I'll check it with new virtual and go back later

**Comment by Unknwon** [comment] 2015-10-10 23:29
> My mistake, I did not mean file xorm.log. I get xorm log messages when install

That's expected but not the thing we're looking for...

**Comment by utking** [comment] 2015-10-11 00:24
So, I've done with tests on a new clean virtual machine. It works fine. Will find what is wrong on my productions server.

**Comment by Unknwon** [comment] 2015-10-11 00:26
Hmm................ :flushed:

**Comment by utking** [comment] 2015-10-11 01:17
OK. I found that if I specify a timezone in /etc/environment, it change the zone for the whole system, but breaks gogs's time display on a user's dashboard. 
So, I removed timezone settings from the file, reboot the host and now I can see the right time.

**Comment by Unknwon** [comment] 2015-10-11 01:22
@utking very valuable info!

So... what was the timezone settings you have?

**Comment by utking** [comment] 2015-10-11 01:24
I always have Asia/Vladivostok. But now it lives only in the /etc/timezone file

**Comment by utking** [comment] 2015-10-11 01:26
Having the timezone set twice (in /etc/timezone and in /etc/environment) breaks gogs's somehow

**Comment by Unknwon** [comment] 2015-10-11 01:27
That is weird but thanks anyway!
