### ISSUE TITLE
error 500 when reopening issue

### ISSUE THREAD

**Issue by soul9** [gogits/gogs#1830] opened 2015-10-23 12:11 UTC
I have tried on both latest stable tag and develop branch, and I can not reopen an issue. There seems to be an invalid pointer dereference somewhere, but I haven't really been able to pinpoint where.
If I comment and reopen, the comment is posted and displayed properly but the issue is not reopened.
I should add that I have been using develop branch, and then downgraded to stable tag a while ago. Updating again to develop branch does not help.

<pre>
Oct 23 12:01:56 gogs gogs[3980]: [Macaron] Started POST /WTsys/OpenELEC/issues/6/comments for 10.0.251.88                                     [58/1893]
Oct 23 12:01:56 gogs gogs[3980]: 2015/10/23 12:01:56 [T] Comment created: 2/18/78
Oct 23 12:01:56 gogs gogs[3980]: [Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/runtime/panic.go:423 (0x4c2fc9)
Oct 23 12:01:56 gogs gogs[3980]: gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/runtime/panic.go:42 (0x4c1689)
Oct 23 12:01:56 gogs gogs[3980]: panicmem: panic(memoryError)
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/runtime/sigpanic_unix.go:24 (0x4d803a)
Oct 23 12:01:56 gogs gogs[3980]: sigpanic: panicmem()
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/github.com/gogits/gogs/routers/repo/issue.go:773 (0x8b6864)
Oct 23 12:01:56 gogs gogs[3980]: NewComment.func1: pr, err = models.GetUnmergedPullRequest(pull.HeadRepoID, pull.BaseRepoID, pull.HeadBranch, pull.Base
Branch)
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/github.com/gogits/gogs/routers/repo/issue.go:855 (0x88e39f)
Oct 23 12:01:56 gogs gogs[3980]: NewComment: }
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/runtime/asm_amd64.s:438 (0x4f416e)
Oct 23 12:01:56 gogs gogs[3980]: call64: CALLFN(·call64, 64)
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/reflect/value.go:432 (0x8dddea)
Oct 23 12:01:56 gogs gogs[3980]: Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/reflect/value.go:300 (0x8dcab1)
Oct 23 12:01:56 gogs gogs[3980]: Value.Call: return v.call("Call", in)
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/github.com/go-macaron/inject/inject.go:117 (0xb78c42)
Oct 23 12:01:56 gogs gogs[3980]: (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/context.go:113 (0x7bc177)
Oct 23 12:01:56 gogs gogs[3980]: (*Context).run: vals, err := c.Invoke(c.handler())
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/context.go:104 (0x7bc05c)
Oct 23 12:01:56 gogs gogs[3980]: (*Context).Next: c.run()
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/github.com/go-macaron/session/session.go:186 (0x70f144)
Oct 23 12:01:56 gogs gogs[3980]: Sessioner.func1: ctx.Next()
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/runtime/asm_amd64.s:437 (0x4f40ce)
Oct 23 12:01:56 gogs gogs[3980]: call32: CALLFN(·call32, 32)
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/reflect/value.go:432 (0x8dddea)
Oct 23 12:01:56 gogs gogs[3980]: Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/reflect/value.go:300 (0x8dcab1)
Oct 23 12:01:56 gogs gogs[3980]: Value.Call: return v.call("Call", in)
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/github.com/go-macaron/inject/inject.go:117 (0xb78c42)
Oct 23 12:01:56 gogs gogs[3980]: (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/context.go:113 (0x7bc177)
Oct 23 12:01:56 gogs gogs[3980]: (*Context).run: vals, err := c.Invoke(c.handler())
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/context.go:104 (0x7bc05c)
Oct 23 12:01:56 gogs gogs[3980]: (*Context).Next: c.run()
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/recovery.go:161 (0x7d14e2)
Oct 23 12:01:56 gogs gogs[3980]: Recovery.func1: c.Next()
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/runtime/asm_amd64.s:437 (0x4f40ce)
Oct 23 12:01:56 gogs gogs[3980]: call32: CALLFN(·call32, 32)
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/reflect/value.go:432 (0x8dddea)
Oct 23 12:01:56 gogs gogs[3980]: Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/reflect/value.go:300 (0x8dcab1)
Oct 23 12:01:56 gogs gogs[3980]: Value.Call: return v.call("Call", in)
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/github.com/go-macaron/inject/inject.go:117 (0xb78c42)
Oct 23 12:01:56 gogs gogs[3980]: (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/context.go:113 (0x7bc177)
Oct 23 12:01:56 gogs gogs[3980]: (*Context).run: vals, err := c.Invoke(c.handler())
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/context.go:104 (0x7bc05c)
Oct 23 12:01:56 gogs gogs[3980]: (*Context).Next: c.run()
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/logger.go:40 (0x7d012e)
Oct 23 12:01:56 gogs gogs[3980]: Logger.func1: ctx.Next()
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/runtime/asm_amd64.s:437 (0x4f40ce)
Oct 23 12:01:56 gogs gogs[3980]: call32: CALLFN(·call32, 32)
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/reflect/value.go:432 (0x8dddea)
Oct 23 12:01:56 gogs gogs[3980]: Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/reflect/value.go:300 (0x8dcab1)
Oct 23 12:01:56 gogs gogs[3980]: Value.Call: return v.call("Call", in)
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/github.com/go-macaron/inject/inject.go:117 (0xb78c42)
Oct 23 12:01:56 gogs gogs[3980]: (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/context.go:113 (0x7bc177)
Oct 23 12:01:56 gogs gogs[3980]: (*Context).run: vals, err := c.Invoke(c.handler())
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/router.go:184 (0x7d2c54)
Oct 23 12:01:56 gogs gogs[3980]: (*Router).Handle.func1: c.run()
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/router.go:286 (0x7c95dd)
Oct 23 12:01:56 gogs gogs[3980]: (*Router).ServeHTTP: h(rw, req, p)
Oct 23 12:01:56 gogs gogs[3980]: /home/git/go/src/gopkg.in/macaron.v1/macaron.go:175 (0x7c151a)
Oct 23 12:01:56 gogs gogs[3980]: (*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/net/http/server.go:1862 (0x6c6d0e)
Oct 23 12:01:56 gogs gogs[3980]: serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/net/http/server.go:1361 (0x6c44fe)
Oct 23 12:01:56 gogs gogs[3980]: (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
Oct 23 12:01:56 gogs gogs[3980]: /home/gogs/go/src/runtime/asm_amd64.s:1696 (0x4f63f1)
Oct 23 12:01:56 gogs gogs[3980]: goexit: BYTE        $0x90        // NOP
Oct 23 12:01:56 gogs gogs[3980]: [Macaron] Completed /WTsys/OpenELEC/issues/6/comments 500 Internal Server Error in 193.623784ms
</pre>

**Comment by soul9** [comment] 2015-10-23 12:16
the issue text also seems to get overwritten by the It looks like sometimes reopening is successful, but in that case the issue text is overwritten by the reopened comment text.

**Comment by ChangePlaces** [comment] 2015-10-23 12:25
Just to put a number in the mix: this doesn't happen in Version: 0.6.9.0903 Beta

**Comment by Unknwon** [comment] 2015-10-23 14:31
Thanks your feedback!

I've push a quick fix to `master` branch, please help test again!

**Comment by soul9** [comment] 2015-10-23 16:16
better. reopening doesn't cause error 500, but issue text (0th comment) is replaced by new comment both on "comment and close" and on "comment and reopen"

**Comment by Unknwon** [comment] 2015-10-23 16:18
> reopening doesn't cause error 500, but issue text (0th comment) is replaced by new comment both on "comment and close" and on "comment and reopen"

Can you reproduce this on https://try.gogs.io ?

**Comment by soul9** [comment] 2015-10-23 16:29
yes I can.
Check https://try.gogs.io/abcaad/test/issues/1
The 0th comment was `#1830`, now it's "2nd", the comment I used for closing the issue.

**Comment by Unknwon** [comment] 2015-10-23 16:36
I see... thanks. I can't produce it locally somehow... let me check.

**Comment by joubertredrat** [comment] 2015-10-23 16:42
I can't produce here too, works normally here. 
Gogs 0.6.16.1002 + Go 1.5.1 + Mysql 5.5

**Comment by Unknwon** [comment] 2015-10-23 16:44
It is 100% reproducible on try.gogs.io but I can't reproduce locally... :sweat:

**Comment by Unknwon** [comment] 2015-10-23 16:46
OK! I found the problem!

**Comment by joubertredrat** [comment] 2015-10-23 16:47
@Unknwon hmm, makes sense, I enabled mail service here few days ago.

**Comment by Unknwon** [comment] 2015-10-23 16:55
OK! Should be fixed by now, you can test on https://try.gogs.io again.

**Comment by soul9** [comment] 2015-10-23 17:01
yep, just updated the code on my server and it looks like you managed to track it down and eradicate it, finally.
Thanks a lot!

**Comment by Unknwon** [comment] 2015-10-23 17:02
:tada:

**Closed** 2015-10-23 17:02 UTC
Labels: bug
