### ISSUE TITLE
Removing a collaborator deletes a repo

### ISSUE THREAD

**Issue by alangrafu** [gogits/gogs#1310] opened 2015-06-05 05:33 UTC
I tried it twice to make sure I could replicate the problem: I created a repo and added a collaborator. Then I removed the collaborator and the repository is gone. Not only that, it is not possible to create a new repository with the same name, so probably only part of the repo's data is deleted from the database.

**Comment by da-kid** [comment] 2015-06-10 16:43
I could not reproduce such behaviour.
Are you using the `dev` branch?

**Comment by dentmaged** [comment] 2015-06-10 17:38
@da-kid The issue is from 6 days ago, I believe it wasn't fixed then.

**Comment by da-kid** [comment] 2015-06-10 21:02
@dentmaged I tried it out with the newest release (master branch) and could not reproduce it.

**Comment by Unknwon** [comment] 2015-08-06 03:51
This wrong behaviour has been fixed in latest version `master` and release `v0.6.3`, please upgrade to avoid it! :flushed:

**Comment by Unknwon** [comment] 2015-08-15 00:52
Close for now but open for continuing discussion.

**Closed by Unknwon** 2015-08-15 00:52 UTC
Labels: bug, feedback needed
