### ISSUE TITLE
In organization options, Gravatar E-mail isn't shown as required when it is required

### ISSUE THREAD

**Issue by csu** [gogits/gogs#1293] opened 2015-05-25 18:22 UTC
In organization options, Gravatar E-mail isn't shown as required, but Gogs won't let you update settings unless you have one set:
![screen shot 2015-05-25 at 11 22 47 am](https://cloud.githubusercontent.com/assets/164822/7800829/66b0d9f0-02d0-11e5-9f66-2e2f00f36712.jpg)

**Comment by csu** [comment] 2015-05-25 18:22
![screen shot 2015-05-25 at 11 22 47 am](https://cloud.githubusercontent.com/assets/164822/7800827/61629f10-02d0-11e5-8038-3e98d7227714.jpg)

**Comment by linquize** [comment] 2015-05-26 14:25
Duplicate of #1193?

**Comment by csu** [comment] 2015-05-26 17:22
@linquize I don't think so. I think #1193 is referring to the email in the screenshot labeled `E-mail *`, whereas I'm referring to the `Gravatar Email` field, which isn't labeled as required, when apparently it is.

**Comment by tboerger** [comment] 2015-06-01 08:07
Does it really make sense to have the Gravatar email field as a required field?

**Comment by csu** [comment] 2015-06-01 18:03
@tboerger no

**Comment by manfer** [comment] 2015-07-28 11:55
I would say that not only it should not be required but shouldn't be autofilled either (unless the organization has chosen to autofill that option on registration, with a checkbox or something).

In my opinion if an organization wants to use an email but don't want to use the associated gravatar nor upload any avatar, shouldn't be forced to use the gravatar.

The problem is not only in organization options but in user options too.

**Comment by Unknwon** [comment] 2015-07-28 14:34
@manfer the idea is good but Gogs needs to add a avatar generator based on e-mail address, there are some libs could do this, just need time to add it into Gogs.

**Comment by Unknwon** [comment] 2015-09-06 15:08
This field is removed in `develop` branch and can be tested on https://try.gogs.io

**Comment by Unknwon** [comment] 2015-09-12 01:04
Close as fixed.

**Closed** 2015-09-12 01:04 UTC
Labels: bug, feedback needed
