### ISSUE TITLE
Can not access gogs.io by Firefox

### ISSUE THREAD

**Issue by huache** [gogits/gogs#3606] opened 2016-09-06 04:30 UTC
Your website https://gogs.io/ cannot be accessed by Firefox. 
By the way, Firefox is not sucks...

**Comment by termlimit** [comment] 2016-09-06 04:43
This appears to be caused by OCSP signing. In about:config if you set security.ssl.enable_ocsp_stapling to false, the website functions normally. When this is set to true (now the default setting), the following message appears:
-------------------------------------
Secure Connection Failed

An error occurred during a connection to gogs.io. Invalid OCSP signing certificate in OCSP response. Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT

- The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.

- Please contact the website owners to inform them of this problem.

-------------------------------------

**Comment by strk** [comment] 2016-09-06 10:11
Was already reported with #3592, closed as "invalid" by @Unknwon 
I confirm the problem, and as #3592 reports the problem is also confirmed by ssllabs.com

**Comment by silverwind** [comment] 2016-09-06 21:41
I think the server is stapling the wrong OCSP:

https://certificate.revocationcheck.com/gogs.io

> Bad signature on embedded certificate: Authority Key Identifier of Signing certificate (StartCom Class 1 Primary Intermediate Server CA OCSP Responder) is not from Issuer ('Let's Encrypt Authority X3')

**Comment by OndrejIT** [comment] 2016-09-08 08:27
Now it's ok for me...
(Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0)

**Comment by strk** [comment] 2016-09-08 08:29
Confirmed, it works for me too now.

**Closed** 2016-09-09 00:24 UTC
