### ISSUE TITLE
ssh key import does not work unless very careful

### ISSUE THREAD

**Issue by stroucki** [gogits/gogs#3780] opened 2016-10-17 21:18 UTC
- Gogs version (or commit ref): 2bec8a4f1ef6b48220a0010c1482e561abd55810
- Git version: 2.1.4
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist: Sorry, we're not able to verify your SSH key: extractTypeFromBase64Key: invalid key format: (nil)
## Description

When trying to add an ssh key by copy-paste, the trailing newline results in a two-element slice in models/ssh_key.go/parseKeyString, which causes the wrong branch to be taken when the key is OpenSSH format.

Pull request follows.

**Comment by ChangePlaces** [comment] 2016-10-17 22:30
I can confirm this happens to me as well.

**Comment by jamesa** [comment] 2016-10-25 10:37
This is a duplicate of #3480.

**Comment by bkcsoft** [comment] 2016-10-25 21:07
Related but I don't think it's a duplicate, I'll keep this open unless author closes it :)

**Comment by stroucki** [comment] 2016-10-27 21:32
Can we have someone apply the patch so that maybe both can be closed?

**Comment by Unknwon** [comment] 2017-01-31 18:29
I think it's been fixed already..

**Closed by Unknwon** 2017-01-31 18:29 UTC
