### ISSUE TITLE
Feature request: Integrated wiki

### ISSUE THREAD

**Issue by TheExoduser** [gogits/gogs#1248] opened 2015-04-29 22:49 UTC
As some of you might have seen on hosters like GitHub there is an integrated wiki feature available for projects, hosted on their servers. 
Gogs is without a doubt pretty awesome already, but maybe you could add this request to your roadmap?

**Comment by matt-h** [comment] 2015-04-30 00:24
This is a duplicate of #270

**Comment by HLFH** [comment] 2015-07-25 20:06
@Unknwon Hi. It's a duplicate. Please close this issue.

**Closed** 2015-07-25 21:29 UTC
