### ISSUE TITLE
Panic when two links are nested in MD

### ISSUE THREAD

**Issue by kisy** [gogits/gogs#2019] opened 2015-11-23 01:54 UTC
/usr/local/go/src/net/http/server.go:1862 (0x7757be)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1361 (0x772fae)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:1696 (0x4f5701)
        goexit: BYTE    $0x90   // NOP
[Macaron] Completed /group/kernel 500 Internal Server Error in 145.130587ms

**Comment by kisy** [comment] 2015-11-23 05:13
Error Cause

readme.md  file add this line

[![Latest Stable Version](https://poser.pugx.org/laravel/framework/version.png)](https://packagist.org/packages/laravel/framework) [![Total Downloads](https://poser.pugx.org/laravel/framework/d/total.png)](https://packagist.org/packages/laravel/framework) [![Build Status](https://travis-ci.org/laravel/framework.png)](https://travis-ci.org/laravel/framework)

**Comment by SoftCreatR** [comment] 2015-11-23 06:38
Did you delete the templates directory before performing the upgrade? Because it works fine for me.

**Comment by kisy** [comment] 2015-11-23 07:18
Yes, I deleted.
rm -rf ./templates

**Comment by SoftCreatR** [comment] 2015-11-23 07:38
And also overwritten ALL files?

Just in case, that someone don't know how to upgrade properly:

- Stop gogs (e.g. `service gogs stop`)
- Download and unpack the latest version e.g.
```
mkdir ~/tmp
cd ~/tmp
wget https://github.com/gogits/gogs/releases/download/v0.7.19/linux_amd64.tar.gz
tar xfvz linux_amd64.tar.gz
```
- Back up your current gogs installation e.g. `cp -rp ~/go/src/github.com/gogits/gogs ~/go/src/github.com/gogits/gogs.bak`
- Delete the template directory e.g. rm -rf /home/git/go/src/github.com/gogits/gogs/templates
- Copy the new version over the old one e.g. `cp ~/tmp/gogs/. ~/go/src/github.com/gogits/gogs`
- Start gogs (e.g. `service gogs start`)

That's how i've done it on my Debian Jessie x64.

**Comment by stonerl** [comment] 2015-11-23 08:13
@kisy Are you able to reproduce this error on https://try.gogs.io ?

**Comment by kisy** [comment] 2015-11-23 09:51
@stonerl  It's ok on https://try.gogs.io

@SoftCreatR I re-do it again, but the result is a failure. thank you for your help! 

I have deleted the line.

**Comment by Unknwon** [comment] 2015-11-23 12:52
Thanks @stonerl @SoftCreatR !

@kisy I've found and fixed a related bug right after 0.7.19 release.... https://github.com/gogits/gogs/commit/f12832c61e95a9eff1195f543fc11d1113dae4fc

**Comment by kisy** [comment] 2015-11-23 14:02
@Unknwon I'm coming

```

        Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:300 (0x98b7b1)
        Value.Call: return v.call("Call", in)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbc8142)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86dbe7)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 (0x86dacc)
/home/vagrant/go/src/github.com/go-macaron/session/session.go:186 (0x7bd9a4)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4f33be)
        call32: CALLFN(·call32, 32)
/usr/local/go/src/reflect/value.go:432 (0x98caea)
        Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:300 (0x98b7b1)
        Value.Call: return v.call("Call", in)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbc8142)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86dbe7)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 (0x86dacc)
/home/vagrant/go/src/gopkg.in/macaron.v1/recovery.go:161 (0x882f52)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4f33be)
        call32: CALLFN(·call32, 32)
/usr/local/go/src/reflect/value.go:432 (0x98caea)
        Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:300 (0x98b7b1)
        Value.Call: return v.call("Call", in)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbc8142)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86dbe7)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 (0x86dacc)
/home/vagrant/go/src/gopkg.in/macaron.v1/logger.go:40 (0x881b9e)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4f33be)
        call32: CALLFN(·call32, 32)
/usr/local/go/src/reflect/value.go:432 (0x98caea)
        Value.call: call(frametype, fn, args, uint32(frametype.size), uint32(retOffset))
/usr/local/go/src/reflect/value.go:300 (0x98b7b1)
        Value.Call: return v.call("Call", in)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbc8142)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86dbe7)
/home/vagrant/go/src/gopkg.in/macaron.v1/router.go:184 (0x8846c4)
/home/vagrant/go/src/gopkg.in/macaron.v1/router.go:286 (0x87b04d)
/home/vagrant/go/src/gopkg.in/macaron.v1/macaron.go:175 (0x872f8a)
/usr/local/go/src/net/http/server.go:1862 (0x7757be)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1361 (0x772fae)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_amd64.s:1696 (0x4f5701)
        goexit: BYTE    $0x90   // NOP
[Macaron] Completed /chaim/md 500 Internal Server Error in 95.27186ms
```

**Comment by Unknwon** [comment] 2015-11-23 14:38
@kisy yes, that's what I expected :trollface: and yes, it should be fixed in `master`.

**Comment by kisy** [comment] 2015-11-23 14:52
@Unknwon @SoftCreatR @stonerl Thanks!

**Comment by Unknwon** [comment] 2015-11-23 15:06
Please close when you confirm fixed in `master` or https://try.gogs.io

**Closed** 2015-11-24 01:18 UTC
Labels: feedback needed

**Comment by Unknwon** [comment] 2015-11-24 01:20
:trollface:
