### ISSUE TITLE
PR merge pre-conditions (forced reviews)

### ISSUE THREAD

**Issue by aaronshaf** [gogits/gogs#2902] opened 2016-03-28 17:06 UTC
Many of us are stuck using Gerrit, partly for its feature of forcing a code review before merge / cherry-pick. It'd be great if there was a way to predicate a merge on a +2 / +1 by certain parties.

**Comment by strk** [comment] 2016-07-22 19:48
Yes, duplicate of #1663

**Closed** 2016-07-23 05:23 UTC
Labels: dont send pull request, kind/feature, status/needs feedback
