### ISSUE TITLE
Custom reserved word for repo names?

### ISSUE THREAD

**Issue by leny** [gogits/gogs#2971] opened 2016-04-13 11:30 UTC
Hi,

I've just migrate my server from Gitlab (which was a big pain to maintain & update) to Gogs, and was very happy with the installation & configuration until I want to create, in an organisation, a repo called "api" and "admin", which, apparently, are "reserved words".

Since I can use these words on Gitlab, GitHub and Bitbucket, I really don't understand why I can't use these names, common names for web-application parts.

Why can't we, as administrators of our own Gogs installation, decide which words can or cannot be used as repo name, specially for such comman and widely-used words in development?

Thanks in advance,

**Comment by neeasade** [comment] 2016-04-13 16:58
I believe the reason for those being reserved is because they are part of gogs api and admin paths/views -- are you asking why such paths aren't configurable?

**Comment by leny** [comment] 2016-04-13 17:05
(sorry for my english, it's not my first language, if this sound aggressive it's because a lack of vocabulary)

My point of view is that, as an user, I don't understand why I can't use certain words as repositories name (specially for words like "admin" or "api", which are widely used by developers).

Whatever the reason, I think it's wrong. For tools like these, it creates a frustration for the user, and I think it's wrong.

And, as in GitHub, Gitlab and Bitbucket it's not a problem, I really doesn't understand why the Gogs users should be "restrained".

**Comment by bkcsoft** [comment] 2016-04-16 23:53
Isn't this the same as #2903 ?

**Comment by bkcsoft** [comment] 2016-05-30 04:19
Closing as duplicate of #2903

**Closed by bkcsoft** 2016-05-30 04:19 UTC
