### ISSUE TITLE
Merge between branchs created from master branch

### ISSUE THREAD

**Issue by carliandro** [gogits/gogs#3835] opened 2016-10-31 20:11 UTC
- Gogs version (or commit ref):  0.9.83.0816
- Git version: 2.9.2
- Operating system: Windows Server
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
When I try merge two branches created from master branch I receive error 500.
But if I try merge any branch with master branch it works fine.

**Comment by 0xbaadf00d** [comment] 2016-10-31 20:11
Maybe duplicate of #3743 ?

**Comment by carliandro** [comment] 2016-11-09 11:46
I did read and tried the solutions showed on issue but without success.

**Comment by carliandro** [comment] 2016-11-10 12:10
Some solution for this?

**Comment by Unknwon** [comment] 2016-12-22 00:48
>Log gist:

Why don't you post error logs from backend?...

**Closed by Unknwon** 2016-12-22 00:48 UTC
