### ISSUE TITLE
Gogs.io page not loaded

### ISSUE THREAD

**Issue by hsafe** [gogits/gogs#3829] opened 2016-10-29 07:24 UTC
- Gogs version (or commit ref): 
- Git version: 
- Operating system: 
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

...
Hi
Why is the site not borwsable with ssl certificate error:Invalid OCSP signing certificate in OCSP response?
 also trying to browse on http it is reverted to the https and the same error?

**Comment by jbub** [comment] 2016-10-29 08:20
duplicate of #3793

**Closed** 2016-10-29 11:30 UTC
