### ISSUE TITLE
Pull request not updating after push --force

### ISSUE THREAD

**Issue by andreynering** [gogits/gogs#1838] opened 2015-10-25 23:27 UTC
I made two pull request tests on try.gogs.io.

[The first one was a non-conflit one](https://try.gogs.io/andreynering/pull-request-test/pulls/1), and I could merge it without any problem.

[In the second I reproduced a conflicting scenario](https://try.gogs.io/andreynering/pull-request-test/pulls/2), and there's an issue with it.

1. I made a pull request from a previous commit, editing a line that was already edited on master;
2. Gogs told me that there were conflits, and I should solve it myself. OK;
3. I made a rebase and force pushed to the branch I formely created the pull request from.

On GitHub, this would trigger an update on the pull request, and should be possible to merge the pull request. But here, nothing happened.

**Comment by Unknwon** [comment] 2015-10-25 23:50
> I made a rebase and force pushed to the branch I formely created the pull request from.

Can you try one without force push?

**Comment by Unknwon** [comment] 2015-10-25 23:54
BTW, Gogs does retest conflict, but I didn't test force push so it may be the problem.

**Comment by andreynering** [comment] 2015-10-25 23:59
> Can you try one without force push?

I did, but the push was rejected because of conflicts, and I had to force push.

> BTW, Gogs does retest conflict, but I didn't test force push so it may be the problem.

I think `--force` will always be require after a rebase, and also after `commit --amend`, etc. So, in most cases, you would have to force push.

**Comment by Unknwon** [comment] 2015-10-26 00:09
How about close this one and create a new PR? What does Gogs say?

**Comment by andreynering** [comment] 2015-10-26 00:16
[It worked](https://try.gogs.io/andreynering/pull-request-test/pulls/3).

**Comment by Unknwon** [comment] 2015-10-26 00:37
Hmm.. so the problem is the force push.

Can you give some steps to do a rebase and force push for a conflict PR? So I can figure out how to make it work.

**Comment by andreynering** [comment] 2015-10-26 01:01
This is what I did:

- Created a "conflict" branch from the actual commit;
- Checkout to master again;
- Edited a line and pushed to the original repository;
- Checkout to conflict;
- Edited the same line with another content and pushed to the forked
repository;
- Created a pull request (conflict -> master). Couldn't merge because of
the conflict;
- Locally rebased conflict with master. Had to manually fix the conflicted
line;
- Tried to push without --force, couldn't because of the conflict;
- Force pushed local/conflict to fork/conflict.
Em 25/10/2015 22:37, "无闻" <notifications@github.com> escreveu:

**Comment by Unknwon** [comment] 2015-10-26 01:03
Thanks! I'll try it tomorrow.

**Comment by Unknwon** [comment] 2015-10-30 00:19
> Locally rebased conflict with master

Which master do you rebase to?

When I did "git rebase master" while I'm in conflict branch, git says: 

```
Current branch conflict is up to date.

```

**Comment by andreynering** [comment] 2015-10-30 10:12
> Which master do you rebase to?

The master locally.

> When I did `git rebase master` while I'm in conflict branch, git says:

> `Current branch conflict is up to date.`

Hmm... It should ask you to resolve the conflict.

You don't actually have to follow step by step what I did. You just have to reproduce a confliting scenario. Something like this:

![gogs conflict](https://cloud.githubusercontent.com/assets/7011819/10843050/718c5910-7edd-11e5-8643-18a8c6668c3e.png)

And then, use force push to see if the pull request updates.

**Comment by Unknwon** [comment] 2015-10-31 15:15
OK, so `rebase` isn't required?

**Comment by andreynering** [comment] 2015-10-31 15:22
It is required because because we have to know if Gogs is updating the pull
request or not. After a rebased and force push, it should be mergeble.

I don't know why the revert branch is up to date for you. Maybe you created
the "revert" branch after commiting to master?
Em 31/10/2015 13:16, "无闻" <notifications@github.com> escreveu:

**Comment by Unknwon** [comment] 2015-10-31 15:32
Actually i don't know which `mater` you are referring, it's another branch same repository or ...?

**Comment by andreynering** [comment] 2015-10-31 15:41
Yes, the default branch created by Git, in the same repository.

Sorry for not being clear. Don't be afraid to ask questions while you have doubts. =)

**Comment by Unknwon** [comment] 2015-10-31 16:05
:trollface: Hmm, so if I remember correctly... you can't create pull request in same repository right now in Gogs?

**Comment by andreynering** [comment] 2015-10-31 16:13
I am not sure if I understood what you mean.

To create another pull request from the same branch, I had to close the existing one.

But... Did you understand the steps to reproduce the issue now?

**Comment by Unknwon** [comment] 2015-10-31 16:19
So you have conflicts between two branches in the same repository, but I don't see how this relates to pull request?

**Comment by andreynering** [comment] 2015-10-31 16:51
The real issue is that the pull request I made didn't update after a force push.

This actually don't relate with the steps I did to catch that, or even with having conflicts or not. It's just the way I found to know if Gogs is in fact rechecking for conflicts or not (before the force push, it should have conflicts, after not anymore).

**Comment by Unknwon** [comment] 2015-10-31 17:04
Gogs does recheck conflicts for every push, but right now I can't reproduce a case that needs force push, so I don't know why Gogs isn't updating the pull request data.

**Comment by JohnMaguire** [comment] 2015-11-01 15:52
This seems like a simple test to see if overwriting history would break a pull request:

1. Make changes to a file.
2. `git add file.txt`
3. `git commit`
4. `git push`
5. Make different changes to the file.
6. `git commit -a`
7. `git push -f`

**Comment by JohnMaguire** [comment] 2015-11-01 16:03
Using the steps I outlined, I cannot reproduce any issue with pull requests after using a force push on 0.6.15.0926.

**Comment by JohnMaguire** [comment] 2015-11-01 16:05
The interesting part about this is that regardless of what the pull request *says*, if you merge it, it should merge according to the branch you pushed. (i.e. If you successfully force pushed the branch, Git will have the commits correct.)

But you're saying that the UI is not updating to reflect the changes you made to the pull request, if I am understanding correctly? Can you try merging the pull request anyway and seeing if the correct changes are merged?

Is there some sort of caching layer that could be causing this issue?

**Comment by Unknwon** [comment] 2015-11-01 17:17
@JohnMaguire Thanks your info!

But in 0.6.15 Gogs didn't have ability to recheck conflict for every push, this feature is introduced in 0.6.18... so I'm not sure if we're talking the same thing here...

**Comment by JohnMaguire** [comment] 2015-11-01 21:15
@Unknwon Gotcha. It sounded to me like his issue was the pull request not updating to show the force pushed commit. (i.e. It was still showing the old commit.) I did not realize he was referring to whether he could merge the pull request or not specifically.

Here is how I am able to reproduce it on try.gogs.io.

1. Fork andreynering/pull-request-test
2. Clone your fork
3. `git checkout -b test`
4. `git reset HEAD~1`
5. Modify README.md by changing the line "Line added on master"
6. `git commit -am 'conflicting commit'`
7. `git push -u origin test`
8. Now make a pull request to andreynering/pull-request-test into master.

This will get you a pull request with conflicts. To reproduce the behavior reported in the bug, do the following from within your fork:

1. `git remote add andreynering git@try.gogs.io:andreynering/pull-request-test.git`
2. `git pull andreynering master`
3. Fix the merge conflict by using your change in README.md
4. `git commit -am "resolve conflict"`
5. `git push`

At this point, the conflict has been resolved, but the pull request can still not be merged. In order to verify that the conflict has indeed been resolved, you can do this:

1. Clone andreynering's repository.
2. `git remote add fork <your-clone-url>`
3. `git fetch fork test`
4. `git merge FETCH_HEAD`

You will see that there is no conflict.

**Comment by Unknwon** [comment] 2015-11-01 21:23
@JohnMaguire thanks! I'll try that and try to spot the problem

**Comment by JohnMaguire** [comment] 2015-11-01 21:33
Taking a quick look at how you're detecting conflicts, I'm wondering if maybe the patch file isn't being updated.

As far as I can tell the only place SavePatch is called is when creating a new pull request or updating one: https://github.com/gogits/gogs/search?utf8=%E2%9C%93&q=SavePatch

Opening the first file, it seems that there is also an UpdatePatch which calls SavePatch(). But the only place that is called is if the admin reopens a closed pull request: https://github.com/gogits/gogs/blob/50058b3c6d05d38d98cddeba2ad353f8138f1234/routers/repo/issue.go#L804

So it's possible that the hook to check if it's merge-able occurs every time, but its using an outdated patch.

**Comment by Unknwon** [comment] 2015-11-02 02:13
@JohnMaguire GitHub search is somewhat isn't up-to-date: https://github.com/gogits/gogs/blob/50058b3c6d05d38d98cddeba2ad353f8138f1234/models/pull.go#L415

**Comment by Unknwon** [comment] 2015-11-03 22:26
Please try out `develop` or https://try.gogs.io again!

**Comment by andreynering** [comment] 2015-11-03 23:02
@Unknwon  Great work! :tada:

Everything is working as intended: https://try.gogs.io/andreynering/prtest/pulls/1

**Comment by Unknwon** [comment] 2015-11-03 23:03
Awesome!

**Closed** 2015-11-03 23:41 UTC
Labels: bug
