### ISSUE TITLE
LDAP add and edit form are misleading

### ISSUE THREAD

**Issue by blemasle** [gogits/gogs#1124] opened 2015-03-23 14:18 UTC
Since v0.6.0, ldap authentication is broken and cannot be used for more than the first login :
* Auto registration and authentication works the first time
* The second time the user tries to login, gogs tries to recreate this user if authentication is successfull, which leads to
```
2015/03/23 13:55:00 [D] LDAP Authen OK: username
2015/03/23 13:55:00 [W] Fail to login(username) by LDAP(ldap): User already exist
```
* If auto registration is disabled, authentication fails every time, without any warning about invalid credentials in the logs

Just to be precise, I'm using the new ldap feature and mapped all the "attribute" fields under the ldap authentication section.

**Comment by Unknwon** [comment] 2015-03-23 14:25
Thanks your report!

Are those two logs are printed by Gogs or you add them yourself?

**Comment by blemasle** [comment] 2015-03-23 14:27
They're printed by gogs, I simply copy/paste the relevant output from `./gogs web`

**Comment by Unknwon** [comment] 2015-03-23 14:32
Can you see the user you're trying log in from database?

**Comment by blemasle** [comment] 2015-03-23 14:34
Can't it be from this 00653e52ee078ae76872f722f056805fb75d98af, where the return of `SearchEntry` have changed ?

I'll check right now for the user.

**Comment by Unknwon** [comment] 2015-03-23 14:36
> Can't it be from this 00653e5, where the return of SearchEntry have changed ?

Could be, but I need to verify my thought first.

**Comment by Unknwon** [comment] 2015-03-23 14:39
If user exists, based on https://github.com/gogits/gogs/blob/master/models/login.go#L178 , it should not do the create operation, and you can see from log `LDAP Authen OK: username`, so 00653e5 might work correctly.

**Comment by blemasle** [comment] 2015-03-23 14:47
`LDAP Authen OK: username` comes from the same function, before the return, see https://github.com/gogits/gogs/blob/master/modules/auth/ldap/ldap.go#L85

I can see the username in the database, with `login_type` set to `2` and `login_source` set to `1`

**Comment by Unknwon** [comment] 2015-03-23 14:48
> LDAP Authen OK: username comes from the same function, before the return, see https://github.com/gogits/gogs/blob/master/modules/auth/ldap/ldap.go#L85

Code after this line return `true` always for indicate whether user is logged in or not.

**Comment by blemasle** [comment] 2015-03-23 14:49
By that, I meant the ldap authentication does not seems to be the issue, but to me it has to with the handling of the response somehow :)

**Comment by Unknwon** [comment] 2015-03-23 14:52
I think I found the bug, `lower_user` of LDAP auto-registered user is not assigned. This field is used to check if user is existed with given username.

**Comment by blemasle** [comment] 2015-03-23 14:53
And I if leave 'username attribute' empty (the first field fullfilled is then the email), the errors now becomes

```
[D] LDAP Authen OK: username
2015/03/23 14:36:16 [W] Fail to login(username) by LDAP(ldap): E-mail already used
```

**Comment by Unknwon** [comment] 2015-03-23 14:54
I've pushed fix `develop` branch, if you're using email to sign in cannot reproduce this issue(I guess this is how how other people are doing).

**Comment by blemasle** [comment] 2015-03-23 14:57
I'm not using email, but was just playing around and try to follow what's going on. I'll try to the fix and come back to you then !

**Comment by Unknwon** [comment] 2015-03-23 14:58
@blemasle yeah, that's why you hit this bug :blush: take your time, and thanks for following up!

**Comment by blemasle** [comment] 2015-03-23 15:48
You may have fixed another bug, but I found the real cause of my issue.

When you add a new LDAP auth source their is a "auths.attributes" field which latter becomes "Username attribute" when editing that same source. Moreover, the first form miss all the new fields.

When I saw this I didn't think straight and take the "Username attribute" for a "display name attribute" (as I've already filled the attribute on which the user is bound) which results in a wrong value being filled.

Anyway, there is no real issue here appart from the difference between the add and edit source form which could mislead the end-user ;)

**Comment by Unknwon** [comment] 2015-03-23 16:05
@blemasle thanks for the feedback! 

We should fix the UI, sorry about misleading!

**Comment by blemasle** [comment] 2015-03-23 16:09
No problem :)

**Comment by Unknwon** [comment] 2015-03-24 23:04
Just push fix on `master`.

**Comment by blemasle** [comment] 2015-03-24 23:31
Great ! As you still need a feedback, I'll see if I can test it tomorrow !

**Comment by Unknwon** [comment] 2015-03-24 23:33
@blemasle no problem.

PS: release `v0.6.1` tomorrow for a critical bug fix, but we can wait one or two days after release.

**Comment by blemasle** [comment] 2015-03-24 23:54
@Unknwon unfortunately I can't get the thing to compile now and it's running late here. I'll definitly try again tomorrow with the `v0.6.1` release

**Comment by Unknwon** [comment] 2015-03-24 23:55
No problem

**Comment by blemasle** [comment] 2015-03-25 15:27
Seems all good to me !

**Comment by Unknwon** [comment] 2015-03-25 15:29
@blemasle very well! Thanks for confirmation.

**Closed** 2015-03-25 15:30 UTC
Labels: bug, ui

**Comment by buka-a4** [comment] 2015-04-10 02:25
My issue is also resolved, tnx :)
