### ISSUE TITLE
Invalid symmetric difference expression

### ISSUE THREAD

**Issue by SpudDogg** [gogits/gogs#4890] opened 2017-11-22 16:36 UTC
- Gogs version (or commit ref):  0.11.33.1119
- Git version: 2.1.4
- Operating system: Debian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist (usually found in `log/gogs.log`):
````
fatal: Invalid symmetric difference expression dd76f78ac9dbd547e0145fa906d4aae6d1f03b18...741e4b90e6a0f216aee057fbeb7fb9ba11390c00
````
## Description
After updating to the latest version, pull requests can no longer be merged in.  The web interface gives a 500 and this error:
````
"An error has occurred : exit status 128 - fatal: Invalid symmetric difference expression dd76f78ac9dbd547e0145fa906d4aae6d1f03b18...741e4b90e6a0f216aee057fbeb7fb9ba11390c00"
````

From the command line, a manual git diff shows the same:
````bash
# git diff dd76f78ac9dbd547e0145fa906d4aae6d1f03b18...741e4b90e6a0f216aee057fbeb7fb9ba11390c00
fatal: Invalid symmetric difference expression dd76f78ac9dbd547e0145fa906d4aae6d1f03b18...741e4b90e6a0f216aee057fbeb7fb9ba11390c00
````

**Comment by Unknwon** [comment] 2017-11-22 18:54
Hi, in which way you merge? "Create a merge commit" or "Rebase before merging"?

**Comment by ah-edg** [comment] 2017-11-22 18:55
copying my comment from #4883:

We also have a problem on pull requests with the new release.
Also on 0.11.33, but with gogs in a custom docker container based on debian jessie.
The data is stored in MySQL.

Gogs showed an 500-error on pull request merges in multiple repositories - but not from one repo to itself.
A rollback to 0.11.29 helped.

Maybe relevant: on the merge site, only the first radio button was shown. I understand it should look like this:
![new merge GUI](https://user-images.githubusercontent.com/2946214/32874732-0ec299f2-ca62-11e7-9853-773709518579.png)

Logs:
```
2017/11/21 21:24:48 [ERROR] [...g/context/context.go:171 ServerError()] Repo.GitRepo.CommitsCountBetween: exit status 128 - fatal: Invalid symme
tric difference expression 709f3ff102dd3945e8e7bb80b1d31e3f31dfdbb4...68af527862a00b0e08324a5700889cf9877fba27
2017/11/21 21:24:48 [TRACE] Template: status/500
```

**Comment by ah-edg** [comment] 2017-11-22 18:56
"Create a merge commit", the other radio button was not shown

**Comment by Unknwon** [comment] 2017-11-22 18:56
@ah-edg you don't see another radio button because you didn't allow in the repository setting, that's not part of this problem..

**Comment by ah-edg** [comment] 2017-11-22 18:58
Oh, ok - I didn't see it has to be explicitly activated, sorry.
Still the merge commit.

**Comment by Unknwon** [comment] 2017-11-22 18:58
@ah-edg I don't have enough info, can you tell me if the pull request is merged successfully or remain unmerged?

**Comment by ah-edg** [comment] 2017-11-22 19:00
We're back in the old version and I cannot easily roll forward, so from memory:

It was not merged. Pulling or fetching it produced the old version, looking at the PR in the web gui led to 500.

**Comment by ah-edg** [comment] 2017-11-22 19:00
but it was confirmed as sucessfully merged.

**Comment by Unknwon** [comment] 2017-11-22 19:06
@ah-edg are you pull request between two repositories?

**Comment by Unknwon** [comment] 2017-11-22 19:10
Yes, I reproduced!

**Comment by Unknwon** [comment] 2017-11-22 19:16
OK it is a regression, fix has been pushed to `master`.

Just a note:

For PRs between different repositories, the changes was **NOT** pushed to base repository, also, changes **were NOT lost**, your data is safe! Those changes just merged to the base branch of original repository (fork repository).

For example, if a PR is between `user1/branch1` and `user2/branch2`, the changes are made to `user2/branch1`.

Since this problem is critical, I'll made a quick release today.

**Comment by Unknwon** [comment] 2017-11-22 19:39
Thanks for the feedback, should be fixed now :D

**Closed by Unknwon** 2017-11-22 19:39 UTC
Labels: kind/bug, status/needs feedback

**Comment by athoik** [comment] 2017-11-23 07:19
Thank you @Unknwon! I was about to create a ticket for that issue, but the great community of gogs already did! 

Well done!

**Comment by KevinJue** [comment] 2018-03-16 16:38
@Unknwon 
It seem we reproduce the problem.
using "Rebase before merging" the pull request look like correctly done in interface but any modification is done on Branch.
The PR is closed and the modification are not apply.

I try to watch log, but nothing strange appear in gogs.log, serv.log ... 

any idea ?

**Comment by Unknwon** [comment] 2018-03-20 01:06
@KevinJue I don't think the issue you encounter relates to the OP. I remember there is an issue already reported this issue, that rebase succeed but no commits merged to base branch.

**Comment by KevinJue** [comment] 2018-03-20 09:21
@Unknwon 
I search a little bit more an issue that can match with the problem and it seem to be #5051. 
Sorry for disturbing this one
