### ISSUE TITLE
Source file be recognized as a BIN

### ISSUE THREAD

**Issue by hchungi** [gogits/gogs#2486] opened 2016-01-27 08:07 UTC
I have a repository which contains many C# source files(.cs). When I tried to modify them then push to Gogs, some files cannot be recognized as a source file(.cs) and show diff content. They all become a BIN.

I really have no idea, because not all *.cs like that. 

Hope you can help me out!

Thanks.

**Comment by Unknwon** [comment] 2016-01-27 09:17
Thanks your feedback!

Can you reproduce this on https://try.gogs.io?

**Comment by hchungi** [comment] 2016-01-27 09:57
Here is my commits
https://try.gogs.io/hsuci/exceptionpush/commits/master

As you can see, I can't preview changes unless I click **View File**, because the source file be recognized as a BIN.

**Comment by Unknwon** [comment] 2016-01-27 10:03
Thanks, got it!

**Comment by linquize** [comment] 2016-01-27 11:26
Do you have BOM in the file?

**Comment by hchungi** [comment] 2016-01-27 16:06
I just checked the file, it seems has BOM with **Unicode / UTF-16LE** (0xff, 0xfe).  
Visual Studio can edit and compiler the file properly.  
Anyway, I am not sure whether this is a bug or not?

**Comment by Unknwon** [comment] 2016-01-27 17:35
I'll pull your demo files and do some tests to see where is the problem.

**Comment by hchungi** [comment] 2016-01-28 02:47
got it, thanks anyway!

**Comment by nawa** [comment] 2016-05-15 20:50
Git identified this file as binary because of UTF-16 encoding
You can see it on your repo trying `git show b748e9086515b69c62f202cdb80efe561c25dde8`
I think that every git hosting like github that use git command line underhood will have the same problem

**Comment by nawa** [comment] 2016-05-15 20:52
@Unknwon I think that this issue could be closed as not a bug

**Comment by Unknwon** [comment] 2016-05-24 02:08
@nawa thanks for the info!

ping @hchungi

**Closed** 2016-07-20 06:08 UTC
Labels: status/needs feedback
