### ISSUE TITLE
Fail to initialize ORM after Upgrade

### ISSUE THREAD

**Issue by Vorlif** [gogits/gogs#2819] opened 2016-03-13 09:19 UTC
## System Information
- Gogs version: 0.9.8.0312
- Git version: 2.1.4
- Operating system: Debian 8.3
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes
  - [ ] No
  - [x] Not relevant

### gogs.log
```
2016/03/13 10:07:46 [I] Migration: convert date to unix timestamp
2016/03/13 10:07:46 [I] Converting table: action
2016/03/13 10:07:46 [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: update bean [table: action, id: 1]: pq: Column „created_unix“ from relation „action“ does not exist
```

## Description
After Upgrade from Version 0.9.1 to 0.9.8 I get the error described.

**Comment by saboya** [comment] 2016-03-13 18:06
Probably related to cb1eadc2768ea5ffb2967eb4262e96730c3f9ba5

**Comment by Unknwon** [comment] 2016-03-13 19:17
Have you updated all deps?

**Comment by Vorlif** [comment] 2016-03-13 20:43
I have use [Gogs Docs](https://gogs.io/docs/upgrade/upgrade_from_source) to upgrade gogs. How can i update the deps?

**Comment by Unknwon** [comment] 2016-03-13 20:50
If you have used `go get -u github.com/gogits/gogs`, should be updated.

What is your PostgreSQL version?

**Comment by Vorlif** [comment] 2016-03-13 21:08
Version: 9.4.6

**Comment by Unknwon** [comment] 2016-03-13 21:14
@Vorlif Do you mind upgrade to 9.5.0? I have tested with this version without error, no pro on db so not sure if this could be the problem.

**Comment by Vorlif** [comment] 2016-03-13 21:44
I'm sorry but an update is not possible. It's a productiv system for other services. 

I am also not a db pro. But I can not find a `_unix` inside my db.

From my currently db backup:
```
cat gogs_13-03-2016 | grep updated
COPY access_token (id, uid, name, sha1, created, updated) FROM stdin;
COPY deploy_key (id, key_id, repo_id, name, fingerprint, created, updated) FROM stdin;
COPY issue (id, repo_id, index, name, poster_id, milestone_id, assignee_id, is_pull, is_closed, content, priority, num_comments, deadline, created, updated) FROM stdin;
COPY login_source (id, type, name, is_actived, cfg, created, updated) FROM stdin;
COPY mirror (id, repo_id, "interval", updated, next_update) FROM stdin;
COPY public_key (id, owner_id, name, fingerprint, content, mode, type, created, updated) FROM stdin;
COPY repository (id, owner_id, lower_name, name, description, website, default_branch, num_watches, num_stars, num_forks, num_issues, num_closed_issues, num_pulls, num_closed_pulls, num_milestones, num_closed_milestones, is_private, is_bare, is_mirror, enable_wiki, enable_external_wiki, external_wiki_url, enable_issues, enable_external_tracker, external_tracker_format, enable_pulls, is_fork, fork_id, created, updated) FROM stdin;
COPY "user" (id, lower_name, name, full_name, email, passwd, login_type, login_source, login_name, type, location, website, rands, salt, created, updated, last_repo_visibility, max_repo_creation, is_active, is_admin, allow_git_hook, allow_import_local, avatar, avatar_email, use_custom_avatar, num_followers, num_following, num_stars, num_repos, description, num_teams, num_members) FROM stdin;
COPY webhook (id, repo_id, org_id, url, content_type, secret, events, is_ssl, is_active, hook_task_type, meta, last_status, created, updated) FROM stdin;
```

Maybe a issue with the migrations? But why I'm the only one?

**Comment by Unknwon** [comment] 2016-03-13 21:46
Of course you can't find because it's a migration. which should create this new column for you.

cc @lunny can you help look into XORM migration problem?

**Comment by Vorlif** [comment] 2016-03-13 21:51
Okay. I understand.

**Comment by Unknwon** [comment] 2016-03-13 22:00
I downloaded 9.4.6 and tested without error... there is some information missing...

**Comment by syscrusher** [comment] 2016-03-13 22:12
I can reproduce on Postgres 9.5, using the same Gogs/Git/Debian versions as @Vorlif.
Occurs after upgrading from source. Source was fetched with `go get -u`.

**Comment by syscrusher** [comment] 2016-03-13 22:46
The error is returned from [migrations.go#L668](https://github.com/gogits/gogs/blob/master/models/migrations/migrations.go#L668). I don't know much about xorm or gogs architecture, but am familiar with go and psotgres so I will keep looking around.

**Comment by Unknwon** [comment] 2016-03-13 22:47
The real failure is here: https://github.com/gogits/gogs/blob/master/models/migrations/migrations.go#L618

This call should have created the new column.

**Comment by Unknwon** [comment] 2016-03-14 02:26
Can you guys update `go get -u .` again and try? XORM just pushed a fix.

**Comment by syscrusher** [comment] 2016-03-14 02:31
Fixed here. Much appreciated, keep up the hard work.

**Comment by Vorlif** [comment] 2016-03-14 15:19
Here also fixed. Thanks for the hard work and quick response.
Issue can be closed from my side.

**Comment by Unknwon** [comment] 2016-03-14 20:33
Thanks for the confirmation!

**Closed by Unknwon** 2016-03-14 20:33 UTC
Labels: status/needs feedback, status/needs reproduce

**Comment by mysiar** [comment] 2016-06-27 09:38
I had similar error message on my QNAP NAS with Gogs 0.9.13.
The reason was that my MySQL db serwer was not running
