### ISSUE TITLE
unknown key algorithm: <nil> for ed25519 SSH keys

### ISSUE THREAD

**Issue by mhartkorn** [gogits/gogs#2435] opened 2016-01-18 21:15 UTC
I am running Gogs version 0.8.22.0115 in Docker with the official image tagged `latest`.

When I try to add a new ed25519 SSH key to my account, it shows the following error message on the top of the page:

> Sorry, we're not able to verify your SSH key: ParsePublicKey: ssh: unknown key algorithm: \<nil>

The key is definitively valid because it is the same key I use to commit to GitHub. RSA keys are working fine.

**Comment by qbit** [comment] 2016-01-19 00:08
Looks like support upstream hasn't landed yet: https://github.com/golang/go/issues/8581

Hopefully it hits soon!

**Comment by mhartkorn** [comment] 2016-01-19 15:01
It seems like that this is not a problem of Go or Gogs. I tried to add an ed25519 key on try.gogs.io and it was successful. Pushing and pulling is also no problem.

Does anybody have an idea what the difference between try.gogs.io and the Docker image is?

**Comment by qbit** [comment] 2016-01-19 16:02
Not sure, my gogs instance shows newer than try.gogs: Gogs Version: 0.8.22.0115

**Comment by mhartkorn** [comment] 2016-01-19 20:37
The issue indeed lies within the go package `golang.org/x/crypto/ssh` as @qbit said. 7ef9a05 made the SSH validation function use `golang.org/x/crypto/ssh` which does not support ed25519 keys, yet.

I will close this issue because #2179 already has some comments about the commit.

**Comment by FSMaxB** [comment] 2016-01-20 16:08
So when is this going to be fixed? Is there some plan to use another way to validate ssh keys before this is fixed upstream? Are there any efforts upstream to fix this? Because the current Situation really sucks (I have to generate RSA keys just to be able to use Gogs).

**Comment by mhartkorn** [comment] 2016-01-20 16:25
I don't think that ed25519 will be in `golang.org/x/crypto/ssh` soon. It might never be integrated because upstream says that they wait for a CFRG decision which might not use ed25519 but something similar.

See: https://github.com/golang/go/issues/8581#issuecomment-154903261

**Comment by FSMaxB** [comment] 2016-01-20 16:29
If this isn't fixed upstream, gogs should use a different method for key validation.

If I'm understanding this correctly, this is only a validation to make sure that everything went right when copy pasting the keys in. The actual crypto is still done by OpenSSH (or whatever is installed on the server), right? And OpenSSH does have proper support for Ed25519.

**Comment by qbit** [comment] 2016-01-20 16:33
In the mean time, you can become your git user on your gogs instance and manually add the key to ~/.ssh/authorized_keys, make sure you copy an existing line to get all the command stuff in there.

If you really need to have the key listed in the "Keys" section of the web site, add it to the `public_key` table in gogs.db

**Comment by FSMaxB** [comment] 2016-01-20 16:38
@qbit Thanks for the workaround.

**Comment by mhartkorn** [comment] 2016-01-26 15:05
The newly released [RFC 7748](https://www.rfc-editor.org/rfc/rfc7748.txt) defines Curve25519, so it will most likely be implemented in `golang.org/x/crypto/ssh` within a reasonable time span.

**Comment by Unknwon** [comment] 2016-01-26 16:31
We may use add back the old approach to support two ways of validations under your configuration. So people who do not have problem with old approach could config to use it. This should work?

**Comment by FSMaxB** [comment] 2016-01-26 16:35
This would be a temporary fix at least. But in the long term, all the keys supported by OpenSSH should be supported by Gogs in the default configuration.

**Comment by Unknwon** [comment] 2016-01-26 16:36
@FSMaxB OK, agreed.

**Comment by PokeAcer549** [comment] 2016-02-13 00:17
I got my ED25519 key added thanks to this :stuck_out_tongue: 
You need to add a regular RSA key so that the line is added to gogs' authorized keys, then go into said file and edit the key. If you want to change the key in the keys area, as stated before, you must edit it in the keys line (SQLite editor if a .db file, or some MySQL editor otherwise).

If you don't want to add a key, use this SQL query (SQLite editor supports SQL queries if SQLite):
```sql
INSERT INTO `public_key` (`id`, `owner_id`, `name`, `fingerprint`, `content`, `mode`, `type`, `created`, `updated`) VALUES (KEYID, USERID, 'KEYNAME', 'KEYFINGERPRINT', 'SSHKEY', 2, 1, '2016-02-13 01:04:42', '2016-02-13 01:07:43');
```
Where KEYID = the ID for the key (check if you have any with that ID or you'll overwrite that person's key!), USERID is your ID (Admin Panel can inform you), KEYNAME is the name of the key, which can contain spaces, KEYFINGERPRINT is the fingerprint, and SSHKEY for the key. The date can also be changed if needed. Then, in the Gogs homedir (/home/gogs if installed via package), go to .ssh and open authorized_keys and add this in:
```bash
command="/opt/gogs/gogs serv key-KEYID --config='/etc/gogs/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty SSHKEY"
```
KEYID and SSHKEY are the only things needed. Ensure your OpenSSL is the latest.

**Comment by Unknwon** [comment] 2016-02-13 00:20
@PokeAcer549 Good hack...!

**Comment by PokeAcer549** [comment] 2016-02-13 00:21
Ty,  I might as well share it as I got it working.

**Comment by Unknwon** [comment] 2016-02-28 01:53
Now this type of key should be supported when you're not using builtin SSH server, please help test.

**Comment by Unknwon** [comment] 2016-02-28 02:05
This post may help as well: https://discuss.gogs.io/t/how-to-config-ssh-settings/34

**Comment by FSMaxB** [comment] 2016-02-29 17:19
I currently don't get the development version of gogs to work. I'm using the Archlinux AUR package gogs-git-dev, I'll take a closer look once I find the time.

**Comment by misuzu** [comment] 2016-03-02 12:16
Works for me in develop branch.

**Comment by mhartkorn** [comment] 2016-03-02 20:33
@FSMaxB Update the dependencies with `go get -v -u ./...` first.

**Comment by FSMaxB** [comment] 2016-03-02 23:39
@mhartkorn: That isn't the issue I'll probably have to write my own package because the original doesn't work. But misuzu already confirmed that it works, so I guess I'm fine anyway.

**Comment by Unknwon** [comment] 2016-03-03 20:17
OK, close as fixed.

**Closed by Unknwon** 2016-03-03 20:17 UTC
Labels: kind/bug, status/needs feedback
