### ISSUE TITLE
Explore doesn't include private but accessible repos

### ISSUE THREAD

**Issue by Dortamur** [gogits/gogs#3088] opened 2016-05-13 03:55 UTC
Currently, there is no easy way to find a repo by searching, when there are many private repos in organisations. In our setup we heavily use Organisations and Teams where 99% of the Repos are Private, and none of the Private repos in an Organisation show up under Explore, either browsing or searching.

It would be really useful to include _all_ repos that a User has access to, under Explore.

By extension, the API /api/v1/repos/search should also return all accessible Repos, including Private repos in an Organisation that the User has access to via a Team.

**Comment by de-live-gdev** [comment] 2016-05-13 16:50
My *Explore -> Repositories* is also empty, all repos on my server are set to private. Nothing shows up, doesn't matter if I'm logged in  as admin, or not, got access to the organization, repo owner, member, etc..

**Comment by bkcsoft** [comment] 2016-05-13 16:58
I can have at look at this

**Comment by bkcsoft** [comment] 2016-05-17 13:14
Which version of Gogs are you running ? I can't reproduce this :sweat:

**Comment by de-live-gdev** [comment] 2016-05-17 14:37
0.9.27.0512

![unbenannt](https://cloud.githubusercontent.com/assets/6735650/15326252/970304e2-1c4d-11e6-9f1f-ddafc59e1140.png)

**Comment by Dortamur** [comment] 2016-05-18 03:06
Mine is 0.9.15.0323.

If I go into Settings for a repo owned by an Organisation, and change Visibility to Not Private, it shows up in Explore. Changing it back to Private, and it no longer shows in Explore. I am in a Team with access to the Repo - and I'm also Admin.

I've also just tested with Repos owned by myself, and the same occurs. Private, and it's not shown in Explore. Not Private, and it is shown.

**Comment by Dortamur** [comment] 2016-05-18 03:33
I've now upgraded to 0.9.25.0506 (using the .deb packages from packager.io), and Explore is still not showing Private-but-allowed repos.

**Comment by bkcsoft** [comment] 2016-05-18 11:28
Nvm, I can reproduce it. Working on it :D

**Comment by maxleistner** [comment] 2017-01-10 12:31
any progress on this? @bkcsoft

**Comment by master-d** [comment] 2017-03-06 21:32
@Unknwon would you still be willing to examine a pull request for this issue?  I noticed you assigned it to yourself on 7/2/2016 but I was curious and wanted to see if I could fix this issue locally.

**Comment by Unknwon** [comment] 2017-03-06 22:12
@master-d yes you can try, it is somewhat a complicated query.

Just keep in mind there is no guarantee that any proposed PR will be merged.

**Comment by master-d** [comment] 2017-03-06 22:26
no worries I just wanted to check to see if you were actively working on it and the "Contributing-code" wiki had mentioned that one should ask before contributing.  I'll try to familiarize myself with the database and go from there.

**Comment by master-d** [comment] 2017-03-10 21:28
I made a pull request for this issue.  This is my first one on github so I hope I didn't screw it up too badly
https://github.com/gogits/gogs/pull/4273

**Comment by Unknwon** [comment] 2017-03-13 04:54
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by hochhaus** [comment] 2017-03-13 06:27
I built 96ae0129ef4db2bb5c7fc3bdcbc128700f116ac1 on the develop branch and unfortunately when logged in do not see my private repos.

To be clear, the account I am logged in with is an administrator who is explicitly listed as a contributor with write access to private repo. Still the private repo is not visible on `/explore/repos`.

**Comment by Unknwon** [comment] 2017-03-13 06:31
@hochhaus currently, you need search, private repos are not listed with empty query string.

**Comment by hochhaus** [comment] 2017-03-13 06:33
@Unknwon Thanks. I just tested and can confirm that searching does show the private repos in my build at https://github.com/gogits/gogs/commit/96ae0129ef4db2bb5c7fc3bdcbc128700f116ac1.

**Comment by hochhaus** [comment] 2017-03-13 06:38
@Unknwon Ijust noticed that if you do a search for a repo when not logged in a 500 is returned.

https://try.gogs.io/explore/repos?q=test (make sure that you are not logged in)

**Comment by Unknwon** [comment] 2017-03-13 06:41
@hochhaus thanks, fixed.

**Comment by hochhaus** [comment] 2017-03-13 06:42
Thanks. Confirmed that your fix works as intended.

**Comment by master-d** [comment] 2017-03-13 15:01
sorry about that.  Can I ask what caused the 500 error when performing a search while not logged in?  I get the same behavior on my local branch.  Is it attempting to set the int64 "UserID" variable to a null value which isn't allowed?

**Comment by Unknwon** [comment] 2017-03-13 17:55
@master-d 

>Is it attempting to set the int64 "UserID" variable to a null value which isn't allowed?

Yes, you can look at my fix patch, is very simple fix, just always need to keep in mind.

>Also should the search for empty string return all repositories the user has access to? I should be able to add that in without too much problem

Yes, should be very similar in terms of SQL, you can try that.

**Comment by master-d** [comment] 2017-03-13 21:01
Ok.  I noticed a search occurs immediately when the "Explore" page is loaded and it seems to be returning results for GetRecentUpdatedRepositories in repo.go on page load.  Should that remain the same or should I load all of the accessible repositories on page load and run the same query if the user enters an empty string in the search box?

**Comment by Unknwon** [comment] 2017-03-13 21:56
@master-d You should use the same function but include same functionality as search (include private but accessible repo).

**Comment by master-d** [comment] 2017-03-15 05:02
PR #4289 should handle empty string searching on page load and manually

**Comment by Unknwon** [comment] 2017-03-17 23:19
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by hochhaus** [comment] 2017-03-23 05:23
@Unknwon Thanks. I tested from the `develop`branch and I can confirm that this patch works as intended (both for authenticated and unauthenticated users).

**Closed** 2017-03-23 15:32 UTC
Labels: kind/enhancement, status/needs feedback
