### ISSUE TITLE
REQUIRE_SIGNIN_VIEW true but git clone still succeeds for empty/null username.

### ISSUE THREAD

**Issue by spawnflagger** [gogits/gogs#3626] opened 2016-09-08 19:52 UTC
- Gogs version (or commit ref): 0.9.30.0601
- Git version: 2.6.4
- Operating system: OpenBSD 5.9 (server) ; FreeBSD 10.2 (client)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes 
  - [x] No _(cannot change REQUIRE_SIGNIN_VIEW there)_
  - [ ] Not relevant
- Log gist:
   n/a _(relevant behavior does not show up as failure in log)_

## Description
We have installed and used GoGS for a few months, just noticed this scenario/bug yesterday.
It is reverse-proxy through Nginx for HTTPS support, also using LDAP auth.
REQUIRE_SIGNIN_VIEW = true
Web UI behaves normally, git via SSH behaves normally.
git via HTTPS behaves normally _if repo is marked as private_.

Bug is when repo is not marked as private, git will prompt for username and password, but if you just hit enter twice, the request goes through.

**Example session**:
> [me@client ~/gittest]$ `git clone https://server/git/gogsuser/examplerepo.git`
> Cloning into 'examplerepo'...
> Username for 'https://server':

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_(press return)_
> Password for 'https://server':

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_(press return)_
> remote: Counting objects: 225, done.
> remote: Compressing objects: 100% (220/220), done.
> remote: Total 225 (delta 102), reused 0 (delta 0)
> Receiving objects: 100% (225/225), 651.65 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (102/102), done.
> Checking connectivity... done.

**Expected behavior**: empty/null user should get denied access.

Bug exists even with LDAP auth turned off, and when trying from localhost:3000, bypassing nginx.

looked through the source a bit...
gogs/models/**login.go**:UserSignIn() calls `x.Get(u)` before checking length of uname.
(whereas **user.go**:GetUserByName() does check name for 0 length)

...

**Comment by bkcsoft** [comment] 2016-09-08 20:33
Duplicate of #3110.
When reporting bugs, always reproduce on (at least) latest release and (if able) try.gogs.io

**Closed by bkcsoft** 2016-09-08 20:33 UTC
