### ISSUE TITLE
Commit shows local git user and not authenticated

### ISSUE THREAD

**Issue by km4efp** [gogits/gogs#2382] opened 2016-01-11 18:22 UTC
The commits pushed via http show up as the local git config user and not the authenticated user on the gogs server.

**Comment by Unknwon** [comment] 2016-01-14 06:26
Thanks your feedback!

But I don't understand the problem?

**Comment by km4efp** [comment] 2016-01-15 22:58
Commits show up on webui as root(local git config) instead of the remote user being authenticated via http

**Comment by km4efp** [comment] 2016-01-16 00:09
When you push it asks you to authenticate with a user/pass and that user being authenticated isnt displayed on gogs but instead the git default user on the client machine.

**Comment by bkcsoft** [comment] 2016-01-16 06:02
I can't reproduce this on `master`... @km4efp can you take a screenshot where this is shown?

**Comment by km4efp** [comment] 2016-01-17 02:50
![screenshot_2016-01-16-21-49-16](https://cloud.githubusercontent.com/assets/9044667/12375661/1b3c3214-bc9b-11e5-9412-73d843fc20a3.png)

**Comment by km4efp** [comment] 2016-01-17 02:52
All commits are via http no ssh.
I dont remember setting up a local git profile to get my name to show up on commits for github.  I thought it just used the username you were authenticating as when pushing the commit.

Also being able to edit files from the webui would be great.

**Comment by Unknwon** [comment] 2016-01-25 18:03
@km4efp thanks your info!

Can you post results of command `git log -10` here?

**Comment by km4efp** [comment] 2016-01-30 00:09
From the client machine pushing the commit or from gogs server?

**Comment by Unknwon** [comment] 2016-01-30 00:11
From the client machine pushing the commit

**Comment by Unknwon** [comment] 2016-02-07 02:24
ping @km4efp

**Comment by km4efp** [comment] 2016-02-16 01:40
commit 4e86f79a66dd71e3574d84c1912d60ff03edb50b
Author: root <root@localhost.localdomain>
Date:   Thu Jan 7 03:57:45 2016 -0500

    updating readme
    
    updating readme

commit cdf60bcd53435c438dadd81f27d901959b5addf4
Author: root <root@localhost.localdomain>
Date:   Thu Jan 7 01:20:48 2016 -0500

    Updating readme
    
    Updating readme

commit 58cd3bf013fdd75fccfbcb7500fa509e8d10d8fa
Author: root <root@localhost.localdomain>
Date:   Thu Jan 7 01:19:30 2016 -0500

    Update readme
    
    Updating readme

**Comment by km4efp** [comment] 2016-02-16 01:41
I am authenticating as sploit using http but root appears since its the local git user.

I would prefer to have the authenticated user show when posting.

I believe thats how github does it.

**Comment by Unknwon** [comment] 2016-02-16 01:48
You committed as `root`, that is the client side problem. Please check your local Git settings.

**Comment by km4efp** [comment] 2016-02-16 22:44
Can you add a toggle option to choose to show the authenticated user if one wishes?

**Comment by Unknwon** [comment] 2016-02-17 00:03
It is not about authenticated user, Git does not care who authenticated the push, but who did the committment.

**Comment by Unknwon** [comment] 2016-02-17 00:07
The only possible to link them together is use the same email address.

**Comment by Unknwon** [comment] 2016-02-20 22:37
ping @km4efp

**Comment by Unknwon** [comment] 2016-02-28 18:05
Close due to lack of feedback.

You can continue discussion on https://discuss.gogs.io/.

**Closed by Unknwon** 2016-02-28 18:05 UTC
Labels: status/needs feedback
