### ISSUE TITLE
New user cannot be created with LDAP authentication in v0.9.97

### ISSUE THREAD

**Issue by velislav** [gogits/gogs#3648] opened 2016-09-14 10:52 UTC
I recently upgraded gogs from version 0.8.0 to version 0.9.97. My authentication type is LDAP (via BindDN).
In 0.8.0 an existing user in the LDAP was created in gogs by just login in gogs web interface with sAMAccountName. However this is not possible in 0.9.97.

Immediately after unsuccessful login (user create) in gogs version 0.9.97:

1. The browser headers are:
Request URL:http://10.0.0.1:3000/user/login
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:10.0.0.1:3000

2. The logs are:
[xorm] [info]  2016/09/14 13:13:17.073501 [sql] SELECT "id", "lower_name", "name", "full_name", "email", "passwd", "login_type", "login_source", "login_name", "type", "location", "website", "rands", "salt", "created_unix", "updated_unix", "last_repo_visibility", "max_repo_creation", "is_active", "is_admin", "allow_git_hook", "allow_import_local", "prohibit_login", "avatar", "avatar_email", "use_custom_avatar", "num_followers", "num_following", "num_stars", "num_repos", "description", "num_teams", "num_members" FROM "user" WHERE "lower_name" = $1 LIMIT 1 [args] [firstname.lastname]
[xorm] [info]  2016/09/14 13:13:17.074493 [sql] SELECT "id", "type", "name", "is_actived", "cfg", "created_unix", "updated_unix" FROM "login_source" WHERE "is_actived" = $1 [args] [true]

**Comment by bkcsoft** [comment] 2016-09-14 12:18
Closed as duplicate of #3578

**Closed** 2016-09-23 08:22 UTC
