### ISSUE TITLE
Issues API not marking issues as closed

### ISSUE THREAD

**Issue by deanpcmad** [gogits/gogs#3240] opened 2016-07-06 17:10 UTC
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.9.0
- Operating system: Server is Ubuntu. Client is Mac
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I'm trying to write a script to convert my GitLab issues to Gogs but the Gogs API isn't setting issues as closed when I have the `closed` parameter set to `true`. It also doesn't work if I use the `state` param and set that to `closed`.

Any ideas?

**Comment by deanpcmad** [comment] 2016-07-06 17:13
After further testing it looks like the Issues are marked as closed if I set `closed` to `true` when creating the issues. The API doesn't recognise the `closed` param when editing the issue though

**Comment by deanpcmad** [comment] 2016-07-06 18:16
Another update. It works on the current version on try.gogs.io but not on version 0.9.13.0318

**Comment by deanpcmad** [comment] 2016-07-06 18:26
When will a new version of Gogs be released? The last version was released in March...

**Comment by Unknwon** [comment] 2016-07-08 03:47
Not sure exactly... If this is not a bug exist in latest `master`, I'm closing this...

**Closed by Unknwon** 2016-07-08 03:47 UTC
