### ISSUE TITLE
Admin users cannot see organisations private repositories

### ISSUE THREAD

**Issue by xor-gate** [gogits/gogs#2732] opened 2016-03-02 13:54 UTC
- Gogs version: 0.8.43.0223
- Operating system: Debian Linux 8 amd64
- Database:
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite

## Description

As a Admin user I cannot see the private repositories on the organisation page. When managing teams with repository access the autocomplete is probably also broken due to non-visible private repositories.

To reproduce probably:
* Create organisation
* Create private repos in organisation
* Dont add Admin user to any team
* As admin user browse to the organisation landing page
* See the organisation page is empty
* When adding the Admin user to the Owners it is still only able to view the Owner Team added repositories
* When adding "all" repositories of the organisation into the Owner Team it is visible.

Together with this, the Owner team should see all repositories in the Organisation or am I wrong?
Probably I should create a seperate issue for that.

When something is not clear or reproducable. Please ask.

**Comment by neolit123** [comment] 2016-03-02 15:05
hello,

```
Create organisation
Create private repos in organisation
Dont add Admin user to any team
As admin user browse to the organisation landing page
See the organisation page is empty
```

i can confirm the above; haven't tried the rest.
perhaps the admin user should be able to view all repositories regardless of the "private" flag.

**Comment by xor-gate** [comment] 2016-03-02 15:07
Yeah you are right about:

> perhaps the admin user should be able to view all repositories regardless of the "private" flag.

**Comment by Unknwon** [comment] 2016-03-02 15:27
Thanks your feedback!

Can you make a example organization on https://try.gogs.io?

**Comment by xor-gate** [comment] 2016-03-02 17:49
@Unknwon I have created:

* Organisation `1337org`
* Private repo `1337privaterepo`
* Public repo `1337publicrepo`

See https://try.gogs.io/1337org/

**Comment by Unknwon** [comment] 2016-03-02 17:55
@xor-gate thanks! As admin, I can navigate to the private repository through admin panel, but yeah, it should be a display problem. Thanks!

**Comment by xor-gate** [comment] 2016-03-02 17:56
You are right about them displaying/showing up under the admin panel. But having them not displayed in the view of the organisation is a bit odd when I first noticed.

**Comment by mhartkorn** [comment] 2016-03-04 20:34
Seems to be working with `master` now.

**Comment by Unknwon** [comment] 2016-03-04 20:42
@mhartkorn really?... I don't fix it at all...

**Comment by mhartkorn** [comment] 2016-03-04 21:10
Funny. I checked out the latest Docker container and compiled from source to make sure. I mean, it's working for me at the moment. The corresponding SQL query for getting the repos from organizations also changed which I explicitly checked before updating. Can someone else test it with the latest `master`, please?

**Comment by Unknwon** [comment] 2016-03-04 21:12
@mhartkorn just to clarify, this issue is about site admin, not organization admin.

**Comment by mhartkorn** [comment] 2016-03-04 21:15
Oh. Sorry, I mixed up 2 issues. :(

**Comment by Unknwon** [comment] 2016-03-04 21:15
:joy:

**Comment by Rukenshia** [comment] 2016-03-08 06:51
I'll try to come up with a PR for the issue. Going to have to dig into the whole code to understand it first, though.

**Comment by Unknwon** [comment] 2016-03-10 04:22
This is claimed to be fixed by merging https://github.com/gogits/gogs/pull/2785.

**Closed** 2016-03-10 07:53 UTC
Labels: kind/bug, status/needs feedback
