### ISSUE TITLE
gogs issues can't show in right place

### ISSUE THREAD

**Issue by niluanxy** [gogits/gogs#3052] opened 2016-05-03 07:38 UTC
gogs issues can't show in right place,for example,i create a tema that's named <strong>temaA</strong>,and my user is aaa,now i should have two user, one is <strong>aaa</strong>, one is <strong>teamA</strong>.Then i use <strong>temaA</strong> to create a project that's named <strong>work1</strong>.After i create issues on <strong>work1</strong>,but it can't tip my user <strong>temaA</strong> or <strong>aaa</strong> to soluve this issues,even i have set to user <strong>aaa</strong>.

<img width="1174" alt="qq20160503-2 2x" src="https://cloud.githubusercontent.com/assets/7076522/14977249/074d1ef4-1145-11e6-97b1-f18168c00da1.png">

<img width="1188" alt="qq20160503-3 2x" src="https://cloud.githubusercontent.com/assets/7076522/14977319/781051e2-1145-11e6-959b-6ca988e577b2.png">

**Comment by Zeeker** [comment] 2016-05-10 15:44
If I understand you correctly, this is a duplicate of #1820 and will be realised in 0.10.0.

**Comment by Unknwon** [comment] 2016-07-02 15:26
@Zeeker has posted what needs to be said...

**Closed by Unknwon** 2016-07-02 15:26 UTC
