### ISSUE TITLE
DisableMinimumKeySizeCheck is not a field of struct type interface {}

### ISSUE THREAD

**Issue by cowai** [gogits/gogs#2416] opened 2016-01-15 12:53 UTC
template: admin/config:82:38: executing "admin/config" at <.Service.DisableMini...>: DisableMinimumKeySizeCheck is not a field of struct type interface {}

I get that when I try to enter the configuration in "latest" docker tag. If I use 0.8.10 as docker tag, it works.
I chose blank ssh port and sqlite for db. Otherwise everything totally default.

**Comment by mhartkorn** [comment] 2016-01-15 14:39
Can confirm. Seems like `DisableMinimumKeySizeCheck` is missing from the [`Service` struct in `modules/setting/setting.go`](https://github.com/gogits/gogs/blob/7ef9a055886574655d9f2be70c957bc16bf30500/modules/setting/setting.go#L445).

**Comment by focmb** [comment] 2016-01-16 23:41
Same error here.

gogs version  0.8.22.0115 on a raspberry 2

**Comment by exmex** [comment] 2016-01-17 08:24
I guess @Unknwon is currently busy with real life or other stuff. Anyway, I have a fix in my repository. So just download my fix, and apply it.

**Comment by focmb** [comment] 2016-01-17 12:26
This fix works. Thanks.

**Comment by Richard-Payne** [comment] 2016-01-18 15:12
@exmex your fix did not work for me.  I downloaded copied out my copy of setting.go, added the extra field to the Service struct as per your change and then volume linked the changed file into the correct path in my docker run script.

I have confirmed that the changed file is accessible in the running container but I still get the error message described in the OP.

The differences in config from the op are that I have non-blank ssh port and I'm using MySQL.

Any thoughts?

**Comment by exmex** [comment] 2016-01-18 15:28
Then you did not rebuild the scripts. Because the error is only related to missing that one key. If you still get the same error, then you didn't rebuild.

**Comment by focmb** [comment] 2016-01-18 15:30
I tried the same way. First I added the changes to the settings.go und retstarted the go-git-service and the error message was not gone. Then I deleted the gogs-folder and did a new git clone. After that I made the changes in the settings.go and did a go build. Now the error is gone and gogs is running fine.

**Comment by Richard-Payne** [comment] 2016-01-19 09:20
ahh, ok.  I'm slightly ignorant on Go and didn't realise that there was a build process.  Normally "script" implies run-time evaluation or, at best, JIT compilation. 

How do I build it?

**Comment by exmex** [comment] 2016-01-19 18:44
I don't know about docker but.

https://gogs.io/docs/installation/install_from_source

**Comment by onnimonni** [comment] 2016-01-22 14:05
I'm also having this issue:
```go
template: admin/config:82:38: executing "admin/config" at <.Service.DisableMini...>: DisableMinimumKeySizeCheck is not a field of struct type interface {}
```

This happens when I try to click the configuration page:
<img width="258" alt="configuration-error-gogs" src="https://cloud.githubusercontent.com/assets/5691777/12512558/c3d79e74-c121-11e5-805c-118293fa5b26.png">

URL: `localhost:3000/admin/config`
Version: 0.8.22.0115
System: Ubuntu 14.04

**Comment by Unknwon** [comment] 2016-01-26 07:00
Pushed a fix to `master`, please help test!

**Closed** 2016-01-26 07:00 UTC
Labels: bug

**Comment by mbi** [comment] 2016-01-26 08:26
Confirmed: the packages on packager.io (that were also affected by this issue) are fixed, thank you!

**Comment by Unknwon** [comment] 2016-01-26 08:30
Thanks @mbi !
