### ISSUE TITLE
Git commits shows Gogs nickname as first option

### ISSUE THREAD

**Issue by dwbbb** [gogits/gogs#1564] opened 2015-09-02 17:55 UTC
Pushing data to gogs records the system user as the commit user and not the user who authenticated against gogs.

i.e. Logged in as root but pushing as a different user would record root as the commit user, this makes it hard to validate the real identity of the person who commits the updates.

Thanks
Dave

**Comment by Unknwon** [comment] 2015-09-02 18:06
Thanks your feedback!

> Pushing data to gogs records the system user as the commit user and not the user who authenticated against gogs.

I don't quite get this part. So... push git data, the data already contains the author info, Gogs only reads it. What exactly situation are you describing?

**Comment by dwbconsulting** [comment] 2015-09-02 18:25
Within the gog's interface I have a number of updates from the user root, which is the system user I ran git push from.  Is there anyway this user could be set to the authenticated i.e. user "dwb" in the example below?

[root@localhost centos]# git push
Username for 'https://hostname': dwb
Password for 'https://dwb@hostname': 

Thanks for a great product
Dave

**Comment by Unknwon** [comment] 2015-09-02 18:28
What is the remote address for your `git push`?

**Comment by Unknwon** [comment] 2015-09-02 18:29
I'm a bit confusing... I think you're doing something wrong..

**Comment by dwbconsulting** [comment] 2015-09-02 19:38
The commit records the Author "user.name" and that author is uploaded to gogs and not aligned with the authenticated user who pushed it, so its hard to see who carried out the commit if the "user.name" is incorrect, my request is to align the commit with the authenticated user not the Author in the initial commit.  But I definitely could be misunderstanding the process.

Something like this.  https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

Thanks
Dave

**Comment by Unknwon** [comment] 2015-09-02 20:20
@dwbconsulting so does the GitHub solution(add another e-mail to account) fits your situation?

**Comment by dwbconsulting** [comment] 2015-09-02 21:40
I would like to have the option to see the user account (gogs login name) as the Author in gogs not the user.name which made the commit in the local repository before the push to gogs.  My number one issue is that I am unable to see who made the push because the user.name can be anything.

Thanks

**Comment by Unknwon** [comment] 2015-09-02 21:42
> My number one issue is that I am unable to see who made the push because the user.name can be anything.

It really sounds like a completely new feature. Who pushes commits isn't really a part of Git repo in my understanding of how Git works.

**Comment by manfer** [comment] 2015-09-02 22:25
It looks like there is no consistency in gogs when showing that name. In some places it shows the username and in other places it shows the full name. I agree it is better to use always the gogs username when possible. Any one that pushes must be a user of the system so it will mandatory have a username. This would be only not true when you migrate a repository and some commits will belong to users that are not registered. In that case would be fine to show the commit author.

@Unknwon I bet you don't realize about the issue because in your case the gogs nickname and the user.name you have configured on git is the same. But a lot of people has a nickname but in the git configuration they use full name. That is common practice.

For example.
https://try.gogs.io/unknwon/gogs/commits/master
Here gogs is showing full name, the commit author full name, instead of gogs nickname.

In the dashboard the gogs nickname is always used.

I bet in all repository pages it is shown as commit author full name.

----------------------

On github for example they show github nickname if the email of the commit author (user.email configured on git) match an email of a github account.

**Comment by Unknwon** [comment] 2015-09-03 10:56
@manfer thanks your explanation, I got it now.

**Comment by cb88** [comment] 2015-09-18 14:56
Is this the same issue? I committed this as crayfield but it doesn't show it that way in the commit log only in the activity log on the dashboard it will say I "crayfield" pushed to master etc... 

![gogs_defaults_to_gogs_instead_of_crayfied_committer](https://cloud.githubusercontent.com/assets/1026000/9962432/aae11af8-5df3-11e5-9dc3-f6e17c9c6f36.PNG)

**Comment by Unknwon** [comment] 2015-09-18 14:58
@cb88 can you click on the user name? Or it's just plain text "Gogs"?

**Comment by cb88** [comment] 2015-09-18 15:01
It's just plain text.

**Comment by Unknwon** [comment] 2015-09-18 15:06
@cb88 thanks for following up!

- Does this happen to every repo?
- Can you reproduce at https://try.gogs.io ?

**Comment by cb88** [comment] 2015-09-18 15:34
Yes all of my repos.

**Comment by Unknwon** [comment] 2015-09-18 15:40
@cb88 thanks!

> Can you reproduce at https://try.gogs.io ?

1. Don't skip my comments, please. 
2. What is version of your Gogs?
3. Does all commits existed became plain text "Gogs"?

**Comment by cb88** [comment] 2015-09-18 15:40
https://try.gogs.io/crayfield/TharBeATest

Yep.. it happened there. I commited via http.

**Comment by Unknwon** [comment] 2015-09-18 15:42
@cb88 

what you get in your computer if you execute shell:

```
git config -l
```

**Comment by cb88** [comment] 2015-09-18 16:02
core.symlinks=false
core.autocrlf=false
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
pack.packsizelimit=2g
help.format=html
http.sslcainfo=/bin/curl-ca-bundle.crt
sendemail.smtpserver=/bin/msmtp.exe
diff.astextplain.textconv=astextplain
rebase.autosquash=true
user.name=Gogs
user.email=gogs@fake.local
core.quotepath=false
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hidedotfiles=dotGitOnly
remote.origin.url=http://localhost:3000/
remote.origin.fetch=+refs/heads/*:refs/r
branch.master.remote=origin
branch.master.merge=refs/heads/master
gui.wmstate=zoomed
gui.geometry=887x427+-1148+-8 513 192

**Comment by Unknwon** [comment] 2015-09-18 16:04
> user.name=Gogs
> user.email=gogs@fake.local

You have never setup your git config before, so Gogs made a fake one for you.

**Comment by cb88** [comment] 2015-09-18 16:06
I see... so even though I am pushing as crayfied it's using the username from the git config. 

I'm not sure I like that. So if I set the username in my git config to crayfield will they match up?

**Comment by Unknwon** [comment] 2015-09-18 16:08
@cb88 I'm not sure how Git works with local repo config and global config.

You should have configured your profile with `git config --global` very first time you use Git.

The reason the fake one is because Git requires to have one no matter you use it or not. So this behavior should only happen in a fresh server or linux/unix user account.

**Comment by cb88** [comment] 2015-09-18 16:43
yes, but shouldn't that only apply to local repositories? If I commit as an authenticated user... that is the what I really want in the gogs repo. As multiple people could be using this same computer etc...

**Comment by Unknwon** [comment] 2015-09-18 17:52
I'm not sure what do you exactly mean by local repository, but Gogs only setup a fake user field value but Git is the only who uses this value. If you want to argue about why Git does not use this value, Gogs can't help 😂

Also you said that the activity timeline looks OK? Can you take a screenshot because I'm confused now what is OK mean to you...

**Comment by cb88** [comment] 2015-09-18 18:21
Ok, so the key is that my git user.name and user.email must match... then gogs knows that the commit matches up with my account (there is a URL to my profile now as you can see on the test repo)

**Comment by Unknwon** [comment] 2015-09-18 18:56
To match you and your account on Gogs, the author email address must match.

However, Gogs is remote to you and in your case it just happens you start Gogs on your local machine, but you cannot expect Gogs to correct who should be the one commit the changes because it does not know what's your git config, Gogs only reads info from Git data.

**Comment by Unknwon** [comment] 2015-09-18 18:57
And I think you mixed concepts about who did the commit of changes and who pushed commits.


Overall, basically, your Git config is wrong and you should set user.name and user.email in global git config.

**Comment by Unknwon** [comment] 2017-03-23 21:46
I think this is already implemented.

**Closed by Unknwon** 2017-03-23 21:46 UTC
Labels: kind/enhancement

**Comment by IlyaBelitser** [comment] 2017-07-18 06:22
It is possible to make as on GitHub?
In a web it is possible to see a сommitter name (username or full name) if an author name (git config user.name) or an e-mail (git config user.email) disperses from a сommitter namer (full name) and a сommiter e-mail.
As a result it was possible to see from under what account it is made commit.

![2](https://user-images.githubusercontent.com/1478002/28302416-5513d4ca-6bb7-11e7-8db0-ea51a7d27ad5.PNG)
