### ISSUE TITLE
Add Team Repository error in SQLite3

### ISSUE THREAD

**Issue by CaiCQ** [gogits/gogs#739] opened 2014-12-13 00:52 UTC
[teams.go:141 TeamsRepoAction()] [E] Action(add): Team does not exist

**Comment by phsmit** [comment] 2015-01-20 21:43
I am also reproducing this problem at the moment.

Go 1.4, sqlite. I am really at a loss, because when I execute the queries in xorm.log everything seems to be going ok.

This is a test instance, so I'm happy to send you any files/logs that might be helpful

**Comment by phsmit** [comment] 2015-01-20 21:51
I think this might be some bug with Sqlite and transactions.

In short, a session is started, team is updated, other queries are done outside the session including SELECTing the team. This somehow fails.

When the session is replaced by x, everything works. Not sure what the real solution is though. Probably not using sqlite.

**Comment by Unknwon** [comment] 2015-01-21 04:37
SQLite driver has all strange session problem...

**Comment by Unknwon** [comment] 2015-02-11 04:46
Hi @CaiCQ , thanks your great patient!

It looks like SQLite3 driver has issues with both session and independent transaction operate on same table.

I've pushed code to `dev` branch to fix this particular issue, it's possible that somewhere else with very complicated process will appear same issue again with SQLite3, but we will catch at our best!

**Comment by Unknwon** [comment] 2015-02-13 20:33
As new mirror release `v0.5.13` is going to release, and this issue is labeled as **feedback needed**, so close it for **assumed resolved**, feel free to reopen this if you want to continue discussing. :beer:

**Closed by Unknwon** 2015-02-13 20:33 UTC
Labels: bug, feedback needed, third-party
