### ISSUE TITLE
Large repo push http  : consumption of ram

### ISSUE THREAD

**Issue by Timetopretend** [gogits/gogs#636] opened 2014-11-19 18:43 UTC
I tried to push a large repository via http. Everything goes well until the transfer is finished eating ram becomes important (Gogs). It's a shame Gogs is so light yet in other cases. To see if this is not a technical limitation caused by the protocol, but I think it is possible to optimize.

**Comment by bkcsoft** [comment] 2016-05-26 02:50
https://github.com/gogits/gogs/blob/master/routers/repo/http.go#L362 `input, err = ioutil.ReadAll(reqBody)` is **the** line that makes Gogs use a lot of RAM when pushing/pulling over HTTP. Not sure why that block is required either to be honest @Unknwon ?

**Comment by Unknwon** [comment] 2016-05-30 10:04
@bkcsoft good point! Maybe you could try to use a continuous reader see if it works?

**Comment by bkcsoft** [comment] 2016-05-30 11:24
I can try :)

**Comment by bkcsoft** [comment] 2016-05-30 16:09
This will be a much larger task than I anticipated... Involving goroutines and channels :cry:

**Comment by Timetopretend** [comment] 2016-05-30 16:16
Excited to see movement here :)

**Comment by bkcsoft** [comment] 2016-05-31 07:35
@Unknwon is there a reason for not using the `post-recieve`-hook instead of the callback that requires that line? seems like it would be way easier to implement it correctly that way :smiley:

**Comment by Unknwon** [comment] 2016-06-01 08:12
@bkcsoft no worries, I'll take a deep look. Not sure why does it matter with `post-recieve` hook?

**Comment by Unknwon** [comment] 2016-06-01 11:22
Clean up the code for `http.go` a bit: https://github.com/gogits/gogs/commit/c041273dd334fc7a45ca6cb67ea2c2b492c4a5ed

Still working on the `input, err = ioutil.ReadAll(reqBody)` thing.

**Comment by bkcsoft** [comment] 2016-06-02 09:16
The issue is the callback is reading refname, oldsum and newsum from the http-request. This is why it needs to store it (unless you do magic), unless you use the `post-recieve`-hook which would give us this automagically :)

Also, I'm still working on this :laughing:

**Comment by Unknwon** [comment] 2016-06-02 19:19
@bkcsoft oops, hope does not break your code too much.... :sweat:

**Comment by bkcsoft** [comment] 2016-06-03 12:15
@Unknwon some breakage, easy to fix though :smiley:
and I need to refactor anyhow :laughing:

**Comment by strk** [comment] 2016-09-08 08:43
I took a look and wondering why ReadAll is needed at all.
The code is finally creating a Reader out of the buffer, why not directly using `reqBody` as the Reader ?
It is originally an `io.ReadCloser`...

**Comment by Unknwon** [comment] 2016-12-24 01:46
This is fixed by #3748.

**Comment by Unknwon** [comment] 2017-02-14 22:01
Just implemented Git hook delegation, so this problem can be ultimately solved by `post-receive` hook. Reopen as a reminder for myself.

**Comment by Unknwon** [comment] 2017-02-16 21:35
This problem should be completely solve by https://github.com/gogits/gogs/commit/d521e716dd59617dbbb637a3e8028bf4a5c6f849.

**Closed** 2017-02-18 06:37 UTC
Labels: kind/bug, status/needs feedback
