### ISSUE TITLE
Transfer of repository to organization doesn't display on org mainpage.

### ISSUE THREAD

**Issue by danshick** [gogits/gogs#950] opened 2015-02-13 19:29 UTC
Steps to reproduce:
1.) Create repository owned by an individual.
2.) Create an organization.
3.) Go to the repository's settings page and click on transfer.
4.) Enter the repository name and the name of the organization as the new owner. Enter your password and click transfer.
5.) Go to the organization's home page (http://SERVERNAME:3000/org/ORGNAME). Transferred repository will not be listed. (It is, however, available as a repo under the org's Owners team repository list)

If you add a new repo from the org's homepage, this repo is shown on that home page.

GoGits · Version: 0.5.11.0103 Beta

**Comment by Unknwon** [comment] 2015-02-13 20:14
Thanks your report! We will get on this ASAP.

**Comment by sapk** [comment] 2015-03-17 21:37
For more information, I have the same issue on a newly install. 
The repo that is transfer is show at the url : 
http://SERVERNAME:3000/org/ORGNAME/teams/owners/repositories
but not on the org page even if the count of repos is good : 
http://SERVERNAME:3000/org/ORGNAME 
and the dashboard doesn't show them in the collaborative part and the count is false.

**Comment by Unknwon** [comment] 2015-03-18 00:15
@sapk thanks for the detail!

**Comment by Unknwon** [comment] 2015-03-18 08:08
@danshick @sapk 

As I cannot reproduce on https://try.gogs.io , I remember this has been fixed in `master` branch code.

**Comment by sapk** [comment] 2015-03-19 00:46
I confirm from master that i can't reproduce. It was with binaries of v0.5.13 that it appends for me. Sorry

**Comment by Unknwon** [comment] 2015-03-19 03:52
@sapk thanks for your feedback! Let's see how things go when we release new binary.

**Comment by Unknwon** [comment] 2015-03-19 21:10
@sapk 0.6 is released.

**Comment by Unknwon** [comment] 2015-03-24 23:22
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:

**Closed by Unknwon** 2015-03-24 23:22 UTC
Labels: bug, feedback needed, reproduce needed
