### ISSUE TITLE
Pull request diff has no text

### ISSUE THREAD

**Issue by chrisbrookes** [gogits/gogs#2489] opened 2016-01-27 12:22 UTC
Gogs Version: 0.8.19.0111

When creating a pull request I don't see any text in the diff at the bottom of the page. The diff colouring appears correct however, were the text to be there.

![s1](https://cloud.githubusercontent.com/assets/1110134/12612946/3584a8a8-c4ee-11e5-9b02-63fb45350af1.png)

Whereas the actual commit diff shows:

![s2](https://cloud.githubusercontent.com/assets/1110134/12613014/b9be2c2a-c4ee-11e5-88a4-23484d8d5f88.png)

In my local gogs installation, the same problem happens after the pull request has been created and you view the *Files Changed* tab for the pull request. I've just tested this on https://try.gogs.io (which is slightly later version (0.8.23.0126) to my local install) and that shows the diff correctly **after** the pull request is created, but I can still reproduce the problem on https://try.gogs.io for the initial pull request create/Compare Changes.

**Comment by chrisbrookes** [comment] 2016-01-27 12:45
Confirmed after local upgrade that 0.8.23.0126 fixes this for the diff in *Files Changed* tab, but is still a problem in the initial pull request create (*Compare Changes*) page.

**Comment by bkcsoft** [comment] 2016-01-27 16:00
Duplicate of #2462 and fixed in #2480

**Comment by Unknwon** [comment] 2016-01-27 17:44
ping @chrisbrookes

**Comment by chrisbrookes** [comment] 2016-01-27 18:43
Appears to be same issue as #2462, assuming it uses same page/template (/.../compare/branch...owner:branch)? Agree, looks like it'll be fixed with #2480.

**Comment by bkcsoft** [comment] 2016-01-27 18:52
@chrisbrookes 
> *looks like* it'll be fixed with #2480 

Have you tried? If it isn't working @andreynering has more stuff to fix :laughing:

**Comment by chrisbrookes** [comment] 2016-01-27 21:21
I'm struggling to test if it's currently fixed in develop because I'm using the docker image, and it seems to be that develop == latest == Version: 0.8.23.0126. Something not right with the docker builds?

**Comment by andreynering** [comment] 2016-01-27 21:37
@chrisbrookes 

I tested it myself and the problem exists.

I already submited a PR with (another) fix: https://github.com/gogits/gogs/pull/2493

**Comment by chrisbrookes** [comment] 2016-01-27 21:54
Ok, thanks!

**Comment by Unknwon** [comment] 2016-01-28 10:33
This is claimed to be fixed by merging #2491

**Closed** 2016-01-28 11:07 UTC
Labels: bug, feedback needed
