### ISSUE TITLE
Releases page can take forever to load when there are loads

### ISSUE THREAD

**Issue by deanpcmad** [gogits/gogs#3094] opened 2016-05-13 20:02 UTC
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref): latest
- Git version:
- Operating system:
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

I've just created a mirror repository for the rails repo and upon viewing the "Releases" tab, it takes forever to load, sometimes not loading at all. Maybe Gogs should only show the first 10 and paginate the rest? You can see it here - https://try.gogs.io/deanpcmad/rails

**Comment by bkcsoft** [comment] 2016-05-16 19:40
162 seconds to load the Releases-page is waaaay too long :laughing: The underlying problem is related to two different issues, one being pagination (#2164), the other one being fetching commit-count is hella-slow (#3022)

#2164 is claimed to be worked on (though that was over a month ago), #3022 is still being debugged.

**Comment by deanpcmad** [comment] 2016-05-16 19:43
Ha yeah, it does take a while! I'll wait to see. I only setup Gogs over the weekend and I love it already! It's pretty awesome and it runs great on a 512MB DigitalOcean server 😄

**Comment by bkcsoft** [comment] 2016-05-16 21:25
Also, might wanna change the Title to "Release page loads slow with many tags" (so it all fits ^.^ )

**Comment by bkcsoft** [comment] 2016-05-16 21:30
Actually I'm closing this as a duplicate of #2164, it also mentions a fix for it :smiley: 

Opening Issue #2164:
> This lack of pagination causes the relases page to hang for several minutes.

**Closed** 2016-05-16 21:30 UTC
Labels: reviewed/duplicate
