### ISSUE TITLE
Organization settings update, Avatar cannot be empty.

### ISSUE THREAD

**Issue by jmptbl** [gogits/gogs#1305] opened 2015-06-02 15:55 UTC
When updating organization settings, an error appears after submitting: Avatar cannot be empty.

0.6.1.0325 Beta

**Comment by linquize** [comment] 2015-06-03 01:08
duplicate of #1293?

**Comment by jmptbl** [comment] 2015-06-03 06:50
Yes, looks like it might be.  In my setup the Gravatar email form field doesn't appear though.

**Comment by gitsnaf** [comment] 2015-06-19 12:46
I have the same problem with 0.6.1.0325 Beta. I can't update an organization. And I would very much like to upload an avatar for a organization.

**Comment by stewartpark** [comment] 2015-07-27 04:07
I'm experiencing the same problem. I'm using 0.6.1.0719 Beta

**Comment by Unknwon** [comment] 2015-07-28 10:04
Hi there, fixed code has been pushed to `develop` branch and you can now test on https://try.gogs.io/ .

**Closed** 2015-07-30 12:01 UTC
Labels: bug, feedback needed
