### ISSUE TITLE
News feed crash when have emoji in commit message

### ISSUE THREAD

**Issue by dotwoo** [gogits/gogs#2448] opened 2016-01-21 08:09 UTC
登录后回到主页显示失败
返回下面内容：
template: user/dashboard/feeds:41:18: executing "user/dashboard/feeds" at <$push.Commits>: nil pointer evaluating *models.PushCommits.Commits

gogs.log日志显示：
[Macaron] Completed / 500 Internal Server Error in 182.872403ms

其它日志没有发现相关问题。
其它页面正常。
版本为：
当前版本: 0.8.10.1217
Go1.5.1
mysql-server-5.1.73-5.el6_6.x86_64
CentOS release 6.7 (Final)

**Comment by dotwoo** [comment] 2016-01-21 10:54
使用开发版也无更详细的错误输出。

**Comment by esiao** [comment] 2016-01-22 12:05
I have the same error. After some digging it seems related to a commit in my commit history which don't have any Diff : Diff Data Not Available.
If I go to my Dashboard I have the same error :
```
template: user/dashboard/feeds:41:18: executing "user/dashboard/feeds" at <$push.Commits>: nil pointer evaluating *models.PushCommits.Commits
```

My coworkers don't have it on their own, so it's linked to my activity and we verified this because if I give the link to my `profile?tab=activity` they also see the error.

**Comment by MattAndDev** [comment] 2016-01-22 13:44
In our case the json.Unmarshal func in ActionContent2Commits was failing since the JSON on the DB was not valid/broken.

```
if err := json.Unmarshal([]byte(act.GetContent()), push); err != nil {
   return nil
}
```

Primary cause of this was an emoj in a commit message breaking the content JSON.
Fixed the JSON on the DB fixed the problem.

**Comment by esiao** [comment] 2016-01-22 13:47
To complete this information : 
I use emojis in my commits message mainly at the starting of the message to inform about the content. This time it was in the middle and after a comma. It may be linked like a bad interpretation and the json object wasn't completed/closed because of that.

If this can help to solve the issue this was the culprit commit message : 
`fix #7, 🐛 need to refresh the thumbnails`

**Comment by Unknwon** [comment] 2016-01-26 18:56
Thanks your feedback!

@dotwoo is your case same as @esiao ?

@esiao can you confirm that non-emoji commits works fine?

**Comment by esiao** [comment] 2016-01-26 21:09
Yes they do. It was explained further down here : https://github.com/gogits/gogs/issues/2460
And it's related to https://github.com/gogits/gogs/issues/2466

**Comment by Unknwon** [comment] 2016-03-03 19:45
Anyone has this issue can you please reproduce on https://try.gogs.io?

**Comment by esiao** [comment] 2016-03-03 19:56
I created a repo to test
https://try.gogs.io/esiao but there's no public feed with my commit messages on my Feed I don't see them even if they're here.
It's only when going to a feed that it crashed (user or dashboard). The commit history is working fine :
https://try.gogs.io/esiao/TestingRepo/commits/49dd62e69bd5b38a0dc2290ef5a56d0bedb1871f

Maybe that can help you if you have a global access and see the commits feed.

**Comment by Unknwon** [comment] 2016-03-03 19:59
Thanks @esiao !

> It's only when going to a feed that it crashed (user or dashboard).

What does this mean?

**Comment by esiao** [comment] 2016-03-03 20:03
On my own Gogs Instance when I go to :
https://try.gogs.io/ (Dashboard feed)

I have a list of all the commits. This is where it was crashing because of the emojii inserted directly and not in code form.

The other place where it crashed was on my profile so
https://try.gogs.io/esiao

Because same as above there was a feed of my commits and the emoji inside.

**Comment by Unknwon** [comment] 2016-03-03 20:06
> This is where it was crashing because of the emojii inserted directly and not in code form.

But I don't see any crash on demo site? Only problematic commits are not shown.

**Comment by esiao** [comment] 2016-03-03 20:09
So it's working as you intended. (I was talking about my previous experience).
The commits with the emojiis are not showing up and just did one regular which showed up.

**Comment by Unknwon** [comment] 2016-03-03 20:12
@esiao OK great, so maybe you were using too old version (there is another somewhat related fix about nil object, could be fixed together).

So the problem is no longer existed? Do you want to display something like `broken feed data` or right is good?

**Comment by esiao** [comment] 2016-03-03 20:21
@Unknwon The best would have been to strip out the code that make it crash to keep the commit. But not displaying it is not a big issue I guess.

The problem no longer exists because I'm using the code version now like `:bug:` and didn't try with the actual emojii inserted directly since we found out this issue.

**Comment by Unknwon** [comment] 2016-03-03 20:45
@esiao since it breaks JSON somehow, I think it would be impossible to recover the data...

**Comment by Unknwon** [comment] 2016-03-03 20:52
Did a deep research, so, when you have emoji in a commit message, JSON encoding was failed, so the feed body is empty after all.

Closing this issue since no more crash.

**Closed by Unknwon** 2016-03-03 20:52 UTC
Labels: status/needs feedback, status/needs reproduce
