### ISSUE TITLE
Create repository for organization hangs 

### ISSUE THREAD

**Issue by ilisin** [gogits/gogs#1100] opened 2015-03-20 03:48 UTC

**Comment by Unknwon** [comment] 2015-03-20 05:41
Thanks your feedback, what is your Gogs version, system, database and reproduce steps?

**Comment by onuraslan** [comment] 2015-03-20 15:01
I upgraded gogs from v0.5.13 tag to v0.6.0 with linux_amd64.zip build. I just unzipped everything and restarted gogs. I am using SQLITE3 database.

Creating a repository under organization doesn't work. If I try to make a org repo, gogs starting to use 100% CPU and never responds any request. Logs doesn't contain anything about this issue.

**Comment by ilisin** [comment] 2015-03-20 15:09
v0.6 in centos7 , sqllite database

**Comment by Unknwon** [comment] 2015-03-20 15:24
@onuraslan @ilisin thanks for the info!

Looks like SQLite3 driver is broken again under Linux...

**Comment by Nickoladze** [comment] 2015-03-20 19:02
I believe I'm experiencing this issue as well. I'm unable to remove people from an organization.

xorm.log when I hit the remove button:

````
[xorm] [info]  2015/03/20 14:59:55.805352 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [1]
[xorm] [info]  2015/03/20 14:59:55.806213 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [1]
[xorm] [info]  2015/03/20 14:59:55.806905 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `lower_name` = ? LIMIT 1 [args] [dynamicedge]
[xorm] [info]  2015/03/20 14:59:55.807468 [sql] SELECT `id`, `uid`, `org_id`, `is_public`, `is_owner`, `num_teams` FROM `org_user` WHERE ((is_owner=?) AND (uid=?)) AND (org_id=?) LIMIT 1 [args] [true 1 3]
[xorm] [info]  2015/03/20 14:59:55.807745 [sql] SELECT `id`, `uid`, `org_id`, `is_public`, `is_owner`, `num_teams` FROM `org_user` WHERE (uid=?) AND (org_id=?) LIMIT 1 [args] [10 3]
[xorm] [info]  2015/03/20 14:59:55.808106 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [10]
[xorm] [info]  2015/03/20 14:59:55.808901 [sql] SELECT `id`, `lower_name`, `name`, `full_name`, `email`, `passwd`, `login_type`, `login_source`, `login_name`, `type`, `location`, `website`, `rands`, `salt`, `created`, `updated`, `is_active`, `is_admin`, `allow_git_hook`, `avatar`, `avatar_email`, `use_custom_avatar`, `num_followers`, `num_followings`, `num_stars`, `num_repos`, `description`, `num_teams`, `num_members` FROM `user` WHERE `id` = ? LIMIT 1 [args] [3]
[xorm] [info]  2015/03/20 14:59:55.809589 [sql] SELECT `id`, `owner_id`, `lower_name`, `name`, `description`, `website`, `default_branch`, `num_watches`, `num_stars`, `num_forks`, `num_issues`, `num_closed_issues`, `num_pulls`, `num_closed_pulls`, `num_milestones`, `num_closed_milestones`, `is_private`, `is_bare`, `is_mirror`, `is_fork`, `fork_id`, `created`, `updated` FROM `repository` WHERE `owner_id` = ? ORDER BY `updated` DESC [args] [3]
[xorm] [info]  2015/03/20 14:59:55.810968 [sql] SELECT `id`, `uid`, `org_id`, `is_public`, `is_owner`, `num_teams` FROM `org_user` WHERE ((is_owner=?) AND (uid=?)) AND (org_id=?) LIMIT 1 [args] [true 10 3]
[xorm] [info]  2015/03/20 14:59:55.811318 [sql] BEGIN TRANSACTION
[xorm] [info]  2015/03/20 14:59:55.811469 [sql] DELETE FROM `org_user` WHERE `id` = ? AND `id` = ? AND `uid` = ? AND `org_id` = ? AND `num_teams` = ? [args] [9 9 10 3 1]
[xorm] [debug] 2015/03/20 14:59:55.811871 [time] DELETE FROM `org_user` WHERE `id` = ? AND `id` = ? AND `uid` = ? AND `org_id` = ? AND `num_teams` = ? - args [9 9 10 3 1] - execution took: 301112ns
[xorm] [info]  2015/03/20 14:59:55.811989 [sql] UPDATE `user` SET num_members=num_members-1 WHERE id=? [args] [3]
[xorm] [debug] 2015/03/20 14:59:55.812224 [time] UPDATE `user` SET num_members=num_members-1 WHERE id=? - args [3] - execution took: 145406ns
[xorm] [info]  2015/03/20 14:59:55.812359 [sql] DELETE FROM `access` WHERE `user_id` = ? AND `repo_id` = ? [args] [10 5]
[xorm] [debug] 2015/03/20 14:59:55.812573 [time] DELETE FROM `access` WHERE `user_id` = ? AND `repo_id` = ? - args [10 5] - execution took: 62203ns
[xorm] [info]  2015/03/20 14:59:55.812724 [sql] SELECT `id`, `user_id`, `repo_id` FROM `watch` WHERE `user_id` = ? AND `repo_id` = ? LIMIT 1 [args] [10 5]
[xorm] [info]  2015/03/20 14:59:55.813079 [sql] DELETE FROM `access` WHERE `user_id` = ? AND `repo_id` = ? [args] [10 7]
[xorm] [debug] 2015/03/20 14:59:55.813234 [time] DELETE FROM `access` WHERE `user_id` = ? AND `repo_id` = ? - args [10 7] - execution took: 60803ns
[xorm] [info]  2015/03/20 14:59:55.813357 [sql] SELECT `id`, `user_id`, `repo_id` FROM `watch` WHERE `user_id` = ? AND `repo_id` = ? LIMIT 1 [args] [10 7]
[xorm] [info]  2015/03/20 14:59:55.813615 [sql] DELETE FROM `watch` WHERE `user_id` = ? AND `repo_id` = ? [args] [10 7]
[xorm] [debug] 2015/03/20 14:59:55.813800 [time] DELETE FROM `watch` WHERE `user_id` = ? AND `repo_id` = ? - args [10 7] - execution took: 89603ns
[xorm] [info]  2015/03/20 14:59:55.813888 [sql] UPDATE `repository` SET num_watches=num_watches-1 WHERE id=? [args] [7]
[xorm] [debug] 2015/03/20 14:59:55.814075 [time] UPDATE `repository` SET num_watches=num_watches-1 WHERE id=? - args [7] - execution took: 95604ns
[xorm] [info]  2015/03/20 14:59:55.814186 [sql] DELETE FROM `access` WHERE `user_id` = ? AND `repo_id` = ? [args] [10 6]
[xorm] [debug] 2015/03/20 14:59:55.814329 [time] DELETE FROM `access` WHERE `user_id` = ? AND `repo_id` = ? - args [10 6] - execution took: 58603ns
[xorm] [info]  2015/03/20 14:59:55.814497 [sql] SELECT `id`, `user_id`, `repo_id` FROM `watch` WHERE `user_id` = ? AND `repo_id` = ? LIMIT 1 [args] [10 6]
````

**Comment by Unknwon** [comment] 2015-03-21 09:11
@Nickoladze Thanks for the info!

I'll try recompile Gogs with older SQLite3 driver under Linux.

**Comment by Unknwon** [comment] 2015-03-22 17:27
Hi @Nickoladze @ilisin @onuraslan , I've recompiled and uploaded new binary for Linux with older version of SQLite3 driver, so it should work now.

If you're compiling yourself, `git checkout a80c27ba33` for `github.com/mattn/go-sqlite3` will work, too.

**Comment by onuraslan** [comment] 2015-03-23 09:40
It's working fine now.

**Comment by Unknwon** [comment] 2015-03-23 09:43
@onuraslan thanks your confirmation!

**Comment by zenzire** [comment] 2015-03-24 12:51
@Unknwon I downloaded the latest binary and still gogs hangs during creating new repository for organization.

In the log there is only one line:
```
[Macaron] Started POST /repo/create for xx.xx.xx.102
```

**Comment by Unknwon** [comment] 2015-03-24 12:59
@zenzire I've retest under Debian 7 and cannot produce this issue again.

Make sure you did remove the old binary and replaced by the newly downloaded binary.

**Comment by zenzire** [comment] 2015-03-24 13:29
@Unknwon I'm using the latest version 0.6.0.0319 Beta

**Comment by Unknwon** [comment] 2015-03-24 23:23
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:

**Closed by Unknwon** 2015-03-24 23:23 UTC
Labels: bug, feedback needed, third-party

**Comment by markusl** [comment] 2015-03-26 07:53
I'm experiencing the same issue on Windows Server 2012 with SQLite database. Creating repository for Organization completely hangs with last entry in the log being "Started POST /repo/create for 10.x.x.x"

**Comment by Unknwon** [comment] 2015-03-26 11:21
@markusl thanks for your feedback!

I'll recompile binary with an older version of SQLite3 for Windows as well.
