### ISSUE TITLE
Issues counter at local gogs server

### ISSUE THREAD

**Issue by Phatalist** [gogits/gogs#3243] opened 2016-07-08 04:25 UTC
- Gogs version (or commit ref): 0.9.28.0527
- Operating system: ubuntu
- Database:
MySQL
- Can you reproduce the bug at http://try.gogs.io:
Don't know how.

![issues](https://cloud.githubusercontent.com/assets/5849901/16677308/3962e678-44f6-11e6-8041-32f020021a63.PNG)

**Comment by clone1018** [comment] 2016-07-08 04:40
This is fixed by https://github.com/gogits/gogs/pull/3207 and caused by Pull Requests being closed @Phatalist 

You can wait for a Gogs release or you can build off of the develop branch for the fix :)

**Closed** 2016-07-08 04:59 UTC
