### ISSUE TITLE
Advanced issue search box

### ISSUE THREAD

**Issue by Mindiell** [gogits/gogs#3620] opened 2016-09-08 04:20 UTC
It should be great to have a simple textbox to filter issues on their title in the issue list. Search could be as simple as showing all issues having at least a word from the box in their title.

**Comment by sh2ka** [comment] 2016-09-20 19:47
+1. Without this feature it's difficult to work when you have a lot of issues.

**Comment by Biromain** [comment] 2016-09-23 08:23
+1, already 350 issues and it's already hell.

**Comment by sha-red** [comment] 2016-10-26 13:12
Duplicate of #13

**Comment by bkcsoft** [comment] 2016-10-26 17:13
Closed as duplicate of #13

**Closed by bkcsoft** 2016-10-26 17:13 UTC
