### ISSUE TITLE
Windows SSH: Error on handshaking. Auth fail

### ISSUE THREAD

**Issue by duongphuhiep** [gogits/gogs#4160] opened 2017-02-20 12:00 UTC
- Gogs version (or commit ref): 0.9.128.0131
- Git version: 2.10.1.windows.1
- Operating system: Windows Server 2012 R2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): https://gist.github.com/duongphuhiep/aca479b8973f50dac06a0a4d7d6cbf16#file-gogs-log

## Description

Each time I made communication with the server (via ssh), for example:
`git pull origin master`, I have to repeat the same command multiple time before it decide to work.
it always says "Server denied authentication", but if I keep on repeating the command, it will success.

```
> git pull origin master
Server denied authentication request: 20
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

 
> git pull origin master
From git.myserver.com:MyCompany/MyApp
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```

Update: we do not have this problem before (I think that the version 0.9.97.0901 didn't have this problem)

**Comment by Unknwon** [comment] 2017-02-20 18:49
Hi, are you using command line or some Git client tool?

Because this doesn't seem to be the server side problem: https://maximilian-boehm.com/hp2215/Reasons-for-com-jcraft-jsch-JSchException-Auth-fail.htm

**Comment by duongphuhiep** [comment] 2017-02-21 00:43
- on client side (my Windows PC), I (mostly) use command line (I only use a GUI client to visualize history, compare, resolve conflict..)
- 2 of my co-worker has the same problem, they uses TortoiseGit

**Comment by Unknwon** [comment] 2017-02-21 00:48
@duongphuhiep  What command line program are you using? The error is clearly about ** jsch**, have you tested with `git-bash` on Windows?

**Comment by duongphuhiep** [comment] 2017-02-21 16:34
No, I used directly the DOS command line prompt , I also try the Git Bash and got the same problem.

I don't have the problem If I cloned the 'http', it is really the SSH connection problem, I'm looking for a way to test the ssh connection between my PC and the gogs server.

**Comment by Unknwon** [comment] 2017-02-21 16:35
Are you using the system SSH daemon or Gogs's builtin SSH server?

**Comment by duongphuhiep** [comment] 2017-02-21 16:39
the Gogs's builtin server

**Comment by Unknwon** [comment] 2017-02-21 16:41
OK, Gogs's builtin server is certainly written in Go and has absolutely no relation to **jsch**, how did your server setup? Anything related to **jsch** on your server? Because I think it is hijacking the connection.

**Comment by duongphuhiep** [comment] 2017-02-21 16:44
here is my config
https://gist.github.com/duongphuhiep/aca479b8973f50dac06a0a4d7d6cbf16#file-gogs-log

on this machine, there is also teamcity installed, I'm not sure if there is anything to do with it. I'm investigating

**Comment by Unknwon** [comment] 2017-02-21 16:46
>on this machine, there is also teamcity installed, I'm not sure if there is anything to do with it. I'm investigating

I think it is entirely possible, TeamCity seems using **jsch**: https://teamcity-support.jetbrains.com/hc/en-us/community/posts/206155429-Integrating-Amazon-AWS-CodeCommit-with-TeamCity?page=1#community_comment_206256775

**Comment by duongphuhiep** [comment] 2017-02-21 17:34
I stopped teamcity on the machine and even restart the gogs webserver, we don't have jsch in the log file anymore. 

The problem is not completely gone. I still have to repeate the command (eg: `git fetch`) 2 or 3 times (but not as much as before). For each failure time I see the problem Handshake in the log file:

```
2017/02/21 18:18:13 [I] Log Mode: File(Info)
2017/02/21 18:18:13 [I] Cache Service Enabled
2017/02/21 18:18:13 [I] Session Service Enabled
2017/02/21 18:18:13 [I] Git Version: 2.10.1
2017/02/21 18:18:14 [I] SQLite3 Supported
2017/02/21 18:18:14 [I] Run Mode: Production
2017/02/21 18:18:14 [I] SSH server started on 0.0.0.0:22
2017/02/21 18:18:14 [I] Listen: http://192.168.XXX.XXX:80
2017/02/21 18:18:35 [W] SSH: Handshaking was terminated: EOF
2017/02/21 18:19:10 [W] SSH: Handshaking was terminated: EOF
2017/02/21 18:20:20 [W] SSH: Handshaking was terminated: EOF
2017/02/21 18:21:17 [W] SSH: Handshaking was terminated: EOF
```

I will continue to investigate tomorrow!

thank you very much

**Comment by Unknwon** [comment] 2017-02-21 17:35
No problem!

**Comment by Unknwon** [comment] 2017-02-25 00:17
I'm closing for now until new proves come in.

**Comment by duongphuhiep** [comment] 2017-02-27 10:32
the log message
```
2017/02/27 11:12:04 [W] SSH: Handshaking was terminated: EOF
```
is probably coming from

https://github.com/gogits/gogs/blob/master/modules/ssh/ssh.go#L135

It seems that

The handshake is a little bit slow in my case, 

Each time I send a request eg. `git fetch`, the request will failed but it will initialize the Handshake. I just have to wait for a few seconds then send `git fetch` request again..

I'm searching a way to test this function...

**Comment by Unknwon** [comment] 2017-02-27 17:26
@duongphuhiep have you test on a fresh server? Because we already knew teamcity could cause problem.

**Comment by duongphuhiep** [comment] 2017-02-28 11:28
no, but I stopped the teamcity server and ensure that there isn't any java process running on this machine.
Since I did that, there is no longer any **jsch** in the logs

**Comment by Unknwon** [comment] 2017-02-28 11:29
@duongphuhiep OK, does this affect pushing? I saw these sometimes, but could just be another hidden process trying to make some noisy.

**Comment by duongphuhiep** [comment] 2017-02-28 11:36
yes, it affects also `git clone`, `git push` and `git pull` - all functions which need to communicate to the ssh server

**Comment by Unknwon** [comment] 2017-02-28 11:39
@duongphuhiep have you tried on a fresh server? because locally sometimes I got these messages but I can still push/pull without problem..

**Comment by duongphuhiep** [comment] 2017-02-28 11:56
I don't have a fresh server right now, I might try in another test machine that I have, but the current server is the cleanest that I have. On this machine, there are only TeamCity (which is disabled) and Gogs.

There is no database, or anything else (because we want to make this machine solely for source codes repositories).

At the moment, I can do everything: `git clone`, `git push`, `git pull`...  just fine, but it won't work for the first try: "Server denied authentication request: 20"

Each time, I will have to repeat `git fetch`, `git fetch`, `git fetch`.... or  `git push`, `git push`, `git push`... until it works.

We might also ignore the ssh and get everyone switch to `http` (for http everything work on first try). so it is not blocking for us, it is just annoying..

**Comment by Unknwon** [comment] 2017-02-28 11:59
@duongphuhiep hmm... running out of ideas, maybe try out latest 0.10.1 for any "magic" reasons?

**Comment by Unknwon** [comment] 2017-03-02 02:34
I can confirm this is a bug, just updated ssh-related dependencies, not sure if this could solve the problem.

Please try latest `develop` branch and make sure you get the version `0.10.3.0301`. Thanks!

**Closed** 2017-03-07 04:57 UTC
Labels: kind/bug, status/needs feedback

**Comment by trompx** [comment] 2017-05-19 00:27
Hello,

Just to let people know, I had the same problem except that I did not have any handshake error log.
I had to push 3-4 times before success.
I was using version 0.9.128
I just updated to version 0.11.4 and everything works fine (at least for now).

Thanks for the fix Unknwon
