### ISSUE TITLE
Removing user from collaboration removes repositiory

### ISSUE THREAD

**Issue by flopaul** [gogits/gogs#1279] opened 2015-05-15 03:18 UTC
migrated repo to organisation. added user as collaborator. removed user from collaboration removes repo from web site.

**Comment by yeleleo** [comment] 2015-05-26 22:25
I can confirm the same bug, really annoying. BTW, repository not removing, only everybody's permissions.
// using PostgreSQL

**Comment by gtsalles** [comment] 2015-06-02 12:38
From what I see, it doesn't actually delete the repository, I've debug it and saw that in file routers/users/home.go line 179, it runs a query to get a user by its name and, when it doesn't find, throws a 404 error.
I've checked in the database, the repository is still there.
I just don't know how to fix it :(

**Comment by gtsalles** [comment] 2015-06-02 13:27
I think I've solved it.
In my case, the user wasn't a part of the team, only the group, when I added him to the team, I've gain access to repository again.
Hope it works for you guys.

**Comment by webus** [comment] 2015-06-04 12:50
It not works for me. I just upgrade gogs to latest version (0.6.1).  And then i delete user from repository, gogs return 404 and repository is not available.

**Comment by makhov** [comment] 2015-06-05 10:04
Fixed at new Gogs reincarnation Gitea — https://github.com/go-gitea/gitea/pull/24

**Comment by Unknwon** [comment] 2015-07-14 14:59
Hi all, fix has been pushed to `master` branch. :satisfied: 

Thanks to @makhov , I did small changes on his PR: https://github.com/gogits/gogs/commit/663c28beb61d5c1319665f195b7e2f4f370c3ea9

**Comment by Unknwon** [comment] 2015-07-30 13:55
Closed as implemented. :octocat:

**Closed by Unknwon** 2015-07-30 13:55 UTC
Labels: bug, feedback needed
