### ISSUE TITLE
README.txt file rendered with injected HTML and shown as empty inline

### ISSUE THREAD

**Issue by strk** [gogits/gogs#3749] opened 2016-10-10 11:24 UTC
A README.txt file in the root of repositories seems to trigger some code to automatically show the content inline but the content is shown as empty. Clicking on the file to show it in the browser shows it as including HTML while there is no HTML in the real file.

You can see this on try.gogs.io: https://try.gogs.io/strk/readme.txt

If you clone the repository you can see there is no HTML in the file, but the file browser injects the html:
https://try.gogs.io/strk/readme.txt/src/master/README.txt

**Comment by bkcsoft** [comment] 2016-10-10 11:34
Seems to be using the markdown renderer

**Comment by jorgesumle** [comment] 2017-01-23 00:16
Has this been fixed in https://github.com/go-gitea/gitea/pull/95?

**Comment by strk** [comment] 2017-01-23 07:44
Yes, fixed in Gitea

**Comment by Unknwon** [comment] 2017-01-24 21:58
The demo file was cleaned in the last cycle, would you mind upload another copy of it?

**Comment by strk** [comment] 2017-01-25 08:39
It's already fixed in Gitea, you can backport the fix if you want.

**Comment by Unknwon** [comment] 2017-01-25 11:04
I can not determine the cause of issue based on the patch.

**Comment by strk** [comment] 2017-01-25 11:06
Then just push a README.txt file with some simple text, like
3 lines of text, with empty lines in between, and check how
it is rendered and shown

**Comment by Unknwon** [comment] 2017-01-25 12:14
[Patch](https://github.com/gogits/gogs/commit/8cb903fbbb6de5decb443af1481b44b5c1a426d1) has been pushed to `develop` branch and you can also test on https://try.gogs.io.

**Closed** 2017-01-31 12:17 UTC
Labels: kind/bug, status/needs feedback
