### ISSUE TITLE
Deleted organizations are not entirely removed

### ISSUE THREAD

**Issue by TimoDritschler** [gogits/gogs#942] opened 2015-02-12 15:04 UTC
When deleting an Organization it is not removed entirely from the database. You can still see the deleted organization in the backend and visit its ```/org/<name>``` page, but it has no settings page and it can not be used at all. Also, the organizations name is then blocked for further use, since the name-conflict check, when creating a new organization, still sees the old one in the database, apparently.

Gogs Version 0.5.11.0103 Beta

**Comment by Unknwon** [comment] 2015-02-12 17:47
Thanks your feedback, we'll get on this ASAP!

**Comment by Unknwon** [comment] 2015-02-22 06:45
Hi @TimoDritschler , I've tested locally and was not able to reproduce the problem you described. 

You may want to provide more information like which system and database are you using?

**Comment by matze** [comment] 2015-02-23 13:23
I am administrating said machine. It's running a virtualized Ubuntu 14.04.2 and uses the SQLite backend. I guess it's a bad idea™ to mess with the gogs.db?

**Comment by Unknwon** [comment] 2015-02-23 18:29
@matze thanks for your info! Let me do more tests with SQLite3 again.

**Comment by Unknwon** [comment] 2015-03-16 06:25
Hi @matze @TimoDritschler , I still cannot reproduce this problem in SQLite3 or MySQL.

**Comment by Unknwon** [comment] 2015-03-24 23:22
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:

**Closed by Unknwon** 2015-03-24 23:22 UTC
Labels: feedback needed, reproduce needed

**Comment by matze** [comment] 2015-03-25 07:15
I just updated to 0.6.0 and tried to see if I can remove one of these old organizations but no cogs, no success:

![gogs](https://cloud.githubusercontent.com/assets/115270/6819787/f9310604-d2c6-11e4-892e-d56f873851a3.png)

P.S.: non-contributors cannot open discussion but still comment :-)

**Comment by Unknwon** [comment] 2015-03-25 10:19
@matze thanks for quick feedback!

Do you have any log when delete the organization?

And can you delete newly created organization?
